_authors/osci_2023/pranishd1.markdown

Added Pranish Dahal (pranishd1) as author for #osci2023
Completed Task1 of OSCI_2023

[OSCI] Add new osci author Pranish Dahal

---

_authors/osci_2023/pranavjad.markdown

Adds a new OSCI author pranavjad to the _authors/osci2023 folder.
n/a

[OSCI] Add new osci author pranavjad

---

_authors/osci_2023/nishantsinghal19.markdown

Adding new author NishantSinghal19

OSCII: Adding new Author nishantsinghal19

---

_authors/osci_2023/kalyanr.markdown

Adds Kalyan as OSCI author to the repository

[OSCI] add new osci author kalyanr

---

_authors/osci_2023/arnoldtingsu.markdown

- [ x ] Commits are signed per the DCO using --signoff

[OSCI] Add new OSCI author arnoldtingsu 

---

_authors/osci_2023/marcaldrichbrophy.markdown

Adds Marc Brophy profile to OSCI profiles.

Adding Marc Brophy profile to OSCI authors. Author: Marc Brophy

---

_authors/osci_2023/wiilie_the_lord.markdown

Add willie-the-lord as new author 
[X] Commits are signed per the DCO using --signoff

[OSCI] Add willie-the-lord as new author 

---

_authors/osci_2023/rlaracon.markdown
_authors/rlaracon.markdown

Added new OSCI author rlaracon
N/A

[OSCI] Added new OSCI author rlaracon

---

_authors/osci_2023/DesmondWillowbrook.markdown

Add Kartavya Vashishstha as an author

[OSCI] Add Kartavya Vashishtha as an author

---

_authors/osci_2023/kubabal.markdown

OSCI: added kubabal to authors

---

_authors/osci_2023/lucaswang750.md

Add new author and profile
None

[OSCI] Add new author Lucas Wang

---

_authors/osci_2023/rohan-agrawal.markdown

[OSC] Adds new author rohan19a

---

_authors/osci_2023/deniskilseev.markdown

Adds new author deniskilseev
- [☑️] Commits are signed per the DCO using --signoff

[OSCI]: Adds new author deniskilseev

---

_authors/osci_2023/mekaeelpc.markdown

[OSCI]: Adds new author mekaeel

---

_authors/osci_2023/prabhask.markdown
_authors/prabhask.markdown

[OSCI] Add new author Prabhas Kurapati

---

_authors/osci_2023/karthiksubramanian.markdown

Added OSCI author karthiks3000 in new markdown file karthiksubramanian.markdown
N/A

OSCI: add new osci author karthiks3000

---

_authors/osci_2023/officerchul.markdown

OSCI: Adds new author OfficerChul

---

_authors/osci_2023/divitr.markdown

[OSCI] Adds new author divitr

---

_authors/osci_2023/caileyjen.markdown

[OSCI] Adds new author caileyjen

---

_authors/osci_2023/wgollapudi.markdown

adding a new author wgollapudi

[OSCI]: Adds new author wgollapudi

---

_authors/osci_2023/tanupa.markdown

Adds tanupa as a new OSCI author to the repository 

[OSCI] add new osci author tanupa

---

_authors/osci_2023/strifale.markdown

added author strifale to osci_2023

---

_authors/osci_2023/abhinavgarg90.markdown

added my details

---

_authors/osci_2023/vnandi.markdown

[OSCI] Adding Profile

---

_authors/osci_2023/yash-sinhal.markdown

OSCI: Adds new author yash-sinhal

---

_authors/osci_2023/maddoxschmidlkofer.markdown

[OSCI] added maddox as author

---

_authors/osci_2023/jacobch.markdown

[OSCI] Added new author jacobch 

---

_authors/osci_2023/hjohnross.markdown

[OSCI] Added new author hJohnRoss

---

_authors/osci_2023/noahdohrmann.markdown

Add Noah Dohrmann author file for OSCI 2023

add noah's author file

---

_authors/osci_2023/kohinoor98.markdown

Added myself to _authors/osci-2023/kohinoor98.markdown
NA

[OSCI] added author - kohinoor98

---

_authors/osci_2023/hegde25sath.markdown

[OSCI] Adding my profile markdown page with prelim details

---

_authors/osci_2023/ortegaa32.markdown

Adding new author markdown file: Arturo Ortega
None

[OSCI] Add new author ortegaa32

---

_authors/osci_2023/CMDWillYang.markdown

Added myself to _authors/osci_2023
N/A

add new osci author CMDWillYang

---

_authors/osci_2023/joshua152.markdown

Added profile for Joshua Au
None

[OSCI] Added new author Joshua152

---

_authors/osci_2023/rahulsiddharth.markdown

Rahul branch2

---

_authors/osci_2023/yiming.markdown
_authors/yiming.markdown

add new author

---

_authors/osci_2023/RobertKilkenny.markdown

Adds myself (Robert Kilkenny) as an author to the project.
No issues resolved

Adding my profile to _authors in OSCI project!

---

_authors/osci_2023/mingyang-shi.markdown

Adding a new author for OSCI 2023: Mingyang Shi
I used a different email from the email I used to register for this program (mmyyshi@gmail.com). The email I used to sign the commit was my github account email, which is mshi@ucsd.edu

Adding a new author: Mingyang Shi

---

_authors/osci_2023/michaelakinosho.markdown

Adds Michael Akinosho as a OSCI-2023 author
None

Add new author Michael Akinosho

---

_authors/osci_2023/sachin.markdown

Add new OSCI author Sachin
None

[OSCI] Add new OSCI author Sachin

---

_authors/osci_2023/SamriddhiS2.markdown

Adds new OSCI 2023 author: Samriddhi Sivakumar
None

Add new author: Samriddhi Sivakumar

---

_authors/osci_2023/taraharmon.markdown
_authors/taraharmon.markdown

Add new author Tara Harmon

---

_authors/osci_2023/chawinphat.markdown

[OSCI] Added new author Chawinphat

---

_authors/osci_2023/vinay-vinod.markdown

Added name to authors

---

_authors/osci_2023/ssnekha.markdown

[OSCI] Adds new author snekha

---

_authors/osci_2023/Yeek2.markdown

[OSCI] Adds new author Yeek2

---

_authors/osci_2023/aigerim.markdown

[OSCI] Adds new author aigerim

---

_authors/osci_2023/AyaSadyk.markdown

[OCSI: Adds new author AyaSadyk

---

_authors/osci_2023/wrch0712.markdown

[OSCI] Adds new author wrch0712

---

_authors/osci_2023/adrianmp.markdown

[OSCI] Adding profile to osci_2023 AdrianMPCodes

---

_authors/osci_2023/kumarj.markdown

[OSCI] Adds new author kumarjana

---

_authors/osci_2023/patty8122.markdown

[OSCI] Adds new author Patty8122

---

_authors/osci_2023/jjafarovs.markdown

OSCI: Adds new author jjafarovs

---

_authors/osci_2023/faradawn.markdown

[OSCI] Add new author Faradawn Yang

---

_authors/osci_2023/yvonnewangg.markdown

[OSCI] Adds new author yvonnewangg

---

_authors/osci_2023/rishabh1815769.markdown

Adds new author rishabh1815769

[OSCI] Adds new author rishabh1815769

---

_authors/osci_2023/afrodidact.markdown

Adds afrodidact as an author within the OSCI section of the OpenSearch Project Website repository
N/A

[OSCI] Adds new author afrodidact

---

_authors/osci_2023/ikibo.markdown

OSCI-2023 new author "ikibo" added

[OSCI-2023] new author ikibo

---

events/opensearchcon/sessions/index.html

Add end-to-end relevance to session schedule

Add end-to-end relevance to session schedule

---

_authors/osci_2023/qthornton9.markdown

[adding author qthornton9 to OSCI]
[none]

OSCI2023: adds new author qthornton9

---

_authors/osci_2023/SaxenaAnushka102.markdown

Adds new author SaxenaAnushka102

[OSCI]: Adds new author SaxenaAnushka102

---

_authors/osci_2023/amanaswini.markdown

added new osci author-AManaswini

---

_authors/alexkonnaris.markdown
_authors/osci_2023/alexkonnaris.markdown

Alex Konnaris Contributing your first PR

---

_authors/osci_2023/danhdav.markdown

[OSCI] Add new author danhdav

---

_authors/osci_2023/sejal-verma.markdown

[OSCI] adds new author sejal-verma

---

_authors/osci_2023/andrewchen.markdown

Adds new author Andrew Chen.
N/A

Uploaded user profile to authors.

---

_authors/osci_2023/shreyavenkat.markdown

[OSCI] Author File Changes by Shreya Venkat

---

_authors/osci_2023/tranngocsongtruc.markdown

Adds new author tranngocsongtruc

OSCI: Adds new author tranngocsongtruc

---

_authors/osci_2023/zachj.markdown

This change adds a new author page as outlined in this guide: https://gist.github.com/ashwin-pc/84ee8bd937caecd6a193e2a6a4c4fe34
NA
- [X ] Commits are signed per the DCO using --signoff
changes committed using git commit -s -m ""

[OSCI] Add new author

---

_authors/osci_2023/arnavarora.markdown

Adds new author Arnav Arora
Introduces myself to the OSCI Github repo
- [✔] Commits are signed per the DCO using --signoff

OSCI: Adds new author arnav-arora

---

_authors/osci_2023/mvarlamov222.markdown

Created a new profile for mvarlamov222

Created profile for mvarlamov222

---

_includes/platform-page-header.html
_sass/_redesign-platform.scss
events/opensearchcon/exhibitors/index.html

Fixes problems with conference page breadcrumbs.
Fixes conference exhibitor listing page button styles.
https://github.com/opensearch-project/project-website/issues/2281
https://github.com/opensearch-project/project-website/issues/2280

Fix conference buttons and breadcrumbs

---

_speaker_sessions/mshah_session.md
events/opensearchcon/sessions/index.html

Unfuzz details of Mehul's Session. 

Staging changes to Mehul's Session

---

_redesign_heros/1.md

modify the link in the 2.10 hero banner
n/a

210 hero link

---

_authors/zhujiaxiang.markdown

Update Peter Zhu author profile with more links and information

Update Peter Zhu author profile with more links and information

---

_posts/2023-10-09-byte-quantized-vectors-in-opensearch.md

Some extra characters made it in the final copy as well as a quick edit to the frontmatter to refer to authors by their shortname. 

A quick frontmatter and markdown fix.

---

_posts/2023-10-09-byte-quantized-vectors-in-opensearch.md

Table presentation issues in latest blog. Solving at the behest of the author. 

adding `has_science_table` to add table borders.

---

_posts/2023-10-09-Announcing-Data-Prepper-2.5.0.md
_posts/2023-10-09-byte-quantized-vectors-in-opensearch.md

Fix table formatting, math, and image width in byte vector blog
https://github.com/opensearch-project/project-website/pull/2341

Quick blog edit - push to prod

---

_events/2023-1018-2-11-release-meetings.markdown

Creates an Event page in support of the 2.11 release
n/a

2.11 Release event

---

_events/2023-1018-2-11-release-meetings.markdown
_posts/2023-10-09-byte-quantized-vectors-in-opensearch.md

2.11 Release event
https://github.com/opensearch-project/project-website/pull/2343

push the 211 event page to prod

---

_events/2023-1018-2-11-release-meetings.markdown

Small edit to the 2.11 release event
n/a

Edit to 2.11 release event

---

_authors/oeyh.markdown

Update contributor to maintainer.
N/A

Update oeyh's bio for Data Prepper 2.5 blog post

---

slack.markdown

New invite link for the Slack page
n/a

Update Slack invite

---

_events/2023-1020-dev-triage-ml-commons.markdown
_events/2023-1103-dev-triage-ml-commons.markdown
_events/2023-1117-dev-triage-ml-commons.markdown
_events/2023-1201-dev-triage-ml-commons.markdown

Biweekly ml-commons events until December
n/a

ml-commons events

---

_authors/osci_2023/tiffanylamm.markdown
_authors/tiffanylamm.markdown

add tiffanylamm to _author
none

[OSCI]add new author tiffanylamm

---

_authors/osci_2023/samarthg1705.markdown

Add new author - samarthg1705 (Samarth Ghai)
N/A

[OCSI] Add New Author samarthg1705

---

_authors/osci_2023/noicebroice.markdown

adds author md for noicebroice
N/A

[OSCI] add author noicebroice

---

_authors/osci_2023/soumyatanwar.markdown
_authors/soumyatanwar.markdown

OSCI: Adds new author soumyatanwar

---

_authors/osci_2023/eegurt.markdown

[OSCI]: Adds new author eegurt

---

_authors/osci_2023/feindr54.markdown

Adding a new author feindr54 (Changxiang Gao)

[OSCI 2023] Adds new author feindr54

---

_authors/osci_2023/xevion.markdown

- Add an author page for Ryan Walters (Xevion)

[OSCI] Add new author Xevion

---

_authors/osci_2023/wuzhijing0127.markdown

Created new profile for wuzhijin0127

Created profile for wuzhijing0127

---

_authors/osci_2023/vedangjoshi.markdown

Placing Vedang Joshi in the authors section of the website repository. 

[OSCI] Adds new author VJoshi380

---

_authors/osci_2023/miriamcheng.markdown

[Added new author miriamcheng]
[None]

OSCI: Adds new author miriamcheng

---

_authors/osci_2023/davidosorno.markdown

[OSCI] Adds new author davidosorno

---

_authors/osci_2023/in-odds.markdown

Adds my personal profile details
None

add Idris author markdown

---

_authors/osci_2023/dejaa1.markdown

adds a new author and fixes previous markdown issue
fixes previous mistake

adding new author profile dejaa1

---

_events/2023-1110-amsterdam-user-group.markdown

Add Amsterdam User Group event
n/a

Add amsterdam event

---

_data/top_nav.yml
_events/2023-1105-ubuntu-summit.markdown
_redesign_heros/2.md
_redesign_heros/_2.md

Ubuntu Summit event, top-nav edit for the About page, new hero banner for survey
n/a

Event menu hero banner edits

---

_events/2023-1106-dev-triage-security.markdown
_events/2023-1113-dev-triage-security.markdown
_events/2023-1120-dev-triage-security.markdown

Updates the security triaging meetings info for the events pages. 

Update triaging meetings URL and times

---

.github/vale/styles/OpenSearch/SubstitutionsError.yml
.github/vale/styles/Vocab/OpenSearch/Words/accept.txt
_includes/header.html

Add terms to Vale (per style guide) and correct capitalization for the placeholder string in the search box.

Add terms to Vale and correct placeholder capitalization

---

_events/2023-1018-2-11-release-meetings.markdown

Add 2.11 retrospective meeting details to 2.11 release post. 
Also updated the chime meeting details to use our chime call since @krisfreedain is out. 

Add 2.11 retrospective meeting details

---

_events/2023-1018-2-11-release-meetings.markdown

Small change to the meta for the 2.11 release retro event
n/a

2.11 release retro update

---

BLOG_GUIDE.md
README.md

Add a blog guide with reference information about formatting blog posts and adding authors.

Add blog guide

---

_speaker_sessions/ajadhav_session.md
_speaker_sessions/bnauheimer_session.md
_speaker_sessions/byucel_session.md
_speaker_sessions/jkowall_session.md
_speaker_sessions/odenloye_session.md
_speaker_sessions/sherman_session.md
_speaker_sessions/zsegal_session.md

Adds remaining 7 of the first batch of available youtube videos from OpenSearchCon 2023

Adds remaining 7 of the first batch of available youtube videos from OpenSearchCon 2023

---

_events/2023-1116-fluent-community-meetup.markdown
_events/2023-1130-fluent-community-meetup.markdown
_events/2023-1214-fluent-community-meetup.markdown

Added the next three upcoming Fluent Community meetings.
Adds upcoming Fluent Community meetings to the event calendar
NA

fluent community meetings

---

_events/2023-1114-community-meeting.markdown
_events/2023-1128-community-meeting.markdown
_events/2023-1212-community-meeting.markdown

New Community Meeting events for Nov/Dec
n/a

New Community Meeting events

---

_posts/2023-10-28-optimize-refresh-interval.markdown

Published blog had old date, putting it in second in the list. 

Changing date to today's date so as to feature it.

---

_posts/2023-09-21-Introducing-Live-Traffic-Capture-and-Replay-For-Migrations-and-Upgrades.md

Fixes name to address co-author missing on the blog issue.
#2388 

Fixing shortname as recommended

---

releases.md

add 2.11.1 dates to releases page
n/a

add 2.11.1 to releases page

---

_sass/_fullwidth-with-breadcrumbs.scss
_sass/_tables.scss
releases.md

Updates table styles and usage on releases page

Updates table styles and usage on releases page

---

_posts/2023-11-20-unlocking-the-secrets-to-ingestion.md

A quick syntax edit for images. 

A few of these images links required a leading forward slash.

---

_posts/2023-11-20-unlocking-the-secrets-to-ingestion.md
releases.md

release page update
https://github.com/opensearch-project/project-website/pull/2437

push out changes to releases page

---

_posts/2023-11-21-how-to-create-custom-threat-detection-rules.md

Fixes Jimish's bio on blog
N/A

Fixing Jimish author

---

_data/top_nav.yml

Small language change for the top-nav
n/a

Menu update for playground

---

_data/top_nav.yml
_posts/2023-11-21-how-to-create-custom-threat-detection-rules.md

Menu update for playground
https://github.com/opensearch-project/project-website/pull/2443

Small top-nav change

---

_posts/2023-11-24-sessions-at-reinvent.md

Fixing typo

---

_events/2022-0921-opensearchcon.markdown
_events/2022-1024-open-observability-day.markdown
_events/2022-1107-ubuntu-summit.markdown
_events/2023-0205-opensearch-at-fosdem23 copy.markdown
_events/2023-0307-awsopensearch-unplugged.markdown
_events/2023-0426-rta-sumit.markdown
_events/2023-0510-devoxxuk.markdown
_events/2023-0510-open-source-summit.markdown
_events/2023-0511-open-source-summit.markdown
_events/2023-0607-chicago-search-meetup.markdown
_events/2023-0927-opensearchcon.markdown
_events/2023-1105-ubuntu-summit.markdown
_events/2023-1108-haystack-austin.markdown
_events/2023-1110-amsterdam-user-group.markdown
_events/_sample.markdown
events/index.html
events/past.html

This is a follow-up to #2288 (merging this PR will automatically marked that older PR as merded).  More events have incomplete / invalid information.  Fix it.

Fix more events metadata

---

_includes/header.html
_layouts/homepage.html
_sass/_community_projects.scss
_sass/_custom-search.scss
_sass/_nested-nav.scss
_sass/_opensearch.scss
_sass/_partners.scss
_sass/_platform.scss
_sass/_pygments.scss
_sass/_redesign-hero-carousel.scss
_sass/_redesign.scss
_sass/_style.scss
_sass/_tables.scss
_sass/_utils.scss
opensearchcon2023-cfp.html

Fixes header navigation menu mobile bug.
Removes dependency on rem units.
Fixes a bug in the responsiveness of the homepage hero banner carousel that I had caused and only partially fixed recently. Now it's fixed all the way.

Fixes header navigation menu mobile bug; removes dependency on rem units

---

_authors/osci_2023/chenxi-wang.markdown

add chenxi wang to author, who is from osci-2023 and worked on [alerting-dashboards-plugin](https://github.com/opensearch-project/alerting-dashboards-plugin)
- add chenxi to author

add chenxi to author

---

_events/2023-1208-open-compliance-summit-security-analytics.markdown

Adds Aparna's talk to the events page
n/a

Open Compliance Summit event

---

_authors/amistrn.markdown

this is an outdated bio of mine, updating it
N/A

Updating my bio on the site

---

_artifacts/opensearch-1.3/arm64/opensearch-1.3.14-docker-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.14-freebsd-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.14-linux-arm64-deb.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.14-linux-arm64-rpm.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.14-linux-arm64-yum.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.14-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.14-min-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.14-docker-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.14-linux-arm64-deb.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.14-linux-arm64-rpm.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.14-linux-arm64-yum.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.14-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.14-min-linux-arm64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.14-docker-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.14-freebsd-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.14-linux-x64-deb.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.14-linux-x64-rpm.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.14-linux-x64-yum.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.14-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.14-min-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.14-windows-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.14-docker-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.14-linux-x64-deb.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.14-linux-x64-rpm.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.14-linux-x64-yum.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.14-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.14-min-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.14-windows-x64.markdown
_artifacts/opensearch-1.3/x86/opensearch-1.3.14-freebsd-x86.markdown
_versions/2023-12-12-opensearch-1.3.14.markdown

To support the 1.3.14 release, currently expected Dec 12
n/a

Download pages for the 1.3.14 release

---

_events/2023-1219-dev-triage-ml-commons.markdown

updating next ml-commons office hour

---

authors/jonahkowall.markdown

Changing my bio with some updates

Update bio for Jonah Kowall

---

_events/2023-1219-dev-triage-ml-commons.markdown
authors/jonahkowall.markdown

Updating meetup link and Jkowall bio
N/A

Updating meetup link and Jkowall bio

---

.github/vale/styles/Vocab/OpenSearch/Products/accept.txt
.github/workflows/vale.yml

Roll back Vale version to correct sentence capitalization errors

Roll back Vale version to correct sentence capitalization errors

---

_data/top_nav.yml

Linking to /events

---

_events/2024-0116-community-meeting.markdown
_events/2024-0130-community-meeting.markdown
_events/2024-0213-community-meeting.markdown
_events/2024-0227-community-meeting.markdown

Community Events for January and February
n/a

Community meeting events for Jan Feb

---

.github/workflows/vale.yml

Revert to a previous version because of go errors in the new versions.

Roll back Vale even more to fix more errors

---

_includes/redesign_buttons.html
_layouts/fullwidth-with-breadcrumbs.html
_sass/_fullwidth-with-breadcrumbs.scss
_sass/_redesign.scss
events/opensearchcon/index.md

Migrates the opensearchcon landing page into the new design system

Migrates the opensearchcon landing page into the new design system

---

_posts/2024-01-03-opensearch-performance-improvements.md

Small improvement on the performance blog header naming

Small improvement on the performance blog header naming

---

_posts/2024-01-16-opensearch-ai-retrospective.md

Changing date for ai retrospective blog.

---

_events/2024-0119-dev-triage-ml-commons.markdown

Adding the next ML Commons Triage meeting
N/A

Adding the first ML Commons triage for next year

---

_events/2024-0131-fluent-bit-opensearch-webinar.markdown
_events/2024-0208-fluent-community-meetup.markdown
_events/2024-0222-fluent-community-meetup.markdown

Add two meetups and the OpenSearch / Fluent Bit joint webinar to the OpenSearch event calendar
NA
- [X ] Commits are signed per the DCO using --signoff

Fluent Bit events February 2024

---

_authors/elifish.markdown
_posts/2024-01-24-trust-in-open-source-software.md

Edit to 'trust in open-source' blog & update to Eli's author profile
n/a

Author and blog edits

---

.github/vale/styles/OpenSearch/SubstitutionsError.yml
.github/vale/styles/Vocab/OpenSearch/Products/accept.txt
.github/vale/styles/Vocab/OpenSearch/Words/accept.txt

Add more words to Vale

---

_data/top_nav.yml

Add documentation subsections to top menu

Add documentation subsections to top menu

---

_events/2024-0202-dev-triage-ml-commons.markdown

Adding new ML Commons Meetup
N/A

Adding new ML Commons Meetup

---

CODE_OF_CONDUCT.md
_authors/_sample.markdown
_authors/krisfreedain.markdown

Update to the Code of Conduct page to match updated wording in the .github repo (see PR https://github.com/opensearch-project/.github/pull/185) 
Minor update to my author profile 
N/A

Code of Conduct update & minor update to my author profile

---

releases.md

We received feedback from the community and the Leadership Committee that it was challenging to know/find details, so I'm enhancing the Releases page to have Release Manager and Tracking Issue for each release.
I've also reversed release history - latest is at the top for ease of use. 
N/A

Update to releases page

---

_events/2024-0213-dev-triage-ml-commons.markdown

[ml-commons triage meeting setup for 02-13-2024]

ml-commons triage meeting setup for 02-13-2024

---

_events/2024-0213-dev-triage-ml-commons.markdown

Fixing metadata for the ML Triage event
N/A

Fixing meta for ML Event

---

_events/2024-0213-dev-triage-ml-commons.markdown
_redesign_use_cases/platform-landing-page.markdown

Fixing metadata for the ML Triage Meeting
N/A

Fixing metadata for ML event

---

_events/2024-0214-2-12-release-meetings.markdown

Add 2.12.0 release event 
Part of https://github.com/opensearch-project/opensearch-build/issues/4115 

Add 2.12.0 release event

---

_events/2024-0214-2-12-release-meetings.markdown

Go/no-go placeholder for 2.12.0

Publishes go/no-go event placeholder. 

---

_events/2024-0214-2-12-release-meetings.markdown

Part of https://github.com/opensearch-project/opensearch-build/issues/4115

[Release 2.12.0] Update meeting ID

---

_events/2024-0214-2-12-release-meetings.markdown

Add additional Go / No-Go voting call
Part of https://github.com/opensearch-project/opensearch-build/issues/4115

Add additional Go / No-Go voting call

---

_events/2024-0214-2-12-release-meetings.markdown

Update retro meeting date
Part of https://github.com/opensearch-project/opensearch-build/issues/4115

[Release 2.12.0] Update retro meeting date

---

_redesign_heros/1.md

Updates herobanner for 2.12 release.

Changing hero banner to read 2.12

---

releases.md

Updated the release manager for 1.3.15 release and fixed few alignment issues with markdown.
NA

Update the release manager for 1.3.15 release

---

_events/2024-0227-dev-triage-ml-commons.markdown

[triage meeting for ml-commons on 2024-02-27]

triage meeting for ml-commons on 2024-02-27

---

_events/2024-0312-community-meeting.markdown
_events/2024-0326-community-meeting.markdown
_events/2024-0409-community-meeting.markdown
_events/2024-0423-community-meeting.markdown

Adding Community Events for March and April to the calendar
n/a

March & April community events

---

_community_members/aredko.md
_community_members/astern.md
_community_members/chenkle.md
_community_members/efisher.md
_community_members/gingersoll.md
_community_members/jkowall.md
_community_members/kfreedain.md
_community_members/mshah.md
_community_members/nknize.md
_community_members/sherman.md
_includes/author_panel.html
_layouts/calendar.html
_layouts/community_member.html
_opensearchcon_sessions/2022-north-america-keynote.md
_opensearchcon_sessions/2022-north-america-opensearch-project-roadmap-2022-and-beyond.md
_opensearchcon_sessions/2022-north-america-speed-up-your-search-concurrency-and-merge-policies-to-the-rescue.md
_opensearchcon_sessions/2023-north-america-18-months-of-operating-opensearch-at-scale.md
_opensearchcon_sessions/2023-north-america-generative-ai-and-search-whats-your-plan.md
_opensearchcon_sessions/2023-north-america-journey-to-a-750-node-cluster-why-mastering-allocation-and-routing-in-opensearch-is-the-key-to-successfully-achieving-massive-scale.md
_opensearchcon_sessions/2023-north-america-keynote.md
releases.md

Patches mismatched community member short_names migrated from conference speakers; adds missing twitter link in community member page
Patches leap year logic in calendar template
Fixes markdown formatting issue in releases page

Patches mismatched community member short_names

---

releases.md

This note was originally added in 2023 but I believe it is still applicable for 2024 as well.

Update year in note about major version release

---

_events/2024-0306-foss-backstage.markdown

Adding an event showcasing our attendance at FOSS Backstage, and Aparna's talk at FOSS Backstage Design
n/a

FOSS Backstage event

---

_redesign_heros/4.md

Replaces our fourth-in-line herobanner with a call to action for the Linux Foundation 2024 Search and Analytics Survey.
None

Linux Foundation 2024 Search and Analytics Survey CTA style herobanner.

---

_data/top_nav.yml
events/opensearchcon/index.md

Updated the opensearchcon landing page and top-nav with information and links for Europe 2024
n/a

OpenSearchCon landing page updates

---

_artifacts/opensearch-1.3/arm64/opensearch-1.3.15-docker-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.15-freebsd-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.15-linux-arm64-deb.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.15-linux-arm64-rpm.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.15-linux-arm64-yum.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.15-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.15-min-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.15-docker-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.15-linux-arm64-deb.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.15-linux-arm64-rpm.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.15-linux-arm64-yum.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.15-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.15-min-linux-arm64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.15-docker-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.15-freebsd-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.15-linux-x64-deb.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.15-linux-x64-rpm.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.15-linux-x64-yum.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.15-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.15-min-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.15-windows-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.15-docker-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.15-linux-x64-deb.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.15-linux-x64-rpm.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.15-linux-x64-yum.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.15-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.15-min-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.15-windows-x64.markdown
_artifacts/opensearch-1.3/x86/opensearch-1.3.15-freebsd-x86.markdown
_versions/2024-03-05-opensearch-1.3.15.markdown

Download pages for the 1.3.15 release - currently scheduled for March 5
n/a

Download pages for 1.3.15

---

_versions/2024-03-05-opensearch-1.3.15.markdown

Fix min release for download pages of 1.3.15
n/a

1.3.15 min release version fix

---

_events/2024-0312-dev-triage-ml-commons.markdown

ml-commons triage meeting 2024-03-12

---

_events/2024-0312-dev-triage-ml-commons.markdown

Publishes new ML Triage Meeting
N/A

Adds next ML triage meeting

---

releases.md

Update release manager and issue for 2.13.0
https://github.com/opensearch-project/opensearch-build/issues/4433

Update release manager and issue for 2.13.0

---

.github/vale/styles/Vocab/OpenSearch/Words/accept.txt

Adds "upvote" and "downvote" to Vale.

Add upvote and downvote to vale

---

.github/vale/styles/Vocab/OpenSearch/Words/accept.txt

Add syslog to Vale

---

_events/2024-0326-dev-triage-ml-commons.markdown

[triage events for ml-commons 2024-03-26]

triage events for ml-commons 2024-03-26

---

_posts/2024-03-15-customer-experience-outcomes.md

Looks Aparna's blog had the wrong excerpt in there. 

Adding a matching excerpt to aparnas blog. 

---

_events/2024-0326-2-13-release-meetings.markdown

Fix calender date to actual event date
opensearch-project/opensearch-build#4433

Fix calender date to actual event date

---

_includes/downloads/opensearch-docker.markdown

Addresses a bug found via this comment: 
https://github.com/opensearch-project/project-website/pull/2526#issuecomment-2019564741

Fixes demo config doc redirect link in docker download steps.

---

_posts/2024-04-02-UsingDocumentationForUsabilityStudies.md

Embedding video
The video was not properly embedded in the blog
#2704 

Fix to the video embed 

---

_events/2024-0409-dev-triage-ml-commons.markdown

ml-commons triage meeting on 2024-04-09

---

_partners/xoriant.md

Left in some example entries meant to be hidden.

A quick change to remove some extra info from a partner page.

---

_events/2024-0409-dev-triage-ml-commons.markdown

updating meetup event

---

_layouts/event.html

Layout was not showing minute of hour for event cards.

---

.github/vale/styles/OpenSearch/SpacingWords.yml

Corrects error in SpacingWords.yml.

Correct error in SpacingWords.yml

---

_events/2024-0326-2-13-release-meetings.markdown

Update retrospective date for 2.13.0
https://github.com/opensearch-project/opensearch-build/issues/4602

Update retrospective date for 2.13.0

---

MAINTAINERS.md
_community_members/dtippett.md

Updating affiliations for David and Nick
Updating Davids about to reflect current reality
N/A

Updating affiliations and dtip's profile page

---

_posts/2024-04-05-Configurable-Automation-for-OpenSearch-ML-Use-Cases.md

Fixed for https://github.com/opensearch-project/project-website/pull/2698

Added missing authors for Flow Framework's Blogpost

---

events/opensearchcon/2024/europe/index.md

Quick table change for the simplified schedule. 

Osc europe 2024 simplified schedule

---

_posts/2023-07-27-alert-anomaly-visual.md

update author name

---

_community_members/llusim.md
_opensearchcon_sessions/2024-europe-how-to-get-your-pull-request-merged.md
_opensearchcon_sessions/2024-europe-migrating-from-self-managed-elasticsearch-to-opensearch.md
_opensearchcon_sessions/2024-europe-natural-language-search-lexical-and-semantic.md

Three more sessions - 
How t0 get your pull request merged
Migrating from self-managed elasticsearch to opensearch
Natural language search, lexical and semantic

Three more sessions and a new conference presenter.

---

_posts/2024-04-17-opensearchcon-europe-speakers-sessions.md

OpenSearchCon Europe session & speaker live blog
n/a

OSC EU Session blog

---

_posts/2024-04-17-opensearchcon-europe-speakers-sessions.md

Blog preview on main page past card boundaries from image. 

Adding an 'excerpt' field.

---

_posts/2024-04-18-discussing-open-source-innovation-at-open-source-summit-north-america.md

Blog recap of Anandhi's keynote at Open Source Summit NA
n/a

Anandhi keynote blog

---

_posts/2024-04-17-opensearchcon-europe-speakers-sessions.md
_posts/2024-04-18-discussing-open-source-innovation-at-open-source-summit-north-america.md

Anandhi keynote blog
https://github.com/opensearch-project/project-website/pull/2775

Push out blog post

---

_community_members/dtippett.md

Updates my bio with more up to date informaiton
N/A

Updating David's Bio

---

_events/2024-0423-dev-triage-ml-commons.markdown

[Development Backlog & Triage Meeting - ml-commons - 2024-04-23]

Development Backlog & Triage Meeting - ml-commons - 2024-04-23

---

_opensearchcon_exhibitors/2024-europe-adelean.md
_opensearchcon_exhibitors/2024-europe-aiven.md
_opensearchcon_exhibitors/2024-europe-bigdataboutique.md
_opensearchcon_exhibitors/2024-europe-bitergia.md
_opensearchcon_exhibitors/2024-europe-elastiflow.md
_opensearchcon_exhibitors/2024-europe-eliatra.md
_opensearchcon_exhibitors/2024-europe-hyland.md
_opensearchcon_exhibitors/2024-europe-infinio.md
_opensearchcon_exhibitors/2024-europe-opensourceconnections.md
_opensearchcon_exhibitors/2024-europe-quesma.md
_opensearchcon_exhibitors/2024-europe-seacom.md
_opensearchcon_exhibitors/2024-europe-zeta-alpha.md

Publishes logos for all Exhibitors for OpenSearchCon Europe 2024. 

Exhibitors for OpenSearchCon Europe 2024

---

_opensearchcon_exhibitors/2023-north-america-bigdata-boutique.md
_opensearchcon_exhibitors/2024-europe-bigdataboutique.md

Removes BigData Boutique from exhibitors. 

Remove BigData from exhibitors. 

---

_opensearchcon_sessions/2024-europe-multi-tenancy-for-all-workloads.md

Updates session "Multi-tenancy for all workloads" to have the right URL. 
#2791 

URL missing a period.

---

_posts/2024-02-23-enhanced-multi-vector-support-in-opensearch-knn.md

Add an attribution to Lucene for multi-vector support blog
N/A

Add an attribution to Lucene for multi-vector support blog

---

_opensearchcon_exhibitors/2024-europe-bigdata-boutique.md

Re-adds bigdata boutique to the list of exhibitors for OpenSearchCon Europe 2024. 

Bigdata Boutique is back.

---

_community_members/liusim.md

Updates permalink for Liat Iusim's profile. 

Permalink doesn't seem to be getting updated as intended.

---

_community_members/bgamble.md

Ben Gamble is not a keynote speaker. Sorry about that. 

fast follow

---

_opensearchcon_sessions/2024-europe-implementing-an-open-source-rag-with-opensearch.md
_opensearchcon_sessions/2024-europe-migrating-from-self-managed-elasticsearch-to-opensearch.md
_opensearchcon_sessions/2024-europe-you-cant-test-everything-but-you-should-monitor-it.md

Time/schedule updates for a few OpenSearchCon EU sessions
n/a

OSC EU session updates

---

_community_members/luchoa.md

Update contributor description

---

_events/2024-0507-dev-triage-ml-commons.markdown

ml-commons triage event 05-07-2024

---

events/opensearchcon/2024/europe/sessions/index.md

Adds javascript widget embed from pretalx to display a much better schedule.

Embedding schedule from pretalx.

---

_opensearchcon_exhibitors/2024-europe-bigdata-boutique.md

One exhibitor no longer wants their table. 

Removal of one exhibitor for OSCONEU.

---

events/opensearchcon/2024/north-america/cfp.md

* Adding "Operating OpenSearch" to the list of CFP tracks. 
* Adding "Operating OpenSearch" to the airtable form choices for track. 

Adding track selection.

---

events/opensearchcon/2024/europe/index.md

OSC training gone from schedule. 

OSC training out.

---

_includes/redesign_buttons.html

Update to slack invitation link
n/a

Slack invite update

---

_includes/redesign_buttons.html
events/opensearchcon/2024/europe/index.md

Slack invite update
https://github.com/opensearch-project/project-website/pull/2847

Push out Slack invite update

---

verify-signatures.markdown

Update 2024 OpenSearch Project Public PGP Key Renewal Changelog
https://github.com/opensearch-project/opensearch-build/issues/3468

Update 2024 OpenSearch Project Public PGP Key Renewal Changelog

---

_includes/redesign_buttons.html
verify-signatures.markdown

Merge Update 2024 OpenSearch Project Public PGP Key Renewal Changelog to prod branch
https://github.com/opensearch-project/opensearch-build/issues/3468

Merge Update 2024 OpenSearch Project Public PGP Key Renewal Changelog to prod branch

---

_events/2024-0514-2-14-release-meetings.markdown

Add 2.14.0 release events

---

_events/2024-0527-training-intro-to-opensearch.markdown
_events/2024-0529-training-opensearch-operations.markdown
_events/2024-0603-training-opensearch-for-product-searches.markdown

3 OpenSearch classes run by Sematext

Sematext OpenSearch classes 2024-05

---

_opensearchcon_sessions/2024-europe-a-thrilling-journey-into-data-driven-security-automation.md
_opensearchcon_sessions/2024-europe-delivering-the-next-wave-of-innovation-with-opensearch.md
_opensearchcon_sessions/2024-europe-enhance-query-execution-visibility-in-OS-with-opentelemtry.md
_opensearchcon_sessions/2024-europe-enhancing-ai-and-llm-systems-with-hybrid-search.md
_opensearchcon_sessions/2024-europe-gaining-observability-into-your-ci-cd-pipeline.md
_opensearchcon_sessions/2024-europe-how-sap-analyzes-opentelemetry-signals-using-data-prepper.md
_opensearchcon_sessions/2024-europe-how-to-become-an-opensearch-project-repo-maintainer.md
_opensearchcon_sessions/2024-europe-how-to-get-your-pull-request-merged.md
_opensearchcon_sessions/2024-europe-implementing-an-open-source-rag-with-opensearch.md
_opensearchcon_sessions/2024-europe-migrating-from-self-managed-elasticsearch-to-opensearch.md
_opensearchcon_sessions/2024-europe-multi-tenancy-for-all-workloads.md
_opensearchcon_sessions/2024-europe-natural-language-search-lexical-and-semantic.md
_opensearchcon_sessions/2024-europe-opensearch-in-kubernetes-helm-charts-and-operator.md
_opensearchcon_sessions/2024-europe-persistent-and-performant-ingestion-using-data-prepper.md
_opensearchcon_sessions/2024-europe-ragelo-an-elo-rating-based-evaluation-toolkit-for-rag.md
_opensearchcon_sessions/2024-europe-revolutionizing-search-unveiling-conversational-search-in-opensearch.md
_opensearchcon_sessions/2024-europe-search-solutions-with-opensearch-python-and-serverless.md
_opensearchcon_sessions/2024-europe-securing-opensearch.md
_opensearchcon_sessions/2024-europe-tune-e-commerce-search-for-success-with-chorus-and-opensearch.md
_opensearchcon_sessions/2024-europe-unleash-your-clusters-potential-with-opensearch-benchmark.md
_opensearchcon_sessions/2024-europe-unspoken-overhead-of-the-inverted-index.md
_opensearchcon_sessions/2024-europe-user-behavior-insights.md
_opensearchcon_sessions/2024-europe-you-cant-test-everything-but-you-should-monitor-it.md
events/opensearchcon/2024/europe/index.md
events/opensearchcon/2024/europe/unconference/index.md
events/opensearchcon/2024/india/cfp.md

Updated new CFP closing date for OpenSearchCon India
Updated OpenSearchCon Europe - registration is closed - added video to each session page - added videos to unconference page
n/a

OSC Page updates

---

.github/CODEOWNERS
MAINTAINERS.md

Per the email thread, add Nathan Bower as a repo maintainer

Add Nathan Bower as a repo maintainer

---

_events/2024-0521-dev-triage-ml-commons.markdown

[ml-commons triage event for 05-21-2024]

ml-commons triage event for 05-21-2024

---

_community_members/qchea.md

short PR on correcting github profile for qichen

MAINT: correct github profile for qichen

---

_posts/2024-05-16-Announcing-Data-Prepper-2.8.0.md

Our colleague George contributed to this blog, but his profile is not included. This corrects that error. 
N/A

Corrects authors for Data Prepper 2.8.0 blog

---

_posts/2024-04-30-A-comprehensive-guide-to-setup-and-connect-self-managed-dashboards-with-Amazon-OpenSearch-domain.md

Tried changing the code snippet format to properly render in the website.
Fix the code snippet in the blog website

Code snippets are not properly rendered in the website

---

_posts/2024-05-16-Announcing-Data-Prepper-2.8.0.md

Wrapped the text of hte blog post in rawtext tags so that Liquid doesnt try to interpret them as variables.
Fixed issue 2889. 
#2889 

Addressed issue# 2889

---

events/opensearchcon/2024/north-america/cfp.md

changes date listed on OSCONNA2024 CFP page. 
#2888

Extending CFP close date to June 14

---

_events/2024-0514-2-14-release-meetings.markdown
releases.md

Add 2.14 release details and schedule retrospective. 

Add 2.14 release details and schedule retrospective

---

_events/2024-05-29-data-prepper-fluent-bit-webinar.markdown

Adding a webinar co-hosted by Kevin Falls and Anurag Gupta to the event calendar.
N/A
- [ X] Commits are signed per the DCO using --signoff

Data Prepper & Fluent Bit Webinar

---

_events/2024-0604-community-over-code-eu-documentation-design-templates.markdown
_events/2024-0609-berlin-buzzwords-2024.markdown
_events/2024-0610-berlin-buzzwords-2024-rediscover-your-keyword-search.markdown

Adds events for Aparna's Community Over Code talk, Praveen & Hajer's talk at Bbuzz, and listing for our booth at Berlin Buzzwords.
N/A

Conference events

---

_events/2024-0604-dev-triage-ml-commons.markdown

triage meeting for 2024-06-04 10:30:00 -0700

---

_posts/2024-05-30-Improving-Dashboards-usability-with-Vega.md

Changes mechanism of `.mov` embedding. 

Embed update.

---

_events/2024-0604-data-prepper-fluent-bit-webinar.markdown
_events/2024-0609-berlin-buzzwords-2024.markdown
_events/2024-0610-berlin-buzzwords-2024-rediscover-your-keyword-search.markdown
_events/2024-0611-berlin-buzzwords-2024-elevatingAI-flow-framework-RAG-tool.markdown
events/opensearchcon/2024/north-america/cfp.md

Edits to Berlin Buzzwords session link, added new BBuzz session, edit Fluent Bit event with updated date, and edit to OSC NA CfP page (we have four tracks not three) 
n/a

Event edits

---

_posts/2024-06-01-opensearchcon-north-america-2024-registration-and-cfp.md

Publishes a blog announcing the CFP and registration for OpenSearchCon North America 2024. 
Resolves #2896 

Announcing OpenSearchCon North America 2024 Blog

---

_posts/2024-06-01-opensearchcon-north-america-2024-registration-and-cfp.md

OpenSEarch Con NA 2024 Blog Date Change

Date change so it appears today.

---

_events/2024-0604-community-meeting.markdown
_events/2024-0618-community-meeting.markdown
_events/2024-0702-community-meeting.markdown
_events/2024-0716-community-meeting.markdown
_events/2024-0730-community-meeting.markdown

Community meetings for June and July.

Next five community meeting events.

---

_events/2024-0610-berlin-buzzwords-2024-rediscover-your-keyword-search.markdown

Small edit to Berlin Buzzwords event
n/a

small event edit

---

_events/2024-0613-user-group-munich.markdown
events/opensearchcon/2024/india/index.md

Edit to close CfP on the OSC India page
Added event page for first Munich User Group date
n/a
- [a] Commits are signed per the DCO using --signoff

OSC India edit & Munich UG event

---

_community_members/lioperry.md

update community member's (lioperry) profile

Update lioperry members profile

---

events/opensearchcon/2024/north-america/index.md

Extends close date for OSCONNA CFP.

Close date.

---

_artifacts/opensearch-1.3/arm64/opensearch-1.3.17-docker-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.17-freebsd-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.17-linux-arm64-deb.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.17-linux-arm64-rpm.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.17-linux-arm64-yum.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.17-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.17-min-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.17-docker-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.17-linux-arm64-deb.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.17-linux-arm64-rpm.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.17-linux-arm64-yum.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.17-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.17-min-linux-arm64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.17-docker-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.17-freebsd-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.17-linux-x64-deb.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.17-linux-x64-rpm.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.17-linux-x64-yum.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.17-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.17-min-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.17-windows-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.17-docker-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.17-linux-x64-deb.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.17-linux-x64-rpm.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.17-linux-x64-yum.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.17-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.17-min-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.17-windows-x64.markdown
_artifacts/opensearch-1.3/x86/opensearch-1.3.17-freebsd-x86.markdown
_versions/2024-06-06-opensearch-1.3.17.markdown

Release version and artifact payload for 1.3.17.
NOTE: IF necessary (I won't be around for the meeting) change the `date:` frontmatter in the `_version/` artifact to reflect actual release date. 

[Only merge when ready] OpenSeearch 1.3.17 release artifact payload

---

_versions/2024-06-06-opensearch-1.3.17.markdown

Fix 1.3.17 using 1.3.16 link for artifacts
https://github.com/opensearch-project/opensearch-build/issues/4659

Fix 1.3.17 using 1.3.16 link for artifacts

---

_community_members/hoangia.md
_community_members/ssingh.md
_posts/2024-06-07-opensearch-performance-2.14.md

Apply last editorial changes to the performance blog

Last editorial changes for performance blog

---

_events/2024-0618-dev-triage-ml-commons.markdown

triage meeting of ml-commons for 2024-06-18

---

events/opensearchcon/2024/india/cfp.md
events/opensearchcon/2024/india/index.md

Remove registration link from main OSC India page
Remove CFP link from OSC India CFP page
Add link to OSC EU 2024 playlist to OSC India CFP page
n/a

Update to OpenSearchCon India 2023 pages

---

_events/2024-0625-2-15-release-meetings.markdown

Update go/nogo meeting dates for 2.15.0
opensearch-project/opensearch-build#4681

Update go/nogo meeting dates for 2.15.0

---

_events/2024-0625-2-15-release-meetings.markdown

Update go/nogo meeting dates for 2.15.0 (Part 2)
opensearch-project/opensearch-build#4681

Update go/nogo meeting dates for 2.15.0 (Part 2)

---

_events/2024-0625-2-15-release-meetings.markdown
events/opensearchcon/2024/europe/index.md
events/opensearchcon/2024/india/index.md
events/opensearchcon/2024/india/sessions/index.md

Relese Redirect_from removed from 2024 Europe. Session lineup added to 2024... to prod env

Relese Redirect_from removed from 2024 Europe. Session lineup added to 2024... to prod env

---

_posts/2024-05-23-OpenSearchCon-europe-2024-shines-in-berlin.md
_posts/2024-05-30-Improving-Dashboards-usability-with-Vega.md
_posts/2024-06-01-opensearchcon-north-america-2024-registration-and-cfp.md
_posts/2024-06-03-so-you-want-better-opensearch-documentation.markdown
_posts/2024-06-05-do-you-need-semantic-search.markdown
_posts/2024-06-06-opensearch-partnering-with-datastax-on-generative-ai.md
_posts/2024-06-07-opensearch-performance-2.14.md
_posts/2024-06-11-A-deep-dive-into-faster-semantic-sparse-retrieval-in-OS-2.12.md
blog/index.html

Changes 
- Blog-categories are now concatenated with "," between multiple elements. 
- The date and blog-category are now on the same line.
- Small changes to the size of the featured post, it is now larger than the normal posts.
- Removed hover affect.

Blog-feed updates - addresses small issues to the rendering of the blog cards

---

_includes/head-twitter-metatags.html

Twittercard image to be absolute URL not relative. 

Absolute url for twittercard images.

---

_data/post_categories.yml

To make it consistent with the other images in our blog.

Changed the generic images from an absolute URL to the relative URL 

---

_posts/2024-06-21-opensearchcon-san-francisco-schedule-and-cfp-updates.md

OpenSearchCon San Francisco - Schedule and CFP Updates

One new blog coming up!

---

_community_members/junqiu.md

Update profile in junqiu.md
N/A

Update profile in junqiu.md

---

benchmarks/index.md

Link latest performance blog on performance benchmarks page. 

Link latest performance blog on performance benchmarks page

---

_posts/2024-06-25-diving-into-opensearch-2.15.md

Release blog for today's 2.15.0 written by @jhmcintyre edited by @natebower 
N/A

2.15.0 Release Blog

---

_redesign_heros/1.md

Updates the 2.14 hero banner to say 2.15

2.15 Hero Banner

---

_posts/2024-06-21-opensearchcon-san-francisco-schedule-and-cfp-updates.md
_posts/2024-06-25-diving-into-opensearch-2.15.md

Typo in the 2.15 blog post, excerpt fix on the OSC NA cfp & schedule post.
n/a

Minor blog edits

---

_posts/2024-06-21-opensearchcon-san-francisco-schedule-and-cfp-updates.md
_posts/2024-06-25-diving-into-opensearch-2.15.md
_redesign_heros/1.md

Minor blog edits
https://github.com/opensearch-project/project-website/pull/3012

Push out minor blog edits

---

_events/2024-0625-2-15-release-meetings.markdown

Update 2.15.0 retro chime link and time information
https://github.com/opensearch-project/opensearch-build/issues/4681

Update 2.15.0 retro chime link and time information

---

_events/2024-0702-dev-triage-ml-commons.markdown

[ml-commons triage meeting for 2nd July 2024]

ml-commons triage meeting for 2nd July 2024

---

_posts/2024-06-26-performance-improvment-hybrid-query-215.md

For this blog post https://opensearch.org/blog/performance-improvment-hybrid-query-215/ we need to add Varun as a blog co-author as he contributed to the feature implementation.
n/a

Adding Varun as blog author

---

_posts/2024-07-01-opensearch-berlin-buzzwords-2024.md

just adds an `s` to a front matter declaration. 

meta_keywords plural.

---

_community_members/varunudr.md

Add details on @vibrantvarun  social and update intro in the profile.

Update Commnunity member Varun details

---

_events/2024-0702-dev-triage-ml-commons.markdown

[ml-commons triage meeting 2024-07-16]

ml-commons triage meeting 2024-07-16

---

_events/2024-07016-dev-triage-ml-commons.markdown

ml-commons triage meeting update

---

_redesign_use_cases/search-vector-database.markdown

Add links to vector database page

Add links to vector database page

---

_partners/aryn.md

aryn.ai partner listing
#3070 

Adding Aryn partner information.

---

_community_members/rgumiero.md

Correction of the name that was different on the page.
Correction of the name that was different on the page.

Name correction

---

.github/ISSUE_TEMPLATE/partner_add_new_partner.yml
_includes/redesign_buttons.html

Updated Slack invite link
https://github.com/opensearch-project/project-website/pull/3094

push out Slack invitation link update

---

_community_members/rishabhmaurya.md
_posts/2024-07-11-Optimize-storage-and-performance-using-MatchOnlyText-field.md

Pulls in blog titled as above. 
#3056 

Merge new blog "optimize storage and performance using matchonlytextfield

---

_layouts/opensearchcon_landing.html
_opensearchcon_sessions/2024-north-america-opensource-connections-training.md
events/opensearchcon/2024/north-america/index.md
events/opensearchcon/2024/north-america/osc-training.md
events/opensearchcon/2024/north-america/sessions/index.md

Adds description, button stack button, and links to the OpenSource Connections "Think Like a Relevance Engineer" training for OSCONNA2024

OpenSource Connections Training added to OSCONNA2024 homepage.

---

_events/2024-0730-dev-triage-ml-commons.markdown

[ml-commons triage meeting 07-30]

ml-commons triage meeting 07-30

---

_events/2024-0806-2-16-release-meetings.markdown

[Release 2.16.0] Update the go/no-go voting call information

[Release 2.16.0] Update the go/no-go voting call information

---

releases.md

Updated release date for 2.16 to Aug 7th per release meeting on Aug 6th.

Updated release date for 2.16 to Aug 7th

---

_events/2024-0806-2-16-release-meetings.markdown
releases.md

Push the updated 2.16 release date to prod

Push the updated 2.16 release date to prod

---

_events/2024-0806-2-16-release-meetings.markdown
releases.md

Update release meeting info. 

---

_events/2024-0806-2-16-release-meetings.markdown

Update 4th go/no-go meeting time

[Release 2.16.0]  Update 4th go/no-go meeting time

---

_events/2024-0806-2-16-release-meetings.markdown

[prod] Update 4th go/no-go meeting time.

---

_events/2024-0806-2-16-release-meetings.markdown

[Release 2.16.0] Update Calendar Date.

[Release 2.16.0] Update Calendar Date

---

_events/2024-0806-2-16-release-meetings.markdown

Release meeting calendar date change. 

---

_events/2024-0806-2-16-release-meetings.markdown

[Release 2.16.0] 2.16.0 release event update

[Release 2.16.0] 2.16.0 release event update

---

_events/2024-0806-2-16-release-meetings.markdown

Updates details of the 2.16 release meeting. 

[prod] 2.16 release meeting

---

_posts/2024-08-07-introducing-opensearch-2-16.md

[blog] - Introducing OpenSearch 2.16 Initial draft. Expecting an update.

---

_posts/2024-08-07-introducing-opensearch-2-16.md

Introducing opensearch 2.16 typo

---

_events/2024-0806-2-16-release-meetings.markdown
_posts/2024-08-07-introducing-opensearch-2-16.md

Adds another paragraph to the introducing OpenSearch 2.16 article. 

Article addendum. 

---

_community_members/kolchfa.md

Update kolchfa profile

---

.github/vale/styles/Vocab/OpenSearch/Products/accept.txt

Update Vale vocabulary terms

---

assets/js/search.js

Add redirection to the search results landing page regarding of this PR. https://github.com/opensearch-project/documentation-website/pull/7942

Add redirection for search landing page

---

events/opensearchcon/2024/north-america/capture-the-flag.md

Removes section from CTF page. 

CTF event had messaging from OpenSource Connections training.

---

_events/2024-0903-community-meeting.markdown
_events/2024-1001-community-meeting.markdown
_events/2024-1105-community-meeting.markdown
_events/2024-1203-community-meeting.markdown

Community Meetings for Sept-Dec 2024
n/a

Community Events rest of 2024

---

_community_members/dchanp.md
_opensearchcon_sessions/2024-north-america-demystifying-security-for-opensearch.md

Updates profile, and fixes issue displaying author name correctly

Fixes author name and updates profile - Darshit Chanpura

---

_opensearchcon_exhibitors/2024/north-america/2024-north-america-elastiflow.md

Add Elastiflow to OpenSearchCon North America exhibitors.

---

events/opensearchcon/2024/north-america/capture-the-flag.md

Adds graylog logo to the capture the flag page. 
#3194 

Adding Graylog logo to the capture the flag page.

---

_opensearchcon_sessions/2024/north-america/2024-north-america-optimizing-storage-performance-and-efficient-index-configuration-with-compression-codecs-in-opensearch.md

Session timing change. 
#3190 

Changes the timing of a session.

---

_opensearchcon_sessions/2024/north-america/2024-north-america-opensearch-conversations-with-context.md

Session timing incorrect for https://opensearch.org/events/opensearchcon/sessions/opensearch-conversations-with-context.html

Timing adjustment.

---

_community_members/bhoffman.md

Speaker's session was removed but they remained on the list of all speakers. A quick fix. 

Removing one speaker from listing.

---

_artifacts/opensearch-1.3/arm64/opensearch-1.3.19-docker-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.19-freebsd-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.19-linux-arm64-deb.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.19-linux-arm64-rpm.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.19-linux-arm64-yum.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.19-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-1.3.19-min-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.19-docker-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.19-linux-arm64-deb.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.19-linux-arm64-rpm.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.19-linux-arm64-yum.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.19-linux-arm64.markdown
_artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.19-min-linux-arm64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.19-docker-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.19-freebsd-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.19-linux-x64-deb.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.19-linux-x64-rpm.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.19-linux-x64-yum.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.19-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.19-min-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-1.3.19-windows-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.19-docker-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.19-linux-x64-deb.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.19-linux-x64-rpm.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.19-linux-x64-yum.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.19-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.19-min-linux-x64.markdown
_artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.19-windows-x64.markdown
_artifacts/opensearch-1.3/x86/opensearch-1.3.19-freebsd-x86.markdown
_versions/2024-08-27-opensearch-1.3.19.markdown

Preemptive PR for 1.3.19 with release date set to tomorrow 8-27.

[release] 1.3.19 artifact volley

---

_community_members/shikhar.md
_opensearchcon_sessions/2024/north-america/2024-north-america-enabling-search-on-databases-with-data-prepper.md
_opensearchcon_sessions/2024/north-america/2024-north-america-how-attribute-based-access-control(abac)-can-solve-different-customer-usecases-and-be-the-future-of-fgac.md

One typoed short-name and one missing co-presenter. 

Session corrections.

---

_posts/2024-08-22-boost-vector-search-with-css.md

Putting the first paragraph of content up in the very first line.
Fixes the blank excerpt for latest blog. 

Fixing excerpt.

---

releases.md

Update releases page from Feb to Aug 2024

Update releases page from Feb to Aug 2024

---

_community_members/_osci_2023/MuhammadSamiullah.markdown
_community_members/_osci_2023/hchang.markdown
_community_members/_osci_2023/tanerjones4075.markdown
_community_members/_osci_2023/vnandi.markdown
_community_members/abandeji.md
_community_members/awssamit.md
_community_members/bnauheimer.md
_community_members/dhruvdas.md
_community_members/ev2900.md
_community_members/gbh.md
_community_members/hdhalter.md
_community_members/jkressin.md
_community_members/khamric.md
_community_members/movvaam.md
_community_members/nschwartz.md
_community_members/parce.md
_community_members/ybarabash.md

Pages like https://opensearch.org/community/members/ybarabash.html don't render links correctly.
Really this site needs a link checker, a schema validator and a linter for this data.

Fix: links to LinkedIn and Twitter profiles.

---

_posts/2024-08-28-Data-Prepper-2.9.0-is-ready-for-download.md
_posts/2024-08-29-Data-Prepper-2.9.0-is-ready-for-download.md

The release blog for Data Prepper 2.9.0. 
We will provide an update with our usual "Thank You" text shortly. But, I wanted to make this available for feedback sooner in order to help us get the post out as soon after our release as possible.
Resolves #3203

Release blog post for Data Prepper 2.9.0. 

---

_opensearchcon_sessions/2024/north-america/2024-north-america-search-results-with-amazon-personalize-and-opensearch-making-searches-smarter.md

Session timing edit as requested by presenters Yuliia Barabash & Laysa Uchoa
n/a

OSCNA Session time edit

---

_community_members/ljeanniot.md

Job title change for Lucas. 
#3248 

Community member title change.

---

_opensearchcon_exhibitors/2024/north-america/2024-north-america-coralogix.md

Coralogix to be added to the exhibitor listing for OpenSEarchCon NA. 
#3245  

Adds coralogix to exhibitors for OpenSearchCon North America 2024

---

events/opensearchcon/2024/north-america/index.md

Schedule for oscon north america 2024
#3206

Overall schedule for OpenSEarchCon 2024 North America

---

releases.md

Update release history from 2021 to 2023

Update release history from 2021 to 2023

---

events/opensearchcon/2024/north-america/index.md
events/opensearchcon/2024/north-america/schedule.md

Adds the schedule to its own page instead of the landing page, adds button to conference button stack. 
#3258 

Standalone page for schedule.

---

releases.md

Update RC date for 2.17.0
See https://github.com/opensearch-project/opensearch-build/issues/4908#issuecomment-2329863750

Update RC date for 2.17.0

---

_redesign_heros/02.md
_redesign_heros/2.md
_redesign_heros/3.md

Every sentence in the banner should be sentence case. This includes text on buttons

Change banner sentences to sentence case

---

_community_members/mvanjiappan.md
_community_members/rmanickam.md
_community_members/rnair.md
_opensearchcon_sessions/2024/north-america/2024-north-america-multitenancy-for-all-workloads.md
_opensearchcon_sessions/2024/north-america/2024-north-america-scaling-operational-intelligence-into-business-intelligence-using-opensearch-genai-for-global-rollouts.md

Makes various and sundry edits to presentations.
#3264 

Session updates for #3264

---

_opensearchcon_sessions/2024/north-america/2024-north-america-how-attribute-based-access-control(abac)-can-solve-different-customer-usecases-and-be-the-future-of-fgac.md

Updates abstract for Prabhat Chaturvedi

Update abstract for Prabhat Chaturvedi

---

release-dashboard/index.md

Central release dashboard Iframe height adjustments
Part of https://github.com/opensearch-project/opensearch-metrics/issues/69 and https://github.com/opensearch-project/opensearch-metrics/issues/51

Central release dashboard Iframe height adjustments

---

_events/2024-0913-2-17-release-meetings.markdown

Update release calls schedule for 2.17
https://github.com/opensearch-project/opensearch-build/issues/4908

Update release calls schedule for 2.17

---

_community_members/mvanjiappan.md
_community_members/rmanickam.md

Mixed up two profile content entries. 

Swapping two profile descriptions,.

---

_data/homepage_datafile.json
_layouts/homepage.html
_sass/_opensearch.scss

Special announcement for OSS Europe. 

Last minute edits to the homepage.

---

trademark-brand-policy.markdown

Wording change.

---

_events/2024-0913-2-17-release-meetings.markdown

Update event date to reflect 2.17.0 release call

Update event date to reflect 2.17.0 release call

---

_events/2024-0913-2-17-release-meetings.markdown

Add 2.17 restrospective meeting
https://github.com/opensearch-project/opensearch-build/issues/4909

Add 2.17 restrospective meeting

---

_events/2024-0924-dev-triage-ml-commons.markdown

[ml-commons triage event 2024-0924]

ml-commons triage event 2024-0924

---

_community_members/rmanickam.md

Title change, Ramesh Kumar Manickam

---

_community_members/efisher.md

Updates to Eli's community member profile
n/a

Eli Fisher profile update

---

release-dashboard/index.md

Onboard 2.18.0 to the release dashboard
https://github.com/opensearch-project/opensearch-build/issues/5004

Onboard 2.18.0 to the release dashboard

---

_community_members/tgrainger.md

Fixes Searchkernel company name spelling, removes extra space, adds _AI-Powered Book_ as most relevant context
N/A

Update Trey Grainger's job title

---

events/opensearchcon/2024/north-america/unconference/index.md

Room for unconference.

---

_data/header_navmenu_datafile.json
_includes/navbar.html
_sass/_navbar.scss

restyled the downloads button to stand out more. 
#3333 

Navbar style small changes

---

events/opensearchcon/2024/north-america/schedule.md

Unconference in overview schedule. 

Overview schedule update for Unconference room.

---

releases.md

Update 2.17.x releases
https://github.com/opensearch-project/opensearch-build/issues/4908
https://github.com/opensearch-project/opensearch-build/issues/5046

Update 2.17.x releases

---

_opensearchcon_sessions/2024/north-america/2024-north-america-building-ai-models-with-opensearch's-user-behavior-insights.md

Trey Grainger from 10:45-11:25am to 1:00-1:40pm

Updating time for Trey Grainger.

---

_posts/2024-10-01-using-search-latency-monitoring.markdown

Remove blog formatting error

---

.github/vale/styles/Vocab/OpenSearch/Words/accept.txt

Adds performant to vale

---

_includes/redesign_buttons.html
slack.markdown

Slack link expired. Replacing with new shared link. 

Slack shared invite link and some random breadcrumbs.

---

_posts/2024-09-30-Boosting-OpenSearch-Development-on-MacOS-with-Apple-Silicon.md
_posts/2024-10-21-Boosting-OpenSearch-Development-on-MacOS-with-Apple-Silicon.md

Adding MacOS Arm64 Core Snapshot Artifact Blog Post
https://github.com/opensearch-project/project-website/issues/3131

[Blog] Adding MacOS Arm64 Core Snapshot Artifact Blog Post

---

_community_members/sb2k16.md

This PR is to fix the profile for @sb2k16.

fix the profile image path

---

_events/2024-1022-dev-triage-ml-commons.markdown
_events/2024-1105-dev-triage-ml-commons.markdown
_events/2024-1119-dev-triage-ml-commons.markdown
_events/2024-1203-dev-triage-ml-commons.markdown
_events/2024-1217-dev-triage-ml-commons.markdown
_events/2024-1231-dev-triage-ml-commons.markdown

[creating triage events for ml-commons for the rest of this year]

creating triage events for ml-commons for the rest of this year

---

releases.md

Update 2.17.1 and 2.18.0 release information

Update 2.17.1 and 2.18.0 release information

---

_events/2024-1101-2-18-release-meetings.markdown

Add 2.18 release call details. 
https://github.com/opensearch-project/opensearch-build/issues/5004

Add 2.18 release call details

---

.github/vale/styles/Vocab/OpenSearch/Words/accept.txt

Adds "precompute" and "preaggregate" to Vale.

Adds precompute and preaggregate to Vale

---

_events/2024-1101-2-18-release-meetings.markdown

Update 2.18 release event with release day schedule and retrospective. 
https://github.com/opensearch-project/opensearch-build/issues/5004. 

Update 2.18 release event

---

.github/vale/styles/Vocab/OpenSearch/Words/accept.txt
_events/2024-1101-2-18-release-meetings.markdown

[prod] 2.18 release event. 

---

_posts/2024-07-19-using-heuristic-evaluation-to-inform-the-user-experience-strategy-of-a-product.markdown

rsalas -> raysalas

---

_events/2024-1101-2-18-release-meetings.markdown

Update 2.18 Retro call schedule. 

Update 2.18 Retro call schedule

---

_posts/2024-11-05-get-started-with-opensearch-2-18.md

meta_description correction, date edit, additional link to Workspace information added. 
n/a

minor 2.18 blog edits

---

_events/2024-1101-2-18-release-meetings.markdown
_posts/2024-11-05-get-started-with-opensearch-2-18.md

minor 2.18 blog edits
https://github.com/opensearch-project/project-website/pull/3441

push out blog edits

---

_posts/2024-11-13-boosting-k-nn-exact-search.md
releases.md

Update 1.3.20 Release information to production

Update 1.3.20 Release information to production

---

_posts/2024-11-13-boosting-k-nn-exact-search.md

This PR updates a recent blog post for boosting exact search k-NN performance.  A footnote is added to specify the recommended settings for users to achieve the best performance and be able to replicate the benchmarking results
N/A

Add clarification footnote to exact search k-NN blog post

---

_posts/2024-11-14-OpenSearchCon-2024-NA-Blog.md

Changes image links into regular links. 

Image markdown switched to link markdown.

---

_community_members/smelik.md

Create Mikhail Smelik community member profile

---

_community_members/prthsh.md

Create Parth Shah community member profile

---

releases.md

Update 1.3.20 releases dates and engineers
#4990

Update 1.3.20 releases

---

_events/2025-0107-community-meeting.markdown
_events/2025-0204-community-meeting.markdown
_events/2025-0304-community-meeting.markdown
_events/2025-0401-community-meeting.markdown
_events/2025-0506-community-meeting.markdown
_events/2025-0603-community-meeting.markdown

Community Meeting event pages for January through June 2025
n/a

First 6 months of 2025 Community Meeting event pages

---

release-dashboard/index.md

Backport of https://github.com/opensearch-project/project-website/pull/3443
Part of https://github.com/opensearch-project/opensearch-build/issues/3747

[Backport Prod] Onboard release 3.0.0

---

_events/2025-0114-dev-triage-ml-commons.markdown
_events/2025-0128-dev-triage-ml-commons.markdown
_events/2025-0211-dev-triage-ml-commons.markdown
_events/2025-0225-dev-triage-ml-commons.markdown
_events/2025-0311-dev-triage-ml-commons.markdown
_events/2025-0325-dev-triage-ml-commons.markdown
_events/2025-0408-dev-triage-ml-commons.markdown
_events/2025-0422-dev-triage-ml-commons.markdown

[ml-commons events till april 2025]

ml-commons events till april 2025

---

_posts/2025-01-14-bigdataboutique-partner-highlight.markdown

Partner highlight for BigData Boutique
#3551 

Partner highlight blog for BigData Boutique

---

_solutionsProviders/tellaro.md

Added Twitter and Linkedin links
Missed this the first time around. Added the links from the github issue 
#3534 

Update Tellaro, add social links

---

_events/2025-0204-state-of-open-con-2025.markdown
_events/2025-0430-opensearchcon-europe-2025.markdown

Event pages for State of Open 2025 & OpenSearchCon Europe 2025
n/a

SOO & OSC event pages

---

_community_members/dwrigley.md

polish my (dwrigley) community member profile 
n/a

update LinkedIn link, include company information.

---

_sass/_community.scss

SCSS image path was wrong. Changed the name to be correct

---

_community_members/dwrigley.md
_sass/_community.scss

Capitalizes a B. I'm not quite sure of the root cause of this one but I did merge some things with main in rapid succession. The PR worked fine locally and displayed the banner as intended. 

[prod] SCSS image path correction

---

CODE_OF_CONDUCT.md

Update coc email as part of the LF transition
Closes https://github.com/opensearch-project/.github/issues/217

Update coc email as part of the LF transition

---

release-dashboard/index.md

Onboard 2.19.0 Release to the central release dashboard
Part of https://github.com/opensearch-project/opensearch-build/issues/5152

Onboard 2.19.0 Release to the central release dashboard

---

releases.md

Add 2.19 release details. 
https://github.com/opensearch-project/opensearch-build/issues/5152

Add 2.19 release details

---

_data/page_community_datafile.json

Added link to OpenSearchCon NA 2025
Changed 'write a blog post' link to go directly to opening that type of issue on repo
Fixed 'become a solutions provider' link - had a couple characters that sent it to the wrong issue
n/a

Community page update & fix

---

release-dashboard/index.md

Onboard 2.19.0 Release to the central release dashboard
Part of https://github.com/opensearch-project/opensearch-build/issues/5152

[Backport prod] Onboard 2.19.0 Release to the central release dashboard

---

_solutionsProviders/O11y.md

Fix related to https://github.com/opensearch-project/project-website/pull/3574#issuecomment-2619747692
https://github.com/opensearch-project/project-website/pull/3574#issuecomment-2619747692

Fix image case to lower

---

_posts/2025-01-30-deepseek-integration-rag.md

Update title of the DeepSeek integration blog

Update title of the DeepSeek integration blog

---

_posts/2025-01-28-OpenSearch-Now-Supports-DeepSeek-Chat-Models.md

Move note to example in DeepSeek blog

Move note to example in DeepSeek blog

---

_posts/2025-01-28-OpenSearch-Now-Supports-DeepSeek-Chat-Models.md

Push DeepSeek note update to prod

Push DeepSeek note update to prod

---

_posts/2025-01-30-one-click-deepseek-integration.md

Instant DeepSeek: One-Click Activation with OpenSearch

[BLOGPOST] Instant DeepSeek: One-Click Activation with OpenSearch

---

_posts/2025-01-28-OpenSearch-Now-Supports-DeepSeek-Chat-Models.md
_posts/2025-01-30-one-click-deepseek-integration.md

Push DeepSeek blog updates to prod

Push DeepSeek blog updates to prod

---

_posts/2024-12-26-Reducing-false-positives-through-algorithmic-improvements.md

Correct the publish date of blog post

Correct the publish date of blog post

---

_solutionsProviders/OameldaCloudServices.md

Fixed their name and a duplicate "hosting" in their description.
Signed-off-by: kaimmej <kaimmej@gmail.com>
Their name was misspelled - I fixed this. 
#3612 

[BUG] SolutionsProvider's name misspelled - Update OameldaCloudServices

---

releases.md

Resolve typos on the releases page
Closes https://github.com/opensearch-project/.github/issues/252

Resolve typos on the releases page

---

_events/2025-0207-2-19-release-meetings.markdown
releases.md

Push releases page update to production

Push releases page update to production

---

_data/page_community_datafile.json
community/index.html

Updated the community page
OpenSearchCon Link behavior now opens into a new tab. 
Playgrounds link was broken.
N/A

[BUG] Community page updates

---

_posts/2025-02-11-explore-OpenSearch-2-19.md

H3's back to H2's, bolded sections to H3's. 

Formatting change again.

---

_events/2025-0220-user-group-munich.markdown
_events/2025-0310-foss-backstage.markdown
_events/2025-0313-user-group-berlin.markdown
_events/2025-0401-kubecon-cloudnativecon-europe-2025.markdown
_events/2025-0401-observability-day-europe-2025.markdown
_events/2025-0403-user-group-london.markdown
_events/2025-0603-opensearchcon-india-2025.markdown
_events/2025-0615-berlin-buzzwords.markdown
_events/2025-0908-opensearchcon-north-america-2025.markdown

Edits:
OpenSearchCon Europe
Event pages for:
OpenSearchCon India, North America
User Groups
FOSS Backstage / Berlin Buzzwords
KubeCon & observability day
n/a

Event pages for OpenSearchCons, User Groups, and more

---

_includes/downloads/opensearch-docker-1.x.markdown
_includes/downloads/opensearch-docker.markdown

This PR updates the docker compose command in the Downloads page. See https://github.com/opensearch-project/documentation-website/pull/9227 for details.

Update docker compose command in downloads

---

_includes/footer.html

LF footer verbiage.

---

_includes/footer.html

Replacing text to be as provided from LF sans corrections.

---

_includes/footer.html
release-dashboard/index.md

Push to prod change order of release versions.

Push to prod change order of release versions

---

_calendars/2025-01.md
_calendars/2025-02.md
_calendars/2025-03.md
_events/2025-0318-3-00-alpha1-release-meetings.markdown
releases.md

Update 3.0.0 events / releases / fix calendars
https://github.com/opensearch-project/opensearch-build/issues/3747

Update 3.0.0 events / releases / fix calendars

---

_events/2025-0401-community-meeting.markdown

Had to reschedule the April Community Meeting due to conflict with KubeCon
n/a

Resched April Community Meeting

---

_calendars/2025-04.md
_events/2025-0422-3-00-beta1-release-meetings.markdown

Update 3.0.0 beta1 related events and dates
https://github.com/opensearch-project/opensearch-build/issues/3747

Update 3.0.0 beta1 related events and dates

---

_community_members/prudhvigodithi.md

Prudhvi Godithi Profile update
N/A

Prudhvi Godithi Profile update

---

_posts/2025-04-21-OpenSearch-Becnhmark--An-Update.md
_posts/2025-04-24-Announcing-Data-Prepper-2.11.md

Fix syntax in benchmark and data prepper blogs

Fix syntax in benchmark and data prepper blogs

---

.github/workflows/check-for-issue.yml
.github/workflows/process-new-blog.yml

Add workflow for new blog posts to:
1. Describe the blog process
2. Check that each new blog has an associated open issue

Add a workflow to check for open issue

---

.github/vale/styles/OpenSearch/HeadingLevel1.yml
.vale.ini
README.md

Document the new blog process and add a rule for heading level 1.

Add blog process and a heading 1 rule

---

_posts/2025-05-09-query-insights-live-queries.md

Add live queries blog for 3.0
[[List any issues this PR will resolve]](https://github.com/opensearch-project/project-website/issues/3775)

Add live queries blog for 3.0

---

MAINTAINERS.md

As much as I'd like to stay here it's time to migrate off. Thanks all for the fun times!

Move David to Emeritus

---

_posts/2025-06-26-Announcing-Data-Prepper-2.12.md

We are releasing Data Prepper 2.12 and this is our release blog.
Co-authors:
* @kkondaka 
* @huypham612 
* @ps48 
Resolves #3833

Data prepper 2.12 release blog

---

.github/CODEOWNERS

Removing myself from code owners.

Update CODEOWNERS file formatting

---

_community_members/akjain.md

Updates the profile page for akjain@

Updating akjain@ profile

---

_posts/2025-08-21-opensearch-writing-assistant-blog.md

Review edits for writing assistant blog post

Review edits for writing assistant blog post

---

_posts/2025-09-03-Introducing-OSCAR-The-AI-Chat-bot-that-Enables-OpenSearch-Conversational-Automation-for-Releases.md

Update oscar beta release in public slack and fix file name
#3929 
#3930

Update oscar beta release in public slack and fix file name

---

_posts/2025-09-03-Introducing-OSCAR-The-AI-Chat-bot-that-Enables-OpenSearch-Conversational-Automation-for-Releases.md

Add sisurab as part of the authors in OSCAR post
