opensearch-project/project-website

- README.md
Cleaned up some of the language around reporting security issues and added a contributing section after seeing @stockholmux's post on the forums about how he'd like to have help with the website.
Signed-off-by: Dawn M. Foster <fosterd@vmware.com>
> Clarified the contribution information in the readme.

- _config.yml
- _data/footer.yml
- _sass/_opensearch.scss
- faq/index.html
Added FAQ section (no content)
FAQ questions can be added as individual files to `/_faqs/` with this structure:
```
---
question: What colour is the sky?
category: General
--- 
The sky is blue.
``` 
Resolves #31
> added FAQ functionality

- _faqs/01-03-why-should-i-use-opensearch.markdown
- _faqs/01-04-is-opensearch-suitable-for-production-use.markdown
- _faqs/01-05-what-license-is-opensearch-released-under.markdown
- _faqs/01-06-is-aws-equipped-to-maintain-and-advance-a-project-like-opensearch.markdown
- _faqs/01-07-what-is-the-relationship-between-the-existing-open-distro-for-elasticsearch-project-and-opensearch.markdown
- _faqs/01-08-is-opensearch-wire-compatible-with-elasticsearch.markdown
- _faqs/01-09-will-the-opensearch-api-change-in-future-versions.markdown
- _faqs/01-10-do-elasticsearch-clients-like-logstash-and-beats-work-with-opensearch.markdown
- _faqs/01-11-does-opensearch-include-forks-of-logstash-and-beats.markdown
Added a batch of FAQ questions.
(related to #31)
> added batch of FAQ questions

- humans.txt
How do we feel about a humans.txt? Here's [a cool one](https://www.artsy.net/humans.txt), but we don't have any easter eggs, yet. 
> Added a humans.txt with a job search URL.

- _faqs/01-12-Can-I-upgrade-from-Elasticsearch-to-OpenSearch.markdown
- _faqs/01-13-which-features-of-elasticsearch-do-you-plan-to-offer-in-the-future-is-opensearch-going-to-keep-pace-with-the-upstream-elasticsearch-releases-how-will-this-evolve.markdown
- _faqs/01-14-can-opensearch-read-indices-from-previous-versions-of-elasticsearch.markdown
- _faqs/01-15-will-you-be-making-contributions-back-to-elasticsearch-open-source.markdown
- _faqs/01-16-i-want-to-contribute,-what-can-i-do.markdown
- _faqs/01-17-how-are-new-features,-bug-fixes,-and-other-development-decisions-made.markdown
- _faqs/01-18-what-will-your-governance-model-be-are-you-looking-at-any-foundations.markdown
- _faqs/02-02-can-i-install-an-opensearch-plugin-as-a-standalone-plugin.markdown
- _faqs/02-03-will-older-versions-of-open-distro-for-elasticsearch-plugins-still-be-available-for-open-source-elasticsearch.markdown
- _posts/OpenSearch-Beta-Announcement.Markdown
Added FAQs (01-12 through 02-03, minus 02/01) and add announcement draft for OpenSearch Beta. 
None specifically.
> Adding OpenSearch FAQs and Beta Announcement Draft to Staging

- _posts/2021-05-14-opensearch-beta-announcement.markdown
Fixed post front-matter - wasn't formatted properly
> fixed beta announcement blog post filename and frontmatter

- _data/opensearch_artifacts.yml
- downloads.html
Added verification information based on #63 (thanks @camerski!)
> added signatures and PGP key info to downloads page only

- _posts/2021-05-13-opensearch-beta-announcement.markdown
Beta pushed - update needed to blog post date
> fixed date of beta blog post

- assets/img/logo-opendistro.svg
- samples/docker-compose.yml
Fix location and variables in docker compose file
> Update docker compose

- _posts/2021-05-13-opensearch-beta-announcement.markdown
- samples/docker-compose.yml
Updates beta-1 blog post with download link
> Staging to main, downloads on beta-1 blog post

- _faqs/01-04-is-opensearch-suitable-for-production-use.markdown
Updates the FAQ to reflect the project is now in beta
> Update FAQ to reflect now in beta

- Gemfile
- Gemfile.lock
- _config.yml
- robots.txt
Added robots.txt and a sitemap. Let's get that SEO working.
> Added robots.txt and a sitemap.

- brand.markdown
> wording tweak

- _posts/2021-05-26-opensearch-roadmap-announcement.markdown
Updates the blog title to say roadmap to be consistent with the rest of the blog.
> Updates title to say roadmap

- index.markdown
This change updates the homepage right hand bar to include a "Have a question" to help anyone get their questions answered when they have one.
> Adds "Have a question" section to homepage

- _events/2021-early-june.markdown
- _sass/_opensearch.scss
Add event for community meeting
> Adding event

- _config.yml
- _includes/share-buttons.html
- _layouts/event.html
- _layouts/post.html
- _sass/_opensearch.scss
Sharing buttons didn't function properly. Also restyled. 
> fixing social sharing buttons

- _data/alert.yml
- _posts/2021-05-28-community-meeting.markdown
Added a blog post about a community meeting and link to the alert header. 
> Added blog post and link to beta-1 alert.

- _data/alert.yml
- downloads.html
Fixes problems found in review prior to RC1 launch
> fixes banner and download page beta-1 messages

- _posts/2021-06-07-opensearch-release-candidate-announcement.markdown
Fixes Wrong link in release blog for RC1
> fixes mislinking

- _authors/kyledvs.markdown
- _includes/author_panel.html
- _layouts/author.html
- _layouts/post.html
- _posts/2021-06-08-opensearch-backwards-compatibility-faq.markdown
- _sass/_opensearch.scss
Blog post about backwards compatibility, twitter is now in author bios
#120 
#112 
> Posting blog, adding twitter 

- _data/beta_feedback.yml
Made the link to report a bug a direct one.
> Direct link to reporting a bug.

- _posts/2021-06-09-opensearch-backwards-compatibility-faq.markdown
> changed post date after missed deployment

- _events/2021-early-july.markdown
- _events/2021-late-june.markdown
- events/index.html
added new events 
created made event sort order reverse cron
> added events, fixed sort order on events

- _events/2021-late-june.markdown
Agenda item addition for community meeting.
> added agenda item to late june meeting

- _posts/2021-06-21-data-into-opensearch.markdown
Added blog post to promote poll on forums regarding tools 
> added blog post for poll

- _partners/opster.md
Adding opster to the partners list. see publication: https://opster.com/blogs/announcing-opensearch-support/
> adding Opster to partners list

- _artifacts/opensearch-1.0.0/arm64/opensearch-1.0.0-min-linux-arm64.markdown
Resolves duplicate artifact listed on downloads page.  
ARM64 listed twice.
> fixing duplicate artifact

- _includes/header.html
Updates the destination for the "Documentation" top-menu item.
> Use relative /docs to access the documentation

- _artifacts/opensearch-cli/_opensearch-cli-1.0.0-macos-arm64.markdown
- _artifacts/opensearch-cli/_opensearch-cli-1.0.0-macos-x64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.0.0-linux-arm64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.0.0-linux-x64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.0.0-windows-x64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.0.0-windows-x86.markdown
- _includes/downloads/opensearch-cli.html
- _layouts/versions.html
- _versions/2021-07-12-opensearch-1.0.0.markdown
Adds artifacts of OpenSearch CLI (minus macos)  
#205
> Add OpenSearch-CLI and fix #205

- _artifacts/opensearch-cli/opensearch-cli-1.0.0-windows-x64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.0.0-windows-x86.markdown
Removed sig files for windows (not signed - installer is signed)
> removed unneeded sig files for windows

- _events/2021-late-july.markdown
> fixed copy/paste error on even title

- _faqs/01-11-does-opensearch-include-forks-of-logstash-and-beats.markdown
This change updates the documentation link for the compatibility matrices in the FAQ section to the correct page. 
#227 
> Updating Documentation Link for Agents and Ingestion Tools

- _community_projects/kubernetes-logging-helm.md
> Listing kubernetes-logging-helm on community projects

- _posts/2021-07-26-feature-highlight-opensearch-dashboards-notebooks.markdown
Changes date on blog post to the current date before publishing.
> fix date on blog post

- _events/2021-opensearch_community_meeting_dec.markdown
- _events/2021-opensearch_community_meeting_early_august.markdown
- _events/2021-opensearch_community_meeting_early_nov.markdown
- _events/2021-opensearch_community_meeting_early_oct.markdown
- _events/2021-opensearch_community_meeting_early_sept.markdown
- _events/2021-opensearch_community_meeting_late_august.markdown
- _events/2021-opensearch_community_meeting_late_nov.markdown
- _events/2021-opensearch_community_meeting_late_oct.markdown
- _events/2021-opensearch_community_meeting_late_sept.markdown
Adds community meetings for the remainder of 2021
> added remaining 2021 community meetings

- _events/2021-opensearch_community_meeting_early_sept.markdown
> fix am/pm mix up

- _posts/2021-08-02-streaming-analytics.markdown
Moved to a monday release for blog post 
> changed blog post date

- _includes/downloads/opensearch-docker.markdown
Give differential instructions for Docker quickstart
> Added docker host environment setup

- _sass/_opensearch.scss
Normalizes font on home page in feature list
> fix homepage font on feature-list

- Gemfile
- Gemfile.lock
- _config.yml
- _includes/author_panel.html
- _layouts/versions.html
- authors/index.html
- robots.txt
- versions/index.html
* Improves sitemap's last-modified
* Fixes paths to `versions`, `artifacts`, and `authors`
* Lets robots know to not bother with `javadocs`
> Sitemap enhancements & URL fixes

- _data/repos.yml
Start adding all repos to "source" page
> adding repos

- _data/repos.yml
- _layouts/default.html
- _layouts/source.html
- _sass/_opensearch.scss
- assets/js/main.js
- assets/js/mod/tag-picker.js
> added filtering logic

- _events/_sample.markdown
Adds sample file so others can create events
n/a
> added sample file

- README.md
Add copyright to readme to conform with rest of project 
#252 
> added copyright to README

- _versions/2021-09-01-opensearch-1.0.1.markdown
spacing change for push to staging 
> changing spacing on version before launch

- _posts/2021-09-01-A query, or There and Back Again.md
- _posts/2021-09-01-a-query-or-there-and-back-again.md
Make blog post active and correct filename issue 
> Query and back blog post

- _events/2021-opensearch_community_meeting_early_sept.markdown
Fixed mismatch between meetup (correct) and website (incorrect) timezone and meeting start time.
> fixed early sept timezone problem

- _events/2021-opensearch_community_meeting_early_sept.markdown
- _layouts/homepage.html
- _sass/_opensearch.scss
- downloads.html
- index.markdown
> Homepage version to prod

- _community_projects/opensearch-terraform.md
> Adding opensearch terraform module

- _authors/laneholl.markdown
> Add Github Id

- events/index.html
> fix a typo on events page

- .github/ISSUE_TEMPLATE/blog_post.md
> Issue templates

- .github/ISSUE_TEMPLATE/blog_post.md
- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/feature_request.md
Adding more issue templates + fixes
> added bug and feature templates

- old_downloads.html
- verify-signatures.markdown
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Replace the subid with the actual public key fingerprint
#332
> Replace the subid with the actual public key fingerprint

- _posts/2021-09-30-opensearch-py-js-go.markdown
Blog post about the release of the new opensearch clients. 
> added blog post about py,js,go clients

- _posts/2021-09-30-opensearch-py-js-go.markdown
- Added Peter to contributor  
- Replaced wrong social graph line.
> Fixed missing contributor and changed social preview

- _posts/2021-09-30-opensearch-py-js-go.markdown
Using correct `npm` instructions
> Fix issue with JS instructions

- _posts/2021-09-30-opensearch-py-js-go.markdown
> fixed npm link in intro

- _posts/2021-09-30-opensearch-py-js-go.markdown
> Move link fix into prod

- _artifacts/opensearch-1.0/arm64/opensearch-1.0.1-freebsd-arm64.markdown
- _artifacts/opensearch-1.0/arm64/opensearch-dashboards-1.0.1-freebsd-arm64.markdown
- _artifacts/opensearch-1.0/x64/opensearch-1.0.1-freebsd-x64.markdown
- _artifacts/opensearch-1.0/x64/opensearch-dashboards-1.0.1-freebsd-x64.markdown
- _artifacts/opensearch-1.0/x86/opensearch-1.0.1-freebsd-x86.markdown
- _artifacts/opensearch-1.0/x86/opensearch-dashboards-1.0.1-freebsd-x86.markdown
- _layouts/versions.html
- _posts/2021-09-30-opensearch-py-js-go.markdown
- artifacts/index.html
FreeBSD for OpenSearch 1.0.1 into production
> FreeBSD downloads

- _posts/2021-10-04-building-opensearch-1.1-distributions.markdown
Blog post wasn't on correct date and didn't use correct time format
> fixed blog post time

- _artifacts/opensearch-1.0/x64/opensearch-dashboards-1.0.0-docker-x64.markdown
- _artifacts/opensearch-1.0/x64/opensearch-dashboards-1.0.1-docker-x64.markdown
- _artifacts/opensearch-1.1/arm64/opensearch-1.1.0-docker-arm64.markdown
- _artifacts/opensearch-1.1/arm64/opensearch-1.1.0-linux-arm64.markdown
- _artifacts/opensearch-1.1/arm64/opensearch-1.1.0-min-linux-arm64.markdown
- _artifacts/opensearch-1.1/arm64/opensearch-dashboards-1.1.0-docker-arm64.markdown
- _artifacts/opensearch-1.1/arm64/opensearch-dashboards-1.1.0-linux-arm64.markdown
- _artifacts/opensearch-1.1/arm64/opensearch-dashboards-1.1.0-min-linux-arm64.markdown
- _artifacts/opensearch-1.1/x64/opensearch-1.1.0-docker-x64.markdown
- _artifacts/opensearch-1.1/x64/opensearch-1.1.0-linux-x64.markdown
- _artifacts/opensearch-1.1/x64/opensearch-1.1.0-min-linux-x64.markdown
- _artifacts/opensearch-1.1/x64/opensearch-dashboards-1.1.0-docker-x64.markdown
- _artifacts/opensearch-1.1/x64/opensearch-dashboards-1.1.0-linux-x64.markdown
- _artifacts/opensearch-1.1/x64/opensearch-dashboards-1.1.0-min-linux-x64.markdown
- _includes/artifact_tree.html
- _includes/downloads/final-section.html
- _versions/2021-10-05-opensearch-1.1.0.markdown
- artifacts/by-version/index.html
- artifacts/index.html
> Downloads v 1 1 0

- _artifacts/opensearch-1.1/arm64/opensearch-1.0.1-freebsd-arm64.markdown
- _artifacts/opensearch-1.1/arm64/opensearch-dashboards-1.0.1-freebsd-arm64.markdown
- _artifacts/opensearch-1.1/x64/opensearch-1.0.1-freebsd-x64.markdown
- _artifacts/opensearch-1.1/x64/opensearch-dashboards-1.0.1-freebsd-x64.markdown
- _artifacts/opensearch-1.1/x86/opensearch-1.0.1-freebsd-x86.markdown
- _artifacts/opensearch-1.1/x86/opensearch-dashboards-1.0.1-freebsd-x86.markdown
The FreeBSD ports have just been updated:
* https://www.freshports.org/textproc/opensearch/
* https://www.freshports.org/textproc/opensearch-dashboards/
n/a
> Add FreeBSD artifacts

- _artifacts/opensearch-1.1/arm64/opensearch-1.0.1-freebsd-arm64.markdown
- _artifacts/opensearch-1.1/arm64/opensearch-dashboards-1.0.1-freebsd-arm64.markdown
- _artifacts/opensearch-1.1/x64/opensearch-1.0.1-freebsd-x64.markdown
- _artifacts/opensearch-1.1/x64/opensearch-dashboards-1.0.1-freebsd-x64.markdown
- _artifacts/opensearch-1.1/x86/opensearch-1.0.1-freebsd-x86.markdown
- _artifacts/opensearch-1.1/x86/opensearch-dashboards-1.0.1-freebsd-x86.markdown
- _data/alert.yml
Moving new artifacts for 1.1.0 FreeBSD to prod
> Moving FreeBSD 1.1.0 downloads to prod

- _includes/footer_legal.html
Removed  “Amazon Web Services and individual contributors” to “OpenSearch contributors”
#199 
> updated to latest copyright guidance

- .gitpod-load.txt
- .gitpod.yml
Adds configuration files to make the repo have a preview on GitPod 
> add gitpod config files

- _tutorials/loading.markdown
Adds a tutorial loading screen
> added tutorial loading

- _posts/2021-11-05-bwc-testing-for-opensearch.markdown
corrects post date on BWC post. 
> fixing post date

- _layouts/tutorial.html
- _sass/_opensearch.scss
- _tutorials/data-prepper-jaeger.markdown
- _tutorials/loading.markdown
Added detection script to demo environment to allow for better detection of OpenSearch Dashboards
> Added demo environment detection script

- .github/pull_request_template.md
- .github/workflows/dco.yml
Add DCO workflow and update PR template to include the checklist
#334 
> Add DCO workflow and update PR template

- LICENSE
Fix copyright in LICENSE file
#252 
> Fix copyright in LICENSE file

- .gitignore
- _layouts/tutorial.html
Checks in a .gitignored directory now
> moving detection file and check script

- _layouts/tutorial.html
Errant comment in the javascript
> fixing relative stylesheet comment

- .gitignore
- _layouts/tutorial.html
> Tutorial template fix to production

- _tutorials/data-prepper-jaeger.markdown
Small changes needed on tutorial example 
> switching protocol and wording on tutorial

- _layouts/tutorial.html
- _tutorials/data-prepper-jaeger.markdown
Small changes to tutorial page 
> Move tutorial change to production

- _layouts/tutorial.html
> http to https on tutorial

- _tutorials/data-prepper-jaeger.markdown
Adds note in tutorial about refreshing the trace analytics page 
> adds note about refresh

- _plugins/search-indexer.rb
Produce indexable artifact for search
> Produce indexable artifact for search

- _community_projects/opensearch-flattened-mapper-plugin.md
Remove flattened mapper from community projects as it is 404ing
> remove flatten mapper

- _community_projects/opensearch-flattened-mapper-plugin.md
- _tutorials/data-prepper-jaeger.markdown
Removes community project that is 404ing.
> Remove flattened mapper from production

- _posts/2021-11-12-partner-highlight-instaclustr.md
Fixes blog post date on instaclustr blog
> fix blogpost date for instaclustr blog

- _posts/2021-11-12-partner-highlight-instaclustr.md
Make date align to actual publish date 
> fix date again on Instaclustr blog

- _data/footer.yml
- connect copy.markdown
- connect.markdown
Created a new Connect page and modified the footer - allows the community to connect with the project in a number of ways.
> New Connect page & footer change

- _includes/copy_banner.html
- _layouts/default.html
- _plugins/search-indexer.rb
- _sass/_custom-search.scss
- _sass/_style.scss
- assets/css/output.scss
- assets/js/search.js
Add custom-search to pages that have the heading bar.
Add testimonials and tutorials.
> Add custom-search

- .gitignore
- .gitpod.yml
- .vscode
- _demo/check-dashboards.sh
- _demo/docker-compose.yml
> initial demo code

- .gitpod.yml
Change port number for gitpod tutorial
> fixing port

- _tutorials/opn305.markdown
Changes how instructions are displayed in gitpod
> fixing lloading for gitpod tutorial

- _tutorials/opn305.markdown
Fixes gitpod button within tutorial
> fixing gitpod button

- _tutorials/opn305.markdown
Includes example with `curl` for creating a user.
> changes OPN305 tutorial to use REST API

- .gitpod.yml
Makes directory cleaner for tutorial user
> adds directory switch to gitpod

- .gitpod.yml
changes directory and one less terminal session
> reduce terminal sessions

- _tutorials/opn305.markdown
> small edits to OPN305

- _artifacts/opensearch-1.2/arm64/opensearch-1.2.0-docker-arm64.markdown
- _artifacts/opensearch-1.2/arm64/opensearch-1.2.0-linux-arm64.markdown
- _artifacts/opensearch-1.2/arm64/opensearch-1.2.0-min-linux-arm64.markdown
- _artifacts/opensearch-1.2/arm64/opensearch-dashboards-1.120-linux-arm64.markdown
- _artifacts/opensearch-1.2/arm64/opensearch-dashboards-1.2.0-docker-arm64.markdown
- _artifacts/opensearch-1.2/arm64/opensearch-dashboards-1.2.0-min-linux-arm64.markdown
- _artifacts/opensearch-1.2/x64/opensearch-1.2.0-docker-x64.markdown
- _artifacts/opensearch-1.2/x64/opensearch-1.2.0-linux-x64.markdown
- _artifacts/opensearch-1.2/x64/opensearch-1.2.0-min-linux-x64.markdown
- _artifacts/opensearch-1.2/x64/opensearch-dashboards-1.2.0-docker-x64.markdown
- _artifacts/opensearch-1.2/x64/opensearch-dashboards-1.2.0-linux-x64.markdown
- _artifacts/opensearch-1.2/x64/opensearch-dashboards-1.2.0-min-linux-x64.markdown
- _versions/2021-11-18-opensearch-1.2.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
Adds version 1.2.0 to downloads
> Opensearch 1 2 0 downloads

- _posts/2021-11-22-launch-announcement-1-2-0.markdown
Changes from review of 1.2.0 blog post  
> updated date, url, and link to release notes

- _data/_alert.yml
- _data/alert.yml
Top-of-website alert for 1.2.0
> adds alert for 1.2.0 release

- .github/ISSUE_TEMPLATE/bug_template.md
Signed-off-by: Tommy Markley <markleyt@amazon.com>
N/A
> Fixes typo in bug template

- _tutorials/opn305.markdown
Fix typos and small changes to tutorial after run through
> small edits for OPN305 tutorial

- _posts/2021-11-24-setup-multinode-cluster-kubernetes.markdown
- one grammar issue
- remove not needed comments
- Added except to make the homepage look better. 
#447 
> K8s blog update

- _tutorials/opn305-skratchpad_command.txt
- _tutorials/opn305.markdown
Adds command scratch pad  to OPN 305 tutorial
> OPN305: adding command scratchpad

- _posts/2021-11-24-setup-multinode-cluster-kubernetes.markdown
- _tutorials/opn305-skratchpad_command.txt
- _tutorials/opn305.markdown
- Move scratchpad to production for OPN305 
> Moving updates to OPN305 to production

- assets/js/search.js
Use ancestors in search results.
> Use ancestors in search results

- _posts/2021-12-01-plugins-intro.markdown
Fixes some small issues in final read through (publish date, tiny grammar tweaks, some spacing issues) 
> small tweaks to grammar and spacing

- assets/js/search.js
* Enhances the breadcrumbs shown with search results
* Uses `versionLabel` for search results of documentation
> Enhance search crumbs and use `versionLabel`

- _posts/2021-12-07-distributed-tracing-pipeline-with-opentelemetry.md
- fix levaraged 
- normalize filename
#444 
> fix spelling, filename

- _posts/2021-08-03-community-clients.markdown
Adds links to new clients in blog post about forking clients
#407 
> added links to new client on old blog post

- _posts/2021-12-09-connecting-java-high-level-rest-client-with-opensearch-over-https.markdown
- fixes date of post and filename
- adds syntax highlighting
#440 
> Connecting high level java fix

- _posts/2021-12-11-update-to-1-2-1.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
Corrects date on blog post and download page.
> fixes release date

- _artifacts/opensearch-1.2/arm64/opensearch-1.2.1-freebsd-arm64.markdown
- _artifacts/opensearch-1.2/x64/opensearch-1.2.1-freebsd-x64.markdown
- _artifacts/opensearch-1.2/x86/opensearch-1.2.1-freebsd-x86.markdown
Ports have been updated a few moments ago, new packages will be available soon!
> Add FreeBSD artifacts for OpenSearch 1.2.1

- _posts/2021-12-11-update-to-1-2-1.markdown
Updates 1.2.1 blog post to include additional information  
> updates blog post for 1.2.1 re new cve

- _artifacts/opensearch-cli/opensearch-cli-1.1.0-linux-arm64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.1.0-linux-x64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.1.0-macos-arm64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.1.0-macos-x64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.1.0-windows-x64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.1.0-windows-x86.markdown
- _versions/2021-07-12-opensearch-1.0.0.markdown
- _versions/2021-09-01-opensearch-1.0.1.markdown
- _versions/2021-10-05-opensearch-1.1.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
- _versions/_2021-12-14-opensearch-1.1.1.markdown
Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>
Add markdown and update latest version to 1.1
#557 
> Add artifacts for opensearch cli 1.1

- _artifacts/opensearch-cli/opensearch-cli-1.1.0-linux-arm64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.1.0-linux-x64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.1.0-macos-arm64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.1.0-macos-x64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.1.0-windows-x64.markdown
- _artifacts/opensearch-cli/opensearch-cli-1.1.0-windows-x86.markdown
- _posts/2021-12-11-update-to-1-2-1.markdown
- _versions/2021-07-12-opensearch-1.0.0.markdown
- _versions/2021-09-01-opensearch-1.0.1.markdown
- _versions/2021-10-05-opensearch-1.1.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
- _versions/_2021-12-14-opensearch-1.1.1.markdown
Moves artifacts for OpenSearch CLI 1.1.0 to production
#557 
> New OpenSearch CLI artifacts to production

- _artifacts/data-prepper/data-prepper-1.2.0-docker-x64.markdown
- _versions/2021-07-12-opensearch-1.0.0.markdown
- _versions/2021-09-01-opensearch-1.0.1.markdown
- _versions/2021-10-05-opensearch-1.1.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
- _versions/_2021-12-14-opensearch-1.1.1.markdown
> Updated the downloads page for Data Prepper 1.2.0.

- _posts/2021-12-09-connecting-java-high-level-rest-client-with-opensearch-over-https.markdown
Signed-off-by: Himanshu Setia <setiah@amazon.com>
Correcting version at a few places in the blog
#440 
> Minor corrections in java client blog

- _posts/2021-12-16-update-1-2-2.markdown
updates blog v1-2-2 blog post to reflect new logstash version 
> updates blog post with logstash info

- _layouts/homepage.html
Removed out dated block from homepage sidebar 
> removed still-need block from homepage

- _layouts/homepage.html
- _posts/2021-12-16-update-1-2-2.markdown
Moving staged change of sidebar change to production  
> Removal of section on sidebar to production

- _artifacts/logstash-oss-with-opensearch-output-plugin/logstash-oss-with-opensearch-output-plugin-7.16.2-docker-arm64.markdown
- _artifacts/logstash-oss-with-opensearch-output-plugin/logstash-oss-with-opensearch-output-plugin-7.16.2-docker-x64.markdown
- _artifacts/logstash-oss-with-opensearch-output-plugin/logstash-oss-with-opensearch-output-plugin-7.16.2-linux-arm64.markdown
- _artifacts/logstash-oss-with-opensearch-output-plugin/logstash-oss-with-opensearch-output-plugin-7.16.2-linux-x64.markdown
- _artifacts/logstash-oss-with-opensearch-output-plugin/logstash-oss-with-opensearch-output-plugin-7.16.2-macos-x64.markdown
- _versions/2021-07-12-opensearch-1.0.0.markdown
- _versions/2021-09-01-opensearch-1.0.1.markdown
- _versions/2021-10-05-opensearch-1.1.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
- _versions/2021-12-16-opensearch-1.2.2.markdown
- _versions/_2021-12-14-opensearch-1.1.1.markdown
Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>
Added new artifacts and updated version.
> Include artifacts for logstash 7.16.2

- _artifacts/data-prepper/data-prepper-1.2.1-docker-x64.markdown
- _versions/2021-07-12-opensearch-1.0.0.markdown
- _versions/2021-09-01-opensearch-1.0.1.markdown
- _versions/2021-10-05-opensearch-1.1.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
- _versions/2021-12-16-opensearch-1.2.2.markdown
- _versions/_2021-12-14-opensearch-1.1.1.markdown
Updated to Data Prepper 1.2.1.
This PR is for an upcoming release. Please wait for confirmation before merging.
N/A
> Updated Data Prepper to version 1.2.1

- _artifacts/opensearch-1.2/arm64/opensearch-1.2.3-freebsd-arm64.markdown
- _artifacts/opensearch-1.2/x64/opensearch-1.2.3-freebsd-x64.markdown
- _artifacts/opensearch-1.2/x86/opensearch-1.2.3-freebsd-x86.markdown
Add FreeBSD artifacts for OpenSearch 1.2.3
n/a
> Add FreeBSD artifacts for OpenSearch 1.2.3

- _events/2022-0104.markdown
- _events/2022-0111.markdown
- _events/2022-0118.markdown
- _events/2022-0124.markdown
Had to update a few dates and UTC times with the current pages
> Events page edits - Date fixes

- _events/2022-0201.markdown
- _events/2022-0208.markdown
- _events/2022-0214.markdown
- _events/2022-0221.markdown
I've created pages for the February 2022 events
> Created Events for February 2022

- _data/alert.yml
Removes banner to upgrade to 1.2.3 
n/a
> removes 1.2.3 upgrade banner

- _versions/2022-01-18-opensearch-1.2.4.markdown
> adds opensearch-min 1.2.4

- _community_projects/opensearch-checkup.md
The OpenSearch check-up analyzes architecture and configuration to provide you with specific recommendations for improvement and optimization. The Check-Up is free forever and based on JSON files so you don’t need to download or install anything.
> Adding OpenSearch checkup

- _includes/header.html
- index.markdown
Existing website makes it hard to know where OpenSearch can be downloaded from, so updating the text.  Note, its kind of wordy, but I am open to suggestions.
> Clarify that Get Started is how to download OpenSearch

- _events/2022-0301.markdown
- _events/2022-0308.markdown
- _events/2022-0314.markdown
- _events/2022-0321.markdown
- _events/2022-0329.markdown
New pages have been created for the March Community Events
> Events pages for March

- _posts/2022-02-10-getting-started-with-fluentd-and-opensearch.md
Adding DCO signature
[[List any issues this PR will resolve]](https://github.com/opensearch-project/project-website/issues/671)
> New blog post

- _posts/2022-02-01-data-prepper-1.2.1-performance-testing.md
Signed-off-by: Steven Bayer <smbayer@amazon.com>
Fixed incorrectly scaled throughput
Inaccurate data
> Fixed incorrect throughput metric

- _includes/footer_legal.html
- _layouts/versions.html
- _posts/2022-03-09-fine-dining-for-indices.md
- blog/index.html
- downloads.html
- events/index.html
- faq/index.html
- index.markdown
- partners/index.html
- source.markdown
- versions/index.html
Adds new footer information to particular pages. 
> Moves footer change to production

- _events/2022-0405.markdown
- _events/2022-0411.markdown
- _events/2022-0418.markdown
- _events/2022-0426.markdown
New events pages for April 2022
> Events pages for April 2022

- _artifacts/opensearch-1.3/arm64/_opensearch-1.3.0-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/_opensearch-dashboards-1.3.0-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.0-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.0-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.0-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.0-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.0-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.0-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/_opensearch-1.3.0-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/_opensearch-dashboards-1.3.0-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.0-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.0-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.0-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.0-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.0-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.0-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x86/_opensearch-1.3.0-freebsd-x86.markdown
- _artifacts/opensearch-1.3/x86/_opensearch-dashboards-1.3.0-freebsd-x86.markdown
- _versions/2022-03-17-opensearch-1.3.0.markdown
Adds artifacts for release 1.3.0 
Note: freebsd stubs are added but hidden.
> Adding V1 3 0

- _data/alert.yml
Add top of page alert to the website
> adds alert for 1.3.0

- _artifacts/data-prepper/data-prepper-1.3.0-docker-x64.markdown
- _artifacts/data-prepper/data-prepper-1.3.0-linux-x64.markdown
- _artifacts/data-prepper/data-prepper-1.3.0-no-jdk-linux-x64.markdown
- _versions/2021-07-12-opensearch-1.0.0.markdown
- _versions/2021-09-01-opensearch-1.0.1.markdown
- _versions/2021-10-05-opensearch-1.1.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
- _versions/2021-12-16-opensearch-1.2.2.markdown
- _versions/2021-12-22-opensearch-1.2.3.markdown
- _versions/2022-01-18-opensearch-1.2.4.markdown
- _versions/2022-03-17-opensearch-1.3.0.markdown
- _versions/_2021-12-14-opensearch-1.1.1.markdown
Signed-off-by: Asif Sohail Mohammed <nsifmoh@amazon.com>
Added Data Prepper 1.3.0 linux archives, Dockerfile image and updated version to 1.3.0
This PR is for an upcoming release. Please wait for confirmation before merging.
> Added Data Prepper 1.3.0 archives

- _posts/2022-03-24-getting-started-with-fluent-bit-and-opensearch.md
[Added Fluent Bit 1.9 blog post]
[[List any issues this PR will resolve](https://github.com/opensearch-project/project-website/issues/733)]
> Add blog post for Fluent Bit

- _faqs/01-20-what-tools-do-you-recommend-for-log-and-metrics-collection.md
- _faqs/01-21-what-tools-do-you-recommend-for-log-aggregation.markdown
- _faqs/02-01-can-i-use-opensearch-plugins-with-the-proprietary-stack.markdown
- _faqs/02-02-can-i-install-an-opensearch-plugin-as-a-standalone-plugin.markdown
- _faqs/02-03-will-older-versions-of-open-distro-for-elasticsearch-plugins-still-be-available-for-open-source-elasticsearch.markdown
- _faqs/02-04-does-opensearch-include-forks-of-logstash-and-beats.markdown
- _faqs/02-05-what-is-opensearch-data-prepper.markdown
- _faqs/02-06-what-is-fluentbit-and-fluentd.markdown
Signed-off-by: Naarcha-AWS <naarcha@amazon.com>
Fixes part of issue from the Documentation Project, https://github.com/opensearch-project/documentation-website/issues/467
- https://github.com/opensearch-project/documentation-website/issues/467
> Add FAQ questions related to LogStash and Fluent

- _artifacts/opensearch-1.3/arm64/_opensearch-1.3.1-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.1-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.1-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.1-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/_opensearch-1.3.1-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.1-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.1-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.1-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x86/_opensearch-1.3.1-freebsd-x86.markdown
- _versions/2022-03-31-opensearch-1.3.1.markdown
- Adds artifacts for 1.3.1 opensearch-min  (x64, arm64)
- Adds artifacts for 1.3.1 opensearch (x64, arm64)
- Adds artifacts for 1.3.1 opensearch-docker (x64, arm64)
- Version file 1.3.1
- Adds (hidden) freebsd artifact files (remove  initial `_` from filename to make these go live)
n/a
> adds v1.3.1 artifacts and version file

- _data/alert.yml
Removes banner at top of all pages
> removes banner

- _data/alert.yml
- _versions/2022-03-30-opensearch-1.3.1.markdown
Removes 1.3.0 related banner on production
> Removes banner on production

- _community_projects/prometheus-exporter-plugin.md
Add Prometheus exporter plugin for OpenSearch.
[Forum discussion](https://discuss.opendistrocommunity.dev/t/prometheus-exporter-plugin-1-3-0-0-released/8980/2)
Signed-off-by: Lukáš Vlček <lukas.vlcek@aiven.io>
> Add Prometheus exporter plugin for OpenSearch

- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.1-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.1-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.1-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.1-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.1-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.1-min-linux-x64.markdown
- _versions/2022-03-30-opensearch-1.3.1.markdown
Ready artifacts for release of v1.3.1 (dashboards)
> v1-3-1 Dashboards

- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.1-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.1-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.1-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.1-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.1-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.1-min-linux-x64.markdown
- _community_projects/prometheus-exporter-plugin.md
- _versions/2022-03-30-opensearch-1.3.1.markdown
Update to release 1.3.1 Dashboards
> Merge 1.3.1 Dashboards to production 

- _website-development-guides/directories.markdown
Adds a document describing project-website's directory structure 
> adds directories document

- _website-development-guides/content-best-practices.markdown
Adds tips for creating content on opensearch.org 
> Adds content best practices doc

- _events/2022-0503.markdown
- _events/2022-0509.markdown
- _events/2022-0516.markdown
- _events/2022-0524.markdown
- _events/2022-0531.markdown
- connect.markdown
New events pages for May 2022
N/A
> Events pages for May 2022

- _posts/2022-04-15-Partner-Highlight-Pureinsights-adds-OpenSearch-to-its-Discovery-Platform.markdown
Signed-off-by: Nereo Campos <nereo.campos@pureinsights.com>
> Remove technical-post category and update date

- _posts/2022-02-25-roadmap-proposal.md
Adding patch releases, updating 2.0-RC to move it out 2 days
Please crosscheck this -- dates are my achilleas heel ;) 
Thanks!
Signed-off-by: CEHENKLE <henkle@amazon.com>
> Adding patch releases to calendar

- _community_projects/opensearch-connector-for-apache-kafka.md
Add Kafka Connector for OpenSearch
Kafka logo source: https://www.apache.org/logos/#kafka
Expanding community projects page.
Signed-off-by: Lukáš Vlček <lukas.vlcek@aiven.io>
> Add Kafka Connector for OpenSearch

- _artifacts/opensearch-drivers/opensearch-odbc-1.4.0.0-macos-x64.markdown
- _artifacts/opensearch-drivers/opensearch-odbc-1.4.0.0-windows-x32.markdown
- _artifacts/opensearch-drivers/opensearch-odbc-1.4.0.0-windows-x64.markdown
Signed-off-by: Eric Wei <menwe@amazon.com>
Add sql-odbc drivers to _artifacts for 1.4.0.0 release
> Added sql odbc 1.4.0.0 release artifacts

- _posts/2022-05-03-release-candidate-2-0-available.md
Signed-off-by: Mcintyre <jamtyre@amazon.com>
Blog post to announce release of OpenSearch 2.0.0 RC1
n/a
> 2022 05 2.0 RC blog

- _artifacts/opensearch-2.0/arm64/opensearch-dashboards-2.0.0-rc1-linux-arm64-yum.markdown
- _artifacts/opensearch-2.0/x64/opensearch-dashboards-2.0.0-rc1-linux-x64-yum.markdown
- about.markdown
Fix download pages for yum files & add draft About page for main site
N/A
> Yum download page fixes

- _artifacts/opensearch-2.0/arm64/opensearch-dashboards-2.0.0-rc1-linux-arm64-yum.markdown
- _artifacts/opensearch-2.0/x64/opensearch-dashboards-2.0.0-rc1-linux-x64-yum.markdown
- _posts/2022-05-03-release-candidate-2-0-available.md
- about.markdown
Merge PR 794 yum download pages & draft About page
N/A
> Merge PR 794 yum download pages & draft About page

- _artifacts/opensearch-1.3/arm64/opensearch-1.3.2-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.2-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.2-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.2-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.2-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.2-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.2-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.2-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.2-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.2-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.2-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.2-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.2-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.2-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.2-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.2-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.2-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.2-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.2-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.2-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.2-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.2-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x86/opensearch-1.3.2-freebsd-x86.markdown
- _versions/2022-05-05-opensearch-1.3.2.markdown
- opensearch-2.0.0-rc1-linux-arm64-rpm.markdown
Website updates to support the 1.3.2 release
N/A
> 1.3.2 Release - website changes

- _data/alert.yml
Place a banner on the front page for the 1.3.2 download
N/A
> 1.3.2 front page banner

- _posts/2022-02-25-roadmap-proposal.md
Signed-off-by: CEHENKLE <henkle@amazon.com>
Updates the 2.0 GA date to allow for more testing since the RC1 take moved. 
> updated 2.0.0 GA date

- _artifacts/data-prepper/data-prepper-1.4.0-docker-x64.markdown
- _artifacts/data-prepper/data-prepper-1.4.0-linux-x64.markdown
- _artifacts/data-prepper/data-prepper-1.4.0-no-jdk-linux-x64.markdown
- _versions/2021-07-12-opensearch-1.0.0.markdown
- _versions/2021-09-01-opensearch-1.0.1.markdown
- _versions/2021-10-05-opensearch-1.1.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
- _versions/2021-12-16-opensearch-1.2.2.markdown
- _versions/2021-12-22-opensearch-1.2.3.markdown
- _versions/2022-01-18-opensearch-1.2.4.markdown
- _versions/2022-03-17-opensearch-1.3.0.markdown
- _versions/2022-03-30-opensearch-1.3.1.markdown
- _versions/2022-05-05-opensearch-1.3.2.markdown
- _versions/_2021-12-14-opensearch-1.1.1.markdown
Signed-off-by: Asif Sohail Mohammed <nsifmoh@amazon.com>
Added Data Prepper 1.4.0 linux archives, Dockerfile image and updated version to 1.4.0
Please wait for confirmation before merging.
> Added Data Prepper 1.4.0 Archives 

- _artifacts/data-prepper/data-prepper-1.4.0-docker-x64.markdown
- _artifacts/data-prepper/data-prepper-1.4.0-linux-x64.markdown
- _artifacts/data-prepper/data-prepper-1.4.0-no-jdk-linux-x64.markdown
- _posts/2022-05-13-tag-youre-it.md
- _versions/2021-07-12-opensearch-1.0.0.markdown
- _versions/2021-09-01-opensearch-1.0.1.markdown
- _versions/2021-10-05-opensearch-1.1.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
- _versions/2021-12-16-opensearch-1.2.2.markdown
- _versions/2021-12-22-opensearch-1.2.3.markdown
- _versions/2022-01-18-opensearch-1.2.4.markdown
- _versions/2022-03-17-opensearch-1.3.0.markdown
- _versions/2022-03-30-opensearch-1.3.1.markdown
- _versions/2022-05-05-opensearch-1.3.2.markdown
- _versions/_2021-12-14-opensearch-1.1.1.markdown
release Data Prepper 1.4.0
#813
> Pushing Data Prepper 1.4.0 GA

- _data/footer.yml
- connect.markdown
- verify-signatures.markdown
Updates to footer, as well as verify_signature & connect pages
N/A
> Verify sig connect & footer updates

- _data/footer.yml
- about.markdown
Adding an About page - moving some content to it
N/A
> New about page

- _posts/2022-05-19-introducing-logstash-input-opensearch-plugin-for-opensearch.md
> Logstash input change

- _posts/2022-05-09-opensearchcon.markdown
Small edit in the blog post
N/A
> OpenSearchCon blog edit

- _events/2022-0606.markdown
- _events/2022-0613.markdown
- _events/2022-0621.markdown
- _events/2022-0628.markdown
- _events/2022-0921-opensearchcon.markdown
Adding to events page - June & OpenSearchCon
N/A
> 2022 06 events pages & opensearchcon

- _events/2022-0606.markdown
- _events/2022-0613.markdown
- _events/2022-0621.markdown
- _events/2022-0628.markdown
- _events/2022-0921-opensearchcon.markdown
- _posts/2022-05-09-opensearchcon.markdown
Adding events pages for June Community Meetings as well as OpenSearchCon
n/a
> Events pages for June and OpenSearchCon

- _layouts/homepage.html
- index.markdown
Edits to the homepage text
N/A
> Homepage edits

- _data/footer.yml
- _includes/head.html
- _includes/header.html
Update of the top navigation
N/A
> menu update

- _artifacts/opensearch-1.3/arm64/opensearch-1.3.3-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.3-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.3-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.3-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.3-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.3-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.3-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.3-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.3-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.3-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.3-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.3-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.3-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.3-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.3-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.3-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.3-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.2-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.3-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.3-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.3-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.3-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.3-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x86/opensearch-1.3.3-freebsd-x86.markdown
- _versions/2022-06-09-opensearch-1.3.3.markdown
Updates to the download area to support our 1.3.3 release
N/A
> Version 1.3.3 release website updates

- _events/2022-0621.markdown
Date change for our 6/21 event to new date of 6/22
n/a
> Event date change

- _artifacts/opensearch-2.0/arm64/_opensearch-2.0.1-freebsd-arm64.markdown
- _artifacts/opensearch-2.0/arm64/opensearch-2.0.1-docker-arm64.markdown
- _artifacts/opensearch-2.0/arm64/opensearch-2.0.1-linux-arm64-rpm.markdown
- _artifacts/opensearch-2.0/arm64/opensearch-2.0.1-linux-arm64-yum.markdown
- _artifacts/opensearch-2.0/arm64/opensearch-2.0.1-linux-arm64.markdown
- _artifacts/opensearch-2.0/arm64/opensearch-2.0.1-min-linux-arm64.markdown
- _artifacts/opensearch-2.0/arm64/opensearch-dashboards-2.0.1-docker-arm64.markdown
- _artifacts/opensearch-2.0/arm64/opensearch-dashboards-2.0.1-linux-arm64-rpm.markdown
- _artifacts/opensearch-2.0/arm64/opensearch-dashboards-2.0.1-linux-arm64-yum.markdown
- _artifacts/opensearch-2.0/arm64/opensearch-dashboards-2.0.1-linux-arm64.markdown
- _artifacts/opensearch-2.0/arm64/opensearch-dashboards-2.0.1-min-linux-arm64.markdown
- _artifacts/opensearch-2.0/x64/_opensearch-2.0.1-freebsd-x64.markdown
- _artifacts/opensearch-2.0/x64/_opensearch-dashboards-2.0.1-freebsd-x64.markdown
- _artifacts/opensearch-2.0/x64/opensearch-2.0.1-docker-x64.markdown
- _artifacts/opensearch-2.0/x64/opensearch-2.0.1-linux-x64-rpm.markdown
- _artifacts/opensearch-2.0/x64/opensearch-2.0.1-linux-x64-yum.markdown
- _artifacts/opensearch-2.0/x64/opensearch-2.0.1-linux-x64.markdown
- _artifacts/opensearch-2.0/x64/opensearch-2.0.1-min-linux-x64.markdown
- _artifacts/opensearch-2.0/x64/opensearch-dashboards-2.0.1-docker-x64.markdown
- _artifacts/opensearch-2.0/x64/opensearch-dashboards-2.0.1-linux-x64-rpm.markdown
- _artifacts/opensearch-2.0/x64/opensearch-dashboards-2.0.1-linux-x64-yum.markdown
- _artifacts/opensearch-2.0/x64/opensearch-dashboards-2.0.1-linux-x64.markdown
- _artifacts/opensearch-2.0/x64/opensearch-dashboards-2.0.1-min-linux-x64.markdown
- _data/alert.yml
- _versions/2022-06-16-opensearch-2.0.1.markdown
Updates for the 2.0.1 release
N/A
> OpenSearch 2.0.1 release website updates

- _posts/2022-06-23-S3-Log-Ingestion-Using-Data-Prepper-1.5.0.md
Blog post announcing the launch of Data Prepper 1.5.0, focused on the S3 Source support.
N/A
> Created the launch announcement blog post for Data Prepper 1.5.0.

- _posts/2022-02-25-roadmap-proposal.md
- _posts/2022-05-16-opentelemetry-metrics-for-data-prepper.md
Metrics Ingestion with Data Prepper using OpenTelemetry - update code
n/a
> Update to open telemetry blog postr

- _events/2022-0705.markdown
- _events/2022-0712.markdown
- _events/2022-0719.markdown
- _events/2022-0726.markdown
> July 2022 Events pages

- _events/2022-0705.markdown
- _events/2022-0712.markdown
- _events/2022-0719.markdown
- _events/2022-0726.markdown
- _posts/2022-05-16-opentelemetry-metrics-for-data-prepper.md
events pages for July 2022
n/a
> Adding Events pages for July 2022

- _data/alert.yml
- _data/footer.yml
- releases.md
New 'releases' page with Release Schedule and Maintenance Policy
n/a
> Release Schedule and Maintenance Policy

- _sass/_tables.scss
- assets/css/output.scss
- releases.md
Fixed date formats
Added table styling
> Cleanup style on the Releases page

- _artifacts/opensearch-2.1/arm64/_opensearch-2.1.0-freebsd-arm64.markdown
- _artifacts/opensearch-2.1/arm64/opensearch-2.1.0-docker-arm64.markdown
- _artifacts/opensearch-2.1/arm64/opensearch-2.1.0-linux-arm64-rpm.markdown
- _artifacts/opensearch-2.1/arm64/opensearch-2.1.0-linux-arm64-yum.markdown
- _artifacts/opensearch-2.1/arm64/opensearch-2.1.0-linux-arm64.markdown
- _artifacts/opensearch-2.1/arm64/opensearch-2.1.0-min-linux-arm64.markdown
- _artifacts/opensearch-2.1/arm64/opensearch-dashboards-2.1.0-docker-arm64.markdown
- _artifacts/opensearch-2.1/arm64/opensearch-dashboards-2.1.0-linux-arm64-rpm.markdown
- _artifacts/opensearch-2.1/arm64/opensearch-dashboards-2.1.0-linux-arm64-yum.markdown
- _artifacts/opensearch-2.1/arm64/opensearch-dashboards-2.1.0-linux-arm64.markdown
- _artifacts/opensearch-2.1/arm64/opensearch-dashboards-2.1.0-min-linux-arm64.markdown
- _artifacts/opensearch-2.1/x64/_opensearch-2.1.0-freebsd-x64.markdown
- _artifacts/opensearch-2.1/x64/_opensearch-dashboards-2.1.0-freebsd-x64.markdown
- _artifacts/opensearch-2.1/x64/opensearch-2.1.0-docker-x64.markdown
- _artifacts/opensearch-2.1/x64/opensearch-2.1.0-linux-x64-rpm.markdown
- _artifacts/opensearch-2.1/x64/opensearch-2.1.0-linux-x64-yum.markdown
- _artifacts/opensearch-2.1/x64/opensearch-2.1.0-linux-x64.markdown
- _artifacts/opensearch-2.1/x64/opensearch-2.1.0-min-linux-x64.markdown
- _artifacts/opensearch-2.1/x64/opensearch-dashboards-2.1.0-docker-x64.markdown
- _artifacts/opensearch-2.1/x64/opensearch-dashboards-2.1.0-linux-x64-rpm.markdown
- _artifacts/opensearch-2.1/x64/opensearch-dashboards-2.1.0-linux-x64-yum.markdown
- _artifacts/opensearch-2.1/x64/opensearch-dashboards-2.1.0-linux-x64.markdown
- _artifacts/opensearch-2.1/x64/opensearch-dashboards-2.1.0-min-linux-x64.markdown
- _data/alert.yml
- _versions/2022-07-07-opensearch-2.1.0.markdown
- index.markdown
Website updates for the 2.1.0 release
n/a
> 2.1.0 Release

- _artifacts/data-prepper/data-prepper-1.5.1-docker-x64.markdown
- _artifacts/data-prepper/data-prepper-1.5.1-linux-x64.markdown
- _artifacts/data-prepper/data-prepper-1.5.1-no-jdk-linux-x64.markdown
- _versions/2021-07-12-opensearch-1.0.0.markdown
- _versions/2021-09-01-opensearch-1.0.1.markdown
- _versions/2021-10-05-opensearch-1.1.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
- _versions/2021-12-16-opensearch-1.2.2.markdown
- _versions/2021-12-22-opensearch-1.2.3.markdown
- _versions/2022-01-18-opensearch-1.2.4.markdown
- _versions/2022-03-17-opensearch-1.3.0.markdown
- _versions/2022-03-30-opensearch-1.3.1.markdown
- _versions/2022-05-05-opensearch-1.3.2.markdown
- _versions/2022-05-26-opensearch-2.0.0.markdown
- _versions/2022-06-09-opensearch-1.3.3.markdown
- _versions/2022-06-16-opensearch-2.0.1.markdown
- _versions/2022-07-07-opensearch-2.1.0.markdown
- _versions/_2021-12-14-opensearch-1.1.1.markdown
Signed-off-by: Asif Sohail Mohammed <nsifmoh@amazon.com>
Added Data Prepper 1.5.1 linux archives, Dockerfile image and updated version to 1.5.1
> Added Data Prepper 1.5.1 archives and updated version to 1.5.1

- _posts/2022-07-13-whatsnew-document-level-monitors.md
[Added a new blog post]
[#902]
> New blog post for document level alerting

- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.4-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.4-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.4-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.4-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.4-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.4-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.4-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.4-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.4-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.4-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x86/opensearch-1.3.4-freebsd-x86.markdown
- _data/footer.yml
- _versions/2022-07-14-opensearch-1.3.4.markdown
Download page updates for the 1.3.4 release & added YouTube link to the footer
n/a
> Download page updates for 1.3.4 release

- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.4-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.4-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.4-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.4-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.4-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.4-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.4-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.4-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.4-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.4-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.4-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.4-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x86/opensearch-1.3.4-freebsd-x86.markdown
- _data/footer.yml
- _faqs/03-30-does-opensearch-support-downgrades.markdown
- _versions/2022-07-14-opensearch-1.3.4.markdown
> v1.3.4 release

- _versions/2022-07-07-opensearch-2.1.0.markdown
- _versions/2022-07-14-opensearch-1.3.4.markdown
Fixes a typo in the minimal distribution download link
n/a
> Fix for 2.1.0 minimal download link

- _data/top_nav.yml
- _includes/header.html
- _sass/_nested-nav.scss
- assets/css/output.scss
This is to introduce a 2-tier top navigation menu.
https://user-images.githubusercontent.com/3527403/178615472-4587fd3a-fc75-46c3-accf-7241eb8b9279.mp4
> Enhanced top nav

- _includes/header.html
> Fix false-positive highlighting of nav items with absolute urls

- _community_projects/kubernetes-logging-helm.md
Signed-off-by: Saji Nediyanchath <saji89@gmail.com>
Fix typos in kubernetes-logging-helm.md
None
> Fix typos in kubernetes-logging-helm.md

- _data/footer.yml
- _events/2022-0802.markdown
- _events/2022-0816.markdown
- _events/2022-0830.markdown
Community Meetings are going to an every other week schedule again. Removed 7/26 event - added August events
n/a
> New events pages for August

- _posts/2022-07-21-aggregate-by-multiple-terms.md
- _posts/2022-07-22-aggregate-by-multiple-terms.md
Signed-off-by: David Tippett <dtip@amazon.com>
This adds a post to accompany the mutli-terms feature. This post features a full demo that covers an end to end example of multi-terms aggregation. 
n/a
> Adding Aggregate by Multiple Terms Post

- _posts/2022-05-09-opensearchcon.markdown
Two small changes to ~~strikethrough~~ CFP & exhibit links
n/a
> OpenSearchCon blog fix

- _posts/2022-05-09-opensearchcon.markdown
- _posts/2022-07-21-aggregate-by-multiple-terms.md
small edits to the OpenSearchCon blog post
n/a
> Quick edit to the OpenSearchCon blog post

- _layouts/homepage.html
- index.markdown
Adding a hero banner area and usage notes to the front page
currently pointed to the OpenSearchCon blog
n/a
> Added hero banner for OpenSearchCon

- _layouts/homepage.html
- _posts/2022-05-09-opensearchcon.markdown
- index.markdown
New hero banner and usage notes for the front page of the site
Starting with a promo for OpenSearchCon
n/a
> Created a hero banner for the website

- _faqs/01-01-what-is-opensearch.markdown
- _faqs/02-03-will-older-versions-of-open-distro-for-elasticsearch-plugins-still-be-available-for-open-source-elasticsearch.markdown
- _faqs/03-03-which-versions-of-elasticsearch-oss-and-kibana-can-i-upgrade-from-to-opensearch-and-opensearch-dashboards-directly.markdown
Updates to FAQs 1.1, 2.3, & 3.3
[938](https://github.com/opensearch-project/project-website/issues/938)
> FAQ updates

- _artifacts/opensearch-2.2/arm64/_opensearch-2.2.0-freebsd-arm64.markdown
- _artifacts/opensearch-2.2/arm64/opensearch-2.2.0-docker-arm64.markdown
- _artifacts/opensearch-2.2/arm64/opensearch-2.2.0-linux-arm64-rpm.markdown
- _artifacts/opensearch-2.2/arm64/opensearch-2.2.0-linux-arm64-yum.markdown
- _artifacts/opensearch-2.2/arm64/opensearch-2.2.0-linux-arm64.markdown
- _artifacts/opensearch-2.2/arm64/opensearch-2.2.0-min-linux-arm64.markdown
- _artifacts/opensearch-2.2/arm64/opensearch-dashboards-2.2.0-docker-arm64.markdown
- _artifacts/opensearch-2.2/arm64/opensearch-dashboards-2.2.0-linux-arm64-rpm.markdown
- _artifacts/opensearch-2.2/arm64/opensearch-dashboards-2.2.0-linux-arm64-yum.markdown
- _artifacts/opensearch-2.2/arm64/opensearch-dashboards-2.2.0-linux-arm64.markdown
- _artifacts/opensearch-2.2/arm64/opensearch-dashboards-2.2.0-min-linux-arm64.markdown
- _artifacts/opensearch-2.2/x64/_opensearch-2.2.0-freebsd-x64.markdown
- _artifacts/opensearch-2.2/x64/_opensearch-dashboards-2.2.0-freebsd-x64.markdown
- _artifacts/opensearch-2.2/x64/opensearch-2.2.0-docker-x64.markdown
- _artifacts/opensearch-2.2/x64/opensearch-2.2.0-linux-x64-rpm.markdown
- _artifacts/opensearch-2.2/x64/opensearch-2.2.0-linux-x64-yum.markdown
- _artifacts/opensearch-2.2/x64/opensearch-2.2.0-linux-x64.markdown
- _artifacts/opensearch-2.2/x64/opensearch-2.2.0-min-linux-x64.markdown
- _artifacts/opensearch-2.2/x64/opensearch-dashboards-2.2.0-docker-x64.markdown
- _artifacts/opensearch-2.2/x64/opensearch-dashboards-2.2.0-linux-x64-rpm.markdown
- _artifacts/opensearch-2.2/x64/opensearch-dashboards-2.2.0-linux-x64-yum.markdown
- _artifacts/opensearch-2.2/x64/opensearch-dashboards-2.2.0-linux-x64.markdown
- _artifacts/opensearch-2.2/x64/opensearch-dashboards-2.2.0-min-linux-x64.markdown
- _data/alert.yml
- _versions/2022-08-11-opensearch-2.2.0.markdown
Download pages and banner announcements for the 2.2.0 release
n/a
> OpenSearch 2.2.0 release updates

- _events/2022-0913.markdown
- _events/2022-0927.markdown
Adding September events to the site
n/a
> September Events

- _posts/2022-08-17-dattell-compares.markdown
Summary post about Dattell's latest blog 
n/a
> Dattell partner summary post

- releases.md
Release date change for 1.3.5 - added 2.2.1 patch
n/a
> Releases page update

- _posts/2022-08-17-dattell-compares.markdown
- releases.md
New release date for 1.3.5
Added 2.2.1 patch dates
n/a
> Updating the releases page

- _posts/2022-08-23-Agent-Ingestion-Usage-In-OpenSearch-Survey-Results.md
Initial proposal for the blog
[[961](https://github.com/opensearch-project/project-website/issues/961)]
> Client Ingestion Survey Results

- _data/footer.yml
- releases.md
Release page update 1.3.5 & 2.2.1 and a couple minor footer updates
n/a
> Release page update 1.3.5 & 2.2.1, footer updates

- _versions/2021-07-12-opensearch-1.0.0.markdown
- _versions/2021-09-01-opensearch-1.0.1.markdown
- _versions/2021-10-05-opensearch-1.1.0.markdown
- _versions/2021-11-23-opensearch-1.2.0.markdown
- _versions/2021-12-11-opensearch-1.2.1.markdown
- _versions/2021-12-16-opensearch-1.2.2.markdown
- _versions/2021-12-22-opensearch-1.2.3.markdown
- _versions/2022-01-18-opensearch-1.2.4.markdown
- _versions/2022-03-17-opensearch-1.3.0.markdown
- _versions/2022-03-30-opensearch-1.3.1.markdown
- _versions/2022-04-28-opensearch-2.0.0-rc1.markdown
- _versions/2022-05-05-opensearch-1.3.2.markdown
- _versions/2022-05-26-opensearch-2.0.0.markdown
- _versions/2022-06-09-opensearch-1.3.3.markdown
- _versions/2022-06-16-opensearch-2.0.1.markdown
- _versions/2022-07-07-opensearch-2.1.0.markdown
- _versions/2022-07-14-opensearch-1.3.4.markdown
- _versions/2022-08-11-opensearch-2.2.0.markdown
- _versions/2022-09-01-opensearch-1.3.5.markdown
- _versions/2022-09-01-opensearch-2.2.1.markdown
- _versions/_2021-12-14-opensearch-1.1.1.markdown
Updating versions for logstash-oss-with-opensearch-output-plugin to 8.4.0
Signed-off-by: Deep Datta <deedatta@amazon.com>
> Updating versions for logstash-oss-with-opensearch-output-plugin to 8.4.0

- _includes/downloads/drivers.markdown
- _includes/downloads/jdbc.markdown
- _includes/downloads/opensearch-docker.markdown
Signed-off-by: David Tippett <dtip@amazon.com>
This fixes several typo's that were present on the project website.
#879
> Minor Editorial changes that resolve #879

- _posts/2022-08-23-New-series-From-the-editors-desk.md
Signed-off-by: natebower <102320899+natebower@users.noreply.github.com>
Updates blog post
> Updates blog post

- _posts/2022-09-12-sql-search-relevance-selective-aggregation-and-window-functions-in-OpenSearch.md
[Proposal for blog post]
[[project-website/issues/986](https://github.com/opensearch-project/project-website/pull/988)]
> New blog post proposal highlighting recently release SQL commands

- _posts/2022-09-14-opensearch-2-3-is-ready-for-download.md
Signed-off-by: James McIntyre <jamtyre@amazon.com>
Changes mentions of "2.3" to "2.3.0" throughout blog post
> copy edit to 2.3.0 blog post

- _data/top_nav.yml
- _events/2022-1011.markdown
- _events/2022-1025.markdown
Add October events pages and small change to 'download' nav in menu
n/a
> October events pages & small navigation update

- _sass/_custom-search.scss
- _sass/_nested-nav.scss
> Fixes the nested nav's interaction with the custom search component

- README.md
- index.markdown
Remove OpenSearchCon hero banner & a couple small edits
n/a
> Homepage update & small edits

- _includes/testimonial-carousel-slide.html
- _includes/testimonial-carousel.html
- _layouts/homepage.html
- _testimonials/openinfrafoundation.markdown
- _testimonials/quantiphi.markdown
- _testimonials/rackspace.markdown
- index.markdown
A small spot gets added to the bottom of the page (a series of divs) where we render all our testimonials, but only one div is visible at a time. Rotates every 25 seconds. 
#1034 
> Implements a small carousel of testimonials at the bottom of the homepage.

- _posts/2022-09-27-whatsnew-custom-geo-json.md
Signed-off-by: Alice Williams <alicejw@amazon.com>
reorder photos for the blog post
> reorder author photos for the blog post

- _posts/2022-09-26-opensearch-playground.md
- _posts/2022-10-03-hacktoberfest-2022.md
> Blog date fixes

- _artifacts/opensearch-1.3/arm64/opensearch-1.3.6-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.6-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.6-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.6-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.6-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.6-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.6-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.6-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.6-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.6-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.6-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.6-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.6-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.6-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.6-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.6-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.6-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.6-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.6-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.6-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.6-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.6-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x86/opensearch-1.3.6-freebsd-x86.markdown
- _versions/2022-10-06-opensearch-1.3.6.markdown
Updates to the download page in preparation for the 1.3.6 release
n/a
> Download page updates for 1.3.6

- _authors/dlv.markdown
> Updated the bio for David Venable.

- _posts/2022-10-10-Announcing-Data-Prepper-2.0.0.md
Removes some extra text which should not have been there.
N/A
> Fixed extra text left from PR review for Data Prepper 2.0.0 blog post.

- about.markdown
- index.markdown
Move Founding Documents section from front page to About page
n/a
> move Founding Documents

- _events/2022-1024-dev-triage-security.markdown
- _events/2022-1024-open-observability-day.markdown
- _events/2022-1031-dev-triage-security.markdown
- _events/2022-1107-ubuntu-summit.markdown
- _events/2022-1122.markdown
- _posts/2022-10-20-aws-knn-algorithms-workload-optimizations.markdown
Partner blog post & events pages for upcoming meetings
n/a
> Events pages and blog post

- releases.md
Signed-off-by: CEHENKLE <henkle@amazon.com>
Adds in proposed 2023 schedule
We don't stop releasing at the end of 2022 ;) 
> adding 2023 proposed schedule

- _posts/2022-10-25-ltr-with-opensearch-and-metarank.markdown
In the blog post there's a broken link to the docs, this PR fixes the broken link.
> Blog post fix: Learn-to-Rank with OpenSearch and Metarank

- _authors/vamshin.markdown
Signed-off-by: vamshin <vamshin@amazon.com>
updated markdown with corrections
> updated markdown with corrections

- _posts/2022-10-26-OpenSearch-Project-voice-and-tone.md
Signed-off-by: natebower <102320899+natebower@users.noreply.github.com>
FTED 2: Voice and tone
> New FTED file

- _data/top_nav.yml
Signed-off-by: Vimal K <vimalinfo10@gmail.com>
Added Link to the Playground in Navigation
closes #1073 
> Added Link to the Playground in Navigation. Fix #1073

- _events/2022-1107-dev-triage-security.markdown
- _events/2022-1114-dev-triage-security.markdown
- _events/2022-1121-dev-triage-security.markdown
- _events/2022-1128-dev-triage-security.markdown
- _events/2022-1205-dev-triage-security.markdown
- _events/2022-1212-dev-triage-security.markdown
- _events/2022-1219-dev-triage-security.markdown
- _versions/2022-10-06-opensearch-1.3.6.markdown
Security triage and backlog meetings
https://github.com/opensearch-project/project-website/pull/1130
> Push Security meetings live to events page

- _posts/2022-11-08-thudtest.md
Fixes a bug where the title for Thud Test blog appears twice.
> Fix Thud Test title

- _posts/2022-11-15-opensearch-2-4-is-available-today.md
- _versions/2022-11-15-opensearch-2.4.0.markdown
new 2.4.0 release blog & 2.4.0 download date update
n/a
> 2.4 release blog

- _versions/2022-11-15-opensearch-2.4.0.markdown
Signed-off-by: Lukáš Vlček <lukas.vlcek@aiven.io>
2.4.0 download links for minimal artifacts point to 2.3.0 zip files
n/a
> Fix download links for 2.4.0 minimal artifacts

- _events/2022-1206.markdown
- _events/2022-1220.markdown
December Community Meeting event pages
n/a
> December events

- _posts/2021-10-29-moving-from-opensource-elasticsearch-to-opensearch.markdown
Signed-off-by: vagimeli <vagimeli@amazon.com>
Describe the blog post your would like to write
This is a blog refresh to update technical information as of OpenSearch 2.4; blog link https://opensearch.org/blog/technical-posts/2021/10/moving-from-opensource-elasticsearch-to-opensearch/
What is the title of the blog post?
Moving from open source Elasticsearch to OpenSearch
Who are the authors?
Sarat Vemulapalli
What is the proposed posting date?
11/10
#1135 
> Blog: Refresh Moving from open source Elasticsearch to OpenSearch

- _events/2022-1206.markdown
- _events/2022-1220.markdown
Fixed the UTC time on December events
n/a
> event utc fix

- _community_projects/opensearch-management-console.md
- _events/2022-1206.markdown
- _events/2022-1220.markdown
Quick UTC time fix on December events
n/a
> Quick UTC time fix on December events

- _posts/2022-11-28-searchium-improve-search-performance.markdown
Blog post to highlight and link to recent post from Searchium.ai
N/A 
> Partner highlight - Searchium

- releases.md
Update to the release page for 1.3.7 
n/a
> Release page update 1.3.7

- _includes/youtube-player.html
- _sass/_web-embed.scss
- docs/add-video.md
- Template for YouTube Embeds
- CSS
- Docs page describing how to add videos
Signed-off-by: David Tippett <dtip@amazon.com>
This change allows us to embed YouTube videos with a reusable component.  
N/A
> Added supporting pieces to enable YouTube embeds.

- _authors/mnkugler.markdown
- _authors/mtimmerm.markdown
- _posts/2022-12-13-aws-sigv4-support-for-clients.md
Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>
Fixes minor issues with SigV4 blog post
> Fix issues with SigV4 blog post

- _includes/feedback.html
- index.markdown
a few minor home page edits
n/a
> Home page edits

- _posts/2022-12-13-aws-sigv4-support-for-clients.md
Ended up writing working demos for every client doing Sigv4 when trying to update https://code.dblock.org/2022/07/11/making-sigv4-authenticated-requests-to-managed-opensearch.html, and found a few problems here.
- Sigv4 is lowercase (.NET client namespace is the exception)
- Made all the host names consistent to `search-xxx.region.es.amazonaws.com`
- Made all the samples output server info
- Updated Python code to take a URL and correctly deduce port
- Removed confusing comments
- Added missing host in Ruby sample
- Fixed Rust sample, couldn't get the aws config to work as written 
- Used defaults in PHP sample
- Removed sdk v1 php sample which looks identical to v2, just includes are different
Working demos:
- …
> Various fixes for the Sigv4 blog post.

- _events/2023-0116-dev-triage-security.markdown
- _events/_0000-0000-communitymeeting-template.markdown
- _posts/2022-05-09-opensearchcon-2022.markdown
- _posts/2022-10-03-hacktoberfest-2022.md
Edits to 1/16 triage meeting
Move opensearchcon blog url to opensearchcon-2022
Minor Hacktoberfest blog edit
n/a
> Event and blog edits

- _events/2023-0116-dev-triage-security.markdown
- _events/_0000-0000-communitymeeting-template.markdown
- _posts/2020-04-06-Building-k-Nearest-Neighbor-(k-NN)-Similarity-Search-Engine-with-Elasticsearch.markdown
- _posts/2022-05-09-opensearchcon-2022.markdown
- _posts/2022-10-03-hacktoberfest-2022.md
Event and blog edits
https://github.com/opensearch-project/project-website/pull/1276
> Event page and blog edits

- _authors/daryllswager.markdown
- _authors/jamesmcintyre.markdown
- _authors/krisfreedain.markdown
- _posts/2023-01-12-aws-kendra-intelligent-ranking.markdown
adds partner blog for the AWS Kendra release - updated a few author bios
n/a
> Partner AWS - Kendra blog & author bio updates

- releases.md
Update 2.5 date on releases page - Maps team found last minute issue, moving to accommodate resolution
n/a
> release page update

- _events/2023-0124-finding-the-right-things.markdown
- _events/2023-0205-opensearch-at-fosdem23 copy.markdown
Signed-off-by: David Tippett <dtip@amazon.com>
Added pages for the Data Ops Poland and FOSDEM event. 
N/A
> Added events pages for FOSDEM and Data Ops Poland

- _community_projects/pgsync.md
- https:/github.com/toluaina/pgsync/blob/main/README.md
Signed-off-by: toluaina <toluaina@hotmail.com>
- add PGSync as a new community project
> Adds new community project

- _artifacts/opensearch-2.5/arm64/opensearch-2.5.0-linux-arm64-deb.markdown
> Download pages for 2.5.0 release

- releases.md
Update to the 2.5.0 release date
N/A
> Release page update - 2.5.0 date pushed

- _posts/2023-01-24-opensearch-2-5-is-live.md
Release announcement for 2.5.0
n/a
> 2.5.0 Release Blog

- _posts/2023-01-24-opensearch-2-5-is-live.md
> 2.5.0 blog edit

- _herobanners/2.5.0-released.md
Signed-off-by: Nate Boot <nateboot@amazon.com>
Adds one more hero banner to announce the release of 2.5.0. Links to David Tippet's blog. 
No issue made, although could technically be considered part of #1166 
> Adding 2.5.0 release announcement hero banner.

- _artifacts/opensearch-1.3/arm64/opensearch-1.3.8-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.8-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.8-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.8-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.8-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.8-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.8-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.8-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.8-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.8-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.8-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.8-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.8-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.8-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.8-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.8-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.8-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.8-windows-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.8-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.8-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.8-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.8-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.8-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.8-windows-x64.markdown
- _artifacts/opensearch-1.3/x86/opensearch-1.3.8-freebsd-x86.markdown
- _versions/2023-02-02-opensearch-1.3.8.markdown
Builds download pages for the 1.3.8 release
n/a
> Download pages for 1.3.8

- _authors/karanas.markdown
- _authors/krisfreedain.markdown
- _posts/2023-02-02-opensearch-newsletter-vol1-issue1.markdown
> Minor edits on blog post and author profiles

- _posts/2023-01-24-opensearch-2-5-is-live.md
I noticed this post was using `metadata_keywords` but the other pages were using `meta_keywords`. I'm not sure if it matters. The whole reason I found this is because I was adding these for my review in #1314. It should help other authors to have consistent values for examples.
N/A
> Use meta_keywords on OpenSearch 2.5 post.

- _posts/2023-01-23-OpenSearch-Flink-Connector.markdown
minor edit to image path in Apache Flink blog post
n/a
> blog image edit

- _authors/mshyani.markdown
Signed-off-by: Fanit Kolchina <kolchfa@amazon.com>
This PR fixes the linkedin link for Milind
> Fixed linkedin link for an author in Semantic blog

- _data/alert.yml
- _events/2023-0306-dev-triage-security.markdown
- _events/2023-0313-dev-triage-security.markdown
- _events/2023-0314.markdown
- _events/2023-0320-dev-triage-security.markdown
- _events/2023-0327-dev-triage-security.markdown
- _events/2023-0328.markdown
- _events/2023-0403-dev-triage-security.markdown
- _events/2023-0410-dev-triage-security.markdown
- _events/2023-0411.markdown
- _events/2023-0417-dev-triage-security.markdown
- _events/2023-0424-dev-triage-security.markdown
- _events/2023-0425.markdown
Events pages for March & April - Community Meetings & Security Dev Triage
n/a
> March April Events

- _community_projects/apache-flink-opensearch.md
Coming from @brijos , adding Apache Flink OpenSearch connector to community projects
N/A
> Add Apache Flink OpenSearch connector to community projects

- _community_projects/apache-flink-opensearch.md
- _layouts/versions.html
Fix repeating signatures in downloads
https://github.com/opensearch-project/project-website/pull/1370
> Quick fix to the download pages

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/partner_information.md
- _events/2023-0307-awsopensearch-unplugged.markdown
New issue template for enhanced partner pages
New partner event
n/a
> New issue template & event page

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/partner_information.md
- MAINTAINERS.md
- _events/2023-0307-awsopensearch-unplugged.markdown
- _layouts/versions.html
Add Fanit Kolchina as a maintainer
New issue template & event page
https://github.com/opensearch-project/project-website/pull/1335
https://github.com/opensearch-project/project-website/pull/1373
> New maintainer, new issue template, new event page

- _posts/2023-02-24-OpenSearch-Partner-Highlight-Searchium-text-vs-vector.md
new partner highlight blog
n/a
> Searchium partner blog

- _posts/2023-02-24-OpenSearch-Partner-Highlight-Searchium-text-vs-vector.md
- _versions/2023-01-24-opensearch-2.5.0.markdown
Searchium partner blog
PR https://github.com/opensearch-project/project-website/pull/1378
> Searchium partner highlight blog

- _events/2023-0510-devoxxuk.markdown
Add information about session "Using Apache Kafka and OpenSearch to explore Mastodon" at DevoxxUK in London
> Add info on "Using Apache Kafka and OpenSearch to explore Mastodon" session

- _artifacts/opensearch-2.6/arm64/opensearch-2.6.0-min-linux-arm64.markdown
> 2.6.0 Download pages2

- Gemfile
- Gemfile.lock
- _posts/2023-02-28-introducing-opensearch-2-6.md
Blog post announcing release of OpenSearch 2.6.0
https://github.com/opensearch-project/project-website/issues/1369
> 2023 02 28blog

- _posts/2023-02-07-Announcing-Data-Prepper-2.1.0.md
The blog post for announcing Data Prepper 2.1.0
Co-authors:
@asifsmohammed
@kkondaka
Resolves #1303
> Created the blog post announcing Data Prepper 2.1.0. #1303

- _authors/apasun.markdown
> Revise Aparna bio

- .github/ISSUE_TEMPLATE/newsletter.md
- _events/2023-0323-fluent-community.markdown
- _events/2023-0406-fluent-community.markdown
- _events/2023-0424-haystack-us-2023.markdown
Newsletter issue template 
fixes for a couple of event submissions
New + 
PR
https://github.com/opensearch-project/project-website/pull/1466
https://github.com/opensearch-project/project-website/pull/1436
> Newsletter issue template & events fixes

- _posts/2023-01-11-similar-document-search.md
We released Shunsuke's translated article on similar document search without back linking to the original. This PR remedies that. 
N/A
> Added backlinking for similar document search to original in Japanese.

- _events/2023-0406-dev-integrations-apache-spark.markdown
- _events/2023-0420-dev-integrations-apache-spark.markdown
- _events/2023-0504-dev-integrations-apache-spark.markdown
- _events/2023-0518-dev-integrations-apache-spark.markdown
Added event pages for upcoming dev planning meetings
n/a
> Event pages for Integrations and Apache Spark dev meetings

- _posts/2023-03-30-semantic-science-benchmarks.md
Changed the link to the model.
N/A
> Replace the model link

- _config.yml
small fix to _config.yml to resolve URL
Tiny (single character) issue introduced in https://github.com/opensearch-project/project-website/pull/1403
> Partner URL fix

- _config.yml
Another small fix for the partner pages
n/a
> Partner URL fix2

- _config.yml
Partner URL fix2
missing .html
PR https://github.com/opensearch-project/project-website/pull/1489
> Last fix for new partner pages

- CODEOWNERS
This change adds a codeowners file and baselines the maintainers. 
resolves #1354
> Baselining Maintainers and adding codeownwers. 

- _posts/2023-03-30-semantic-science-benchmarks.md
Minor formatting update for the semantic science blog.
> Update format for semantic science blog

- releases.md
Updated the release and freeze date for 2.7
N/A
> Updated the release and freeze date for 2.7

- _sass/_style.scss
- releases.md
> Updated Release Dates 2.7

- _layouts/default.html
- _sass/_opensearch.scss
Adds a class for defining a border and shadow which is then applied by default to blog posts.
> Adds default image styling to blog posts

- slack.markdown
Fixing slack join link as they expire
N/A
> Upating Slack Link

- _posts/2023-04-19-Announcing-Data-Prepper-2.2.0.md
- releases.md
Releases page update 
PR https://github.com/opensearch-project/project-website/pull/1545
> Push changes to Releases page live

- _events/2023-0501-dev-triage-security.markdown
- _events/2023-0508-dev-triage-security.markdown
- _events/2023-0509.markdown
- _events/2023-0515-dev-triage-security.markdown
- _events/2023-0522-dev-triage-security.markdown
- _events/2023-0523.markdown
- _events/2023-0529-dev-triage-security.markdown
- _events/2023-0601-dev-integrations-apache-spark.markdown
- _events/2023-0605-dev-triage-security.markdown
- _events/2023-0606.markdown
- _events/2023-0612-dev-triage-security.markdown
- _events/2023-0615-dev-integrations-apache-spark.markdown
- _events/2023-0619-dev-triage-security.markdown
- _events/2023-0620.markdown
- _events/2023-0626-dev-triage-security.markdown
- _events/2023-0629-dev-integrations-apache-spark.markdown
- _events/2023-0713-dev-integrations-apache-spark.markdown
- _events/2023-0727-dev-integrations-apache-spark.markdown
Community Meeting events through June
Security Dev Triage through June
Apache Spark integrations through July
n/a
> New event pages

- _community_projects/telicent-plugin.md
Adds new community project -> telicent plugin
None
> Adds new community project -> telicent plugin

- OpenSearchCon2023.md
Adds a landing page for our upcoming OpenSearchCon, 2023. 
I don't think there is one. 
> Save the Date for OpenSearchCon 2023!

- _events/2023-0523.markdown
- _events/2023-0606.markdown
- _events/2023-0620.markdown
Fixing my own mistaken links in a couple new events pages I just built. 
n/a
> Events agenda link fixes

- OpenSearchCon2023.md
Adds permalink, meta_description and meta_keywords.
> Permalink and meta_description,meta_keywords. For luck.

- _events/2023-0504-dev-officehours-dashboards.markdown
- _events/2023-0518-dev-officehours-dashboards.markdown
- _events/2023-0601-dev-officehours-dashboards.markdown
- _events/2023-0615-dev-officehours-dashboards.markdown
> Update meetup links for upcoming OpenSearch Dashboards office hours 

- _posts/2023-05-04-segment-replication.md
Fix typo in segment replication blog
> Fix typo in segment replication blog

- _posts/2023-05-04-segment-replication.md
- verify-signatures.markdown
> Segrep blog typo fix

- slack.markdown
New invite link for the Slack page
Existing link expired 
> Update Slack invite link

- _includes/artifact_tree.html
- _layouts/homepage.html
- _layouts/lines.html
- _layouts/versions.html
- _plugins/version-sort-filter.rb
- downloads.html
- versions/index.html
Fix version sorting
* This is a first pass that only honors the numeric portions; the logic has to be modified to honor PEP 440.
> Fix version sorting

- opensearchcon2023-cfp.html
> Forgot to remove a colon

- opensearchcon2023-cfp.html
Changing cfp from papers to presentations
N/A
> Changing cfp from papers to presentations

- _posts/2023-05-18-call-for-presentations-bring-your-ideas-to-opensearchcon-2023.md
Provides a quick edit to sanitize a sentence.
N/A
> Quick copy edit re opensearchcon blog.

- _posts/2023-05-18-call-for-presentations-bring-your-ideas-to-opensearchcon-2023.md
> open source instead of open search

- _posts/2023-05-18-call-for-presentations-bring-your-ideas-to-opensearchcon-2023.md
Last minute phrase change for the CFP blog. 
N/A
> Blog phrasing change.

- _posts/2023-05-18-call-for-presentations-bring-your-ideas-to-opensearchcon-2023.md
Adding location information to OpenSearchCon blog
N/A
> Adding location information to OpenSearchCon blog

- opensearchcon2023-cfp.html
Added the following: 
- Backlink to previous year conference talks
- More information about the date of the conference at the top. 
N/A
> Updating with more information about the conference

- _data/top_nav.yml
- opensearchcon2023-cfp.html
Earlier edits to CFP page got clobbered.
Adding nav menu entries for OpenSearchCon
> CFP page edits and entries in the top nav.

- _posts/2023-05-18-call-for-presentations-bring-your-ideas-to-opensearchcon-2023.md
- opensearchcon2023-cfp.html
Extends the OpenSearchCon CFP deadline
N/A
> Extending CFP Deadline

- _posts/2023-06-01-opensearch-dashboards-community-member-insights.md
Completes #1461 by publishing the blog itself. 
#1461 
> #1461 - Community Insights blog.

- _posts/2023-05-25-Announcing-Data-Prepper-2.3.0.md
Announcing Data Prepper 2.3.0
Resolves #1586 
Resolves #1586 
- [X ] Commits are signed per the DCO using --signoff
> Announcing Data Prepper 2.3.0

- _partners/improving.md
Updated the Improving partner's website page link to reflect their new website.
> Updated Improving partner page website link

- _posts/2023-05-25-Announcing-Data-Prepper-2.3.0.md
Update contributor names and add a link to add_entries
- [ X] Commits are signed per the DCO using --signoff
> Update contributor names and add a link to add_entries

- benchmarks/index.md
Added category selection link above the dashboards to select specific dashboard.
NA
> Add category selection to benchmarking page

- _events/2023-0627.markdown
- _events/2023-0711.markdown
- _events/2023-0725.markdown
- _events/2023-0808.markdown
- _events/2023-0822.markdown
Edit 6/20 CM meeting to 6/27
New Community Meeting events for July & August. 
N/A
> New Community Meetings

- _events/2023-0611-cfp-workshop.markdown
Updating the commit to have a padded zero in the front of the hour. 
N/A
> Adding Zero paddin to hours

- _posts/2023-06-01-opensearch-dashboards-community-member-insights.md
The excerpt for this posting has markdown in it. We could maybe replace it with pure HTML, but we're removing the markdown from the excerpt for now. 
N/A
> Removing markdown from excerpt front matter.

- _data/top_nav.yml
- robots.txt
Link to new Performance Benchmarks page in the top-nav
modify robots.txt file to allow crawlers on that page
n/a
> Link to Benchmarks page

- .github/workflows/link-checker.yml
> Fix link checker workflow

- .github/vale/styles/OpenSearch/Spelling.yml
- .github/vale/styles/Vocab/OpenSearch/Products/accept.txt
- .github/vale/styles/Vocab/OpenSearch/Words/accept.txt
Add words to vale vocabulary and update error spelling message.
> Add words to vale vocabulary and update error spelling message.

- opensearchcon2023-cfp.html
Closing the OpenSearchCon CFP with some new wording and a link to register. 
N/A
> Closing the OpenSearchCon CFP

- benchmarks/index.md
Add link to view open performance issues across OpenSearch GitHub organization
NA
> Add link to view open performance issues

- _posts/2023-06-26-exploring-opensearch-vector-database-capabilities.md
Add AWS partner highlight blog post on vector database capabilities
N/a
> Add AWS partner highlight post to blog

- _events/2023-0628-search-relevance-triage-backlog.markdown
- _events/2023-0712-search-relevance-triage-backlog.markdown
- _events/2023-0726-search-relevance-triage-backlog.markdown
- _events/2023-0809-search-relevance-triage-backlog.markdown
Add events for new Search Relevance team dev meetings
n/a
> Search team events

- _artifacts/opensearch-1.3/arm64/opensearch-1.3.11-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.11-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.11-linux-arm64-deb.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.11-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.11-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.11-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.11-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.11-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.11-linux-arm64-deb.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.11-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.11-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.11-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.11-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.11-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.11-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.11-linux-x64-deb.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.11-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.11-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.11-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.11-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.11-windows-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.11-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.11-linux-x64-deb.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.11-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.11-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.11-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.11-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.11-windows-x64.markdown
- _artifacts/opensearch-1.3/x86/opensearch-1.3.11-freebsd-x86.markdown
- _versions/2023-06-29-opensearch-1.3.11.markdown
Download pages to support the 1.3.11 release - expected 6/29
n/a
> Download pages for 1.3.11 release

- _posts/2023-05-18-call-for-presentations-bring-your-ideas-to-opensearchcon-2023.md
Mods existing blog to indicate closure of CFP window.
#1738 
> Indicating closure of CFP window to resolve #1738

- _events/2023-0710-dev-triage-security.markdown
- _events/2023-0717-dev-triage-security.markdown
- _events/2023-0724-dev-triage-security.markdown
- _events/2023-0728-generative-ai-brainstorm.markdown
- _events/2023-0731-dev-triage-security.markdown
- _events/2023-0807-dev-triage-security.markdown
- _events/2023-0814-dev-triage-security.markdown
- _events/2023-0821-dev-triage-security.markdown
- _events/2023-0828-dev-triage-security.markdown
- _events/2023-0904-dev-triage-security.markdown
- _events/2023-0911-dev-triage-security.markdown
- _events/2023-0918-dev-triage-security.markdown
- _events/2023-0925-dev-triage-security.markdown
- _includes/feedback.html
New events pages for the security team & survey update for front page
n/a
> New events & survey

- _community_projects/stormcrawler.markdown
Fixes syntax error in the markdown for the stormcrawler community project
Allows for the Community Project tile for Stormcrawler to correctly render.
None open
> Fixes syntax error in the markdown for the stormcrawler community project

- _events/2023-0718-2-9-release-meetings.markdown
Building out a page to house the 2.9.0 release series
n/a
> 2.9 open release event

- _partners/telicent.md
Fixes typo + add link to custom docker image
> Fixed typo for Telicent + added link to dockerhub

- _posts/2023-06-15-registration-for-opensearchcon-2023-is-now-open.md
Changing phrasing for #1775 
Resolves #1775 
> Fixes #1775

- _authors/jimishsh.markdown
- _authors/prabarch.markdown
> Fix file formatting for two authors

- _events/2023-0725-efficient-vector-search-opensearch.markdown
Adding an event to the event page
N/A
> Add 2023-0725-efficient-vector-search-opensearch event

- _artifacts/data-prepper/data-prepper-2.1.1-docker-x64.markdown
- _artifacts/data-prepper/data-prepper-2.2.1-docker-x64.markdown
- _artifacts/data-prepper/data-prepper-2.3.0-docker-x64.markdown
- _artifacts/data-prepper/data-prepper-2.3.1-docker-x64.markdown
This fixes some issues with Data Prepper Docker YAML files. The formatting was off, which resulted in incorrect YAML/data.
N/A
> Fixes some Data Prepper Docker artifact YAML files

- _events/2023-0718-2-9-release-meetings.markdown
- releases.md
Edits to the Releases page and 2.9 Release Meeting Event page
n/a
> Edits to the 2.9 release dates

- _events/2023-0718-2-9-release-meetings.markdown
Update to the 2.9 meeting series event
n/a
> Event update

- _events/2023-0718-2-9-release-meetings.markdown
- opensearchcon2023-cfp.html
Event update
https://github.com/opensearch-project/project-website/pull/1793
> Pushing updates to the 

- .pre-commit-config.yaml
> Adding simple precommit hooks

- _events/2023-0807-dev-triage-security.markdown
> Missed a date sorry!

- _events/2023-0718-2-9-release-meetings.markdown
- _events/2023-0724-dev-triage-security.markdown
- _events/2023-0725.markdown
- _events/2023-0726-search-relevance-triage-backlog.markdown
- _events/2023-0727-dev-integrations-apache-spark.markdown
- _events/2023-0728-generative-ai-brainstorm.markdown
- _events/2023-0731-dev-triage-security.markdown
> Event UTC offset correction.

- slack.markdown
> Slack invite link update

- benchmarks/index.md
Add index compression benchmarking dashboards to opensearch.org/benchmarks webpage
NA
> Add index compression benchmarking dashboard

- _herobanners/0-2.9.0-released.md
> Not getting anything right today. Sorry.

- _posts/2023-07-25-introducing-extensions-for-opensearch.md
> Fix formatting in extensions blog post

- _posts/2023-07-25-introducing-extensions-for-opensearch.md
> Remove highlighter specification from extensions blog post

- _community_projects/langchain.md
Added LangChain that supports OpenSearch since https://github.com/langchain-ai/langchain/pull/1191 and https://github.com/langchain-ai/langchain/pull/8256.
> Added LangChain community project.

- .github/vale/styles/OpenSearch/HeadingCapitalization.yml
- .github/vale/styles/OpenSearch/SignatureV4.yml
- .github/vale/styles/OpenSearch/SubstitutionsError.yml
- .github/vale/styles/OpenSearch/TableHeadings.yml
- .github/vale/styles/Vocab/OpenSearch/Plugins/accept.txt
- .github/vale/styles/Vocab/OpenSearch/Products/accept.txt
- .github/vale/styles/Vocab/OpenSearch/Words/accept.txt
- .vale.ini
- _posts/2023-07-06-optimize-opensearch-index-shard-size.markdown
Add a sigv4 rule and more words to style workflow
> Add a sigv4 rule and more words to style workflow

- _authors/zhujiaxiang.markdown
Update peterzhuamazon (zhujiaxiang) author information on opensearch.org
> Update peterzhuamazon (zhujiaxiang) author information on opensearch.org

- releases.md
Update the release dates and release process for minor versions
NA
> Update the release process and dates for OpenSearch  minor release

- releases.md
Fixing the EOL date for 1.x
NA
[X] Commits are signed per the DCO using --signoff
> Fix EOL date

- _events/2023-0718-2-9-release-meetings.markdown
Adding meeting for the 2.9.0 retro
n/a
> 2.9.0 retro

- _posts/2023-08-01-personas-framework.md
Takes intro title out of the first paragraph, and moves the date so that it shows up on the top of the list of blogs. 
> Quick edit to Aparna's blog.

- _community_projects/opsgpt.md
> Update opsgpt.md with icon link

- _artifacts/opensearch-1.3/arm64/opensearch-1.3.12-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.12-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.12-linux-arm64-deb.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.12-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.12-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.12-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.12-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.12-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.12-linux-arm64-deb.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.12-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.12-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.12-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.12-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.12-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.12-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.12-linux-x64-deb.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.12-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.12-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.12-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.12-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.12-windows-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.12-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.12-linux-x64-deb.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.12-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.12-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.12-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.12-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.12-windows-x64.markdown
- _artifacts/opensearch-1.3/x86/opensearch-1.3.12-freebsd-x86.markdown
- _versions/2023-08-10-opensearch-1.3.12.markdown
Download pages to support the 1.3.12 release, expected on August 10
n/a
> Download pages for 1.3.12 release

- slack.markdown
> Updated Slack invite link

- _events/2023-0816-search-relevance-triage-backlog.markdown
- _events/2023-0823-search-relevance-triage-backlog.markdown
- _events/2023-0830-search-relevance-triage-backlog.markdown
- _events/2023-0906-search-relevance-triage-backlog.markdown
- _events/2023-0913-search-relevance-triage-backlog.markdown
- _events/2023-0920-search-relevance-triage-backlog.markdown
- _events/2023-0927-search-relevance-triage-backlog.markdown
- _events/2023-1004-search-relevance-triage-backlog.markdown
- _events/2023-1011-search-relevance-triage-backlog.markdown
- _events/2023-1018-search-relevance-triage-backlog.markdown
- _events/2023-1025-search-relevance-triage-backlog.markdown
- _posts/2022-02-25-roadmap-proposal.md
Search relevance events through October & minor edit to old release proposal blog
n/a
> Search events & blog edit

- _data/top_nav.yml
Adds speaker & session links to top mav
n/a
> OpenSearchCon top nav

- _posts/2023-08-01-personas-framework.md
Minor edit to ensure clickable hyperlinks in 'personas-framework' blog
N/A
> minor blog edit

- _speaker_sessions/aflynn_session.md
- _speaker_sessions/ajambu_session.md
- _speaker_sessions/astern_session.md
- _speaker_sessions/bnauheimer_session.md
- _speaker_sessions/byucel_session.md
- _speaker_sessions/dvenable_session.md
- _speaker_sessions/gbafna_session.md
- _speaker_sessions/irakhmanberdiyev_session.md
- _speaker_sessions/keynote_session.md
- _speaker_sessions/khamric_session.md
- _speaker_sessions/mmammo_session.md
- _speaker_sessions/pmprasad_session.md
- _speaker_sessions/ssingh_session.md
- _speaker_sessions/vborkar_session.md
Fixed some capitalization on the session pages
n/a
> OpenSearchCon session capitalization fix

- _posts/2023-05-16-Discontinuing-custom-Logstash-distribution.md
Updates the blog post for the custom Logstash distribution to include the date of the last release.
N/A
> Provides updated discontinuation date for the custom Logstash distribution

- _events/2023-0825-dev-triage-ml-commons.markdown
- _events/2023-0905-community-meeting.markdown
- _events/2023-0919-community-meeting.markdown
- _events/2023-1003-community-meeting.markdown
- _events/2023-1017-community-meeting.markdown
- _events/2023-1031-community-meeting.markdown
Community meetings & first ml-commons dev triage meeting
N/A
> Community Meetings & ml-commons meeting

- _events/2023-0901-dev-triage-ml-commons.markdown
- _events/2023-0915-dev-triage-ml-commons.markdown
- _exhibitors/aiven.md
ml-commons triage meetings & additional exhibitor
n/a
> Events & exhibitor

- _posts/2023-08-28-Announcing-Data-Prepper-2.4.0.md
A blog post announcing the release of Data Prepper 2.4.0
Resolves #1854
> 1854 data prepper 2.4.0 announcement blog

- _posts/2023-08-23-dashboards-usability-snapshot.md
Adds new blog about usability snapshot; fixes rebase problems caused in PR #1878; closed #1878 and opened this PR; tech, doc, and editorial reviews approved under #1878.  
> Add new blog about usability snapshot

- _posts/2023-08-23-dashboards-usability-snapshot.md
Usability snapshot blog had a june date. Fixing to aug 23. 
> Fixing blog date.

- releases.md
Minor issue with change log area formatting
n/a
> Fix minor formatting on releases page

- _posts/2023-08-23-dashboards-usability-snapshot.md
> I picked the wrong date. I should have asked.

- _authors/iskanderrakhman.markdown
- _posts/2023-09-05-Receive-mentorship-from-Amazon-engineers-and-accelerate-your-career-in-Tech.md
Wrong author shortname referred to in blog.  
> Updating Iskander's blog and author profile.

- releases.md
One more change to the RC date on 2.10
n/a
> Release date update

- _speakers/chenkle.md
- events/opensearchcon/unconference/index.md
Adding speaker page for Charlotte as well as adding to the Unconference lineup 
n/a
> Unconference edits

- _conference_workshops/when_life_hands_you_data_grab_open_search.md
Fix query DSL link in workshop page
> Fix link in workshop page

- releases.md
Tiny edit to the releases page
n/a
> small release edit

- slack.markdown
> Updated Slack Link

- _posts/2023-09-18-opensearch-security-a-testament-to-our-commitment.md
Blog post for the independent security audit
n/a
> Security audit post

- _events/2023-0925-2-10-release-meetings copy.markdown
> 2.10 release meetings

- _events/2023-0925-2-10-release-meetings copy.markdown
- _posts/2023-09-18-opensearch-security-a-testament-to-our-commitment.md
2.10 release meetings
https://github.com/opensearch-project/project-website/pull/2008
> Push out release meeting

- _events/2023-0925-2-10-release-meetings.markdown
Small edit to 2.10 release meeting
n/a
> 2.10 rel event update

- _events/2023-0925-2-10-release-meetings copy.markdown
- _events/2023-0925-2-10-release-meetings.markdown
2.10 rel event update
https://github.com/opensearch-project/project-website/pull/2010
> push out 2.10 release meeting edits

- _events/2023-0925-2-10-release-meetings.markdown
2.10 rel event update 
https://github.com/opensearch-project/project-website/pull/2013
> Push out edits to the 2.10 release meeting

- _sass/_redesign-conference.scss
- _speaker_sessions/jhandler_session.md
Adds the conference session for speaker Jon Handler.
Adjusts the padding of the session speaker card.
> Adds Jon Handler session; adjusts session speaker card padding

- CODE_OF_CONDUCT.md
- _events/2023-0925-2-10-release-meetings.markdown
- _sass/_redesign-conference.scss
- _speaker_sessions/jhandler_session.md
Updates our code of conduct and adds one last session to the conference page. Better late than never.
> Code of Conduct and Conference Page update. 

- _events/2023-0925-2-10-release-meetings.markdown
Adding another go/no-go for tomorrow
n/a
> small edit to 2.10 release event

- _artifacts/opensearch-1.3/arm64/opensearch-1.3.13-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.13-freebsd-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.13-linux-arm64-deb.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.13-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.13-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.13-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-1.3.13-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.13-docker-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.13-linux-arm64-deb.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.13-linux-arm64-rpm.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.13-linux-arm64-yum.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.13-linux-arm64.markdown
- _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.13-min-linux-arm64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.13-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.13-freebsd-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.13-linux-x64-deb.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.13-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.13-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.13-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.13-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-1.3.13-windows-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.13-docker-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.13-linux-x64-deb.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.13-linux-x64-rpm.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.13-linux-x64-yum.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.13-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.13-min-linux-x64.markdown
- _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.13-windows-x64.markdown
- _artifacts/opensearch-1.3/x86/opensearch-1.3.13-freebsd-x86.markdown
- _versions/2023-09-21-opensearch-1.3.13.markdown
Download pages to support the 1.3.13 release, expected on September 21
N/A
> 1.3.13 Release download pages

- events/opensearchcon/unconference/index.md
> unconference edit

- _sass/_redesign-conference.scss
- events/opensearchcon/sessions/index.html
Add legend to session schedule
> Add legend to session schedule

- _authors/osci_2023/vchrombie.markdown
> [OSCI-23] Add `vchrombie` as an author

- _authors/osci_2023/maximilian.markdown
Added myself as a new OSCI author to the repo
> Added MaximilianMeiler to OSCI authors

- _authors/osci_2023/anthony-mccrovitz.markdown
Adds anthony-mccrovitz as osic author to the repo
> [OSCI] add new osic author anthony-mccrovitz

- _authors/osci_2023/yeraassyl.markdown
Added yeraassyl as author for osci_2023
Contribute my first pr
> [OSCI] Add new osci author yeraassyl

- _authors/osci_2023/samuelorji.markdown
> [OSCI] Add new author Samuel Orji

- _authors/osci_2023/johnathonbowers.markdown
[This PR adds a new OSCI author markdown file for johnathonbowers]
[]
> [OSCI] Add new OSCI author johnathonbowers

- _authors/osci_2023/rblcoder.markdown
Adds rupa as a OSCI author to the repository
> [OSCI] add new osci author rupa

- _authors/osci_2023/Sanjana679.markdown
Adds Sanjana679 as an OSCI author to the repository
> [OSCI] Add new OSCI author Sanjana679

- _authors/osci_2023/nancyjlau.markdown
Adds nancyjlau as a OSCI author to the repository
N/A
> [OSCI] Add new osci author nancyjlau

- _authors/osci_2023/geoffrey1330.markdown
Add Israel Geoffrey as an author
> [OSCI] Add new author Israel Geoffrey

- _authors/ctsai.markdown
- _authors/osci_2023/ctsai.markdown
Add ctsai21 as an author
- [] Commits are signed per the DCO using --signoff
> [OSCI] Add ctsai21 as an author 

- _authors/osci_2023/d-wwwang.markdown
Added OSCI author d-wwwang in new markdown file d-wwwang.markdown
NA
> [OCSI] add new osci author d-wwwang

- _authors/osci_2023/djcarrillo6.markdown
New OSCI author to the repo.
- [ X] Commits are signed per the DCO using --signoff
> [OSCI] Add new OSCI author djcarrillo6

- _authors/osci_2023/prerana.markdown
Adds prerana as a OSCI author to repository.
> [OSCI]Added my name in osci author Prerana

- _authors/osci_2023/sudershan29.markdown
Adding a new file describing the profile for Sudershan29
> [OSCI] Adding New Profile for Sudershan29
