opensearch-project/project-website

_layouts/post.html
(missing `.html` on authors link was causing a 404 error when deployed to s3)
=> fixed issue with deployed site throwing 404

README.md, docker-compose.yml, docker/Dockerfile, docker/run.sh
This PR provides an easy way to setup/serve the site locally using a light way (Docker) instead of dealing with the dependency hell while installing all the dependencies for using Jekyll.
n/a
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
=> Add a possibility to run/serve the site via Docker

_includes/share-buttons.html, _layouts/post.html
Adds social media share links. This PR follows [this guide](https://jekyllcodex.org/without-plugin/share-buttons/) published on jekyllcodex.org. I want to thank jekyllcodex.org for providing this short guide and html page for adding social sharing links.
=> Add social sharing links to blogs

README.md
Noticed that our instructions for installing ruby here are incorrect. RVM is one option to install Ruby (it manages multiple ruby installations), and if we wanted to recommend RVM we would say "install RVM, then install Ruby". But since YMMV with how you like to install Ruby (e.g via rvm or rbenv), then we should have no opinion.
Added automatic TOC, fixed some minor stuff.
=> Fix ruby install instructions

_authors/alolitas.markdown, _authors/amistrn.markdown, _authors/dblock.markdown, _authors/handler.markdown, _authors/kyledvs.markdown, _authors/virajph.markdown, _includes/author_panel.html, _sass/_opensearch.scss
Twitter links have a typo, fixed. Removed `@` which is redundant, even though Twitter redirects.
Added GitHub.
=> Fixed twitter links and added GitHub.

Gemfile.lock, _faqs/03-01-how-can-i-upgrade-a-cluster-with-multiple-nodes-to-opensearch.markdown, _faqs/03-02-how-can-i-upgrade-a-single-node-deployment.markdown, _faqs/03-03-which-versions-of-elasticsearch-oss-and-kibana-can-i-upgrade-from-to-opensearch-and-opensearch-dashboards-directly.markdown, _faqs/03-04-can-i-upgrade-older-versions-of-elasticsearch-oss-and-kibana-to-opensearch-and-opensearch-dashboards.markdown, _faqs/03-05-can-i-upgrade-a-non-oss-cluster.markdown, _faqs/03-06-can-i-upgrade-from-elasticsearch-and-kibana-7.11-or-other-versions-released-after-the-fork.markdown, _faqs/03-07-will-my-odfe-plugins-continue-to-work-after-upgrade.markdown, _faqs/03-08-at-what-point-is-the-upgrade-process-complete.markdown, _faqs/03-09-does-an-upgrade-require-downtime.markdown, _faqs/03-10-can-i-do-a-blue-green-upgrade-with-data-migration.markdown, _faqs/03-11-can-i-install-elasticsearch-xyz-plugin-in-opensearch.markdown, _faqs/03-12-can-i-rollback-an-upgrade-half-way-in-progress-e-g-2-4-nodes-are-running-opensearch.markdown, _faqs/03-13-are-there-any-changes-required-for-my-existing-elasticsearch-clients-to-continue-to-work.markdown, _faqs/03-14-can-i-run-a-heterogeneous-mixed-opensearch-and-elasticsearch-cluster-.markdown, _faqs/03-15-can-i-run-a-heterogeneous-mixed-opensearch-dashboards-and-kibana-cluster-.markdown, _faqs/03-16-is-opensearch-security-enabled-by-default-after-an-upgrade.markdown, _faqs/03-17-what-settings-change-during-the-upgrade.markdown, _faqs/03-18-what-rest-apis-change-during-the-upgrade.markdown, _faqs/03-19-how-do-we-upgrade-or-migrate-secure-or-system-indices.markdown, _faqs/03-20-is-there-binary-compatibility-between-elasticsearch-oss-and-opensearch.markdown, _faqs/03-21-where-can-i-find-more-information-and-track-progress-on-ensuring-backwards-compatibility.markdown, _faqs/03-22-will-kibana-work-on-top-of-opensearch.markdown, _faqs/03-23-i-have-built-a-custom-plugin-for-elasticsearch-will-it-run-without-modification-on-opensearch.markdown, _faqs/03-24-can-i-install-kibana-xyz-plugin-that-only-uses-rest-apis-in-opensearch-dashboards-1.0.markdown, _faqs/03-25-i-have-built-a-custom-visualization-for-kibana-will-it-be-usable-with-opensearch-dashboards-without-modification.markdown, _faqs/03-26-can-opensearch-read-indices-from-previous-versions-of-elasticsearch.markdown, _faqs/03-27-will-the-opensearch-api-change-in-future-versions.markdown
updates the upgrade FAQ section title to specifically say "Upgrading to OpenSearch." _Upgrading_ might be perceived as upgrading from OpenSearch 1.x to 1.y. However, these FAQs are focused upgrading from open source ES and ODFE to OpenSearch.
=> updates the upgrade FAQ section title to be more specific 

samples/docker-compose.yml
Configure docker-compose.yml to have OpenSearch-Dashboards talk to both OpenSearch nodes.
OpenSearch-Dashboards only talk to one of the two hosts 
=> docker-compose.yml sample: post OpenSearch-Dashboard to both OpenSearch nodes

_layouts/fullwidth.html, _sass/_opensearch.scss, _sass/_partners.scss, _sass/_utils.scss, assets/css/output.scss, partners/index.html
These are mainly cosmetic CSS and markup changes to the partners page. I'm keeping the information and hierarchy the same, just adding some visual polish + responsive styles.
=> Visual updates to partners page

_includes/head.html
Signed-off-by: Lorna Mitchell <lornajane@aiven.io>
Adds a few opengraph tags to `head.html`, doesn't include description since it doesn't seem to be set but if there is a description that should be used, I can add that too.
Fixes #132
=> Add title, url, site name and image opengraph tags

_artifacts/opensearch-1.0.0/arm64/opensearch-1.0.0-min-linux-arm64.markdown
makes signature link for opensearch-min download actual signature, not full tarball
=> fixing sig link on arm64

_includes/downloads/opensearch-docker.markdown
Before:
`3. Have a nice coffee while everything is downloading and startup up`
After:
`3. Have a nice coffee while everything is downloading and starting up`
Signed-off-by: Tommy Markley <markleyt@amazon.com>
https://github.com/opensearch-project/project-website/issues/201
=> Fixes typo on Downloads page

README.md, community_projects/index.html
🥳 `staging` is going away. `main` is the new working branch and `prod` = opensearch.org
#57
=> Updates to remove `staging` branch from content

_includes/downloads/opensearch-docker.markdown
Adds instruction to set docker to use a larger amount of ram for the example
#222
=> added 4gb warning to docker compose instructions

authors/index.html, versions/index.html
URLs on [versions](https://opensearch.org/versions/) and [authors](https://opensearch.org/authors/) pages are missing the `.html` suffix; this change fixes them.
=> Fix urls on `/authors` and `/versions`

_config.yml, robots.txt, sitemap-index.xml
Generates a sitemap-index to point to the website sitemap, as well as the docs sitemap. The sitemap-index is then fed to `robots.txt` instead of the website sitemap.
PS, in the process, I merged the 2 `exclude` directives in the config.
=> Sitemap index to include documentation

_layouts/versions.html, artifacts/index.html
This fixes extra `.html`s from URLs on the artifact and download pages for OpenSearch Minimum.
=> Remove extra `.html` from versions and artifacts

_config.yml, _javadocs/1.0.0.markdown, _javadocs/beta-1.markdown, _javadocs/rc-1.markdown, _layouts/javadocs.html, _sass/_style.scss, javadocs/index.html
Moves JavaDocs landing pages out of `/docs` into `/javadocs` where the artifacts actually are.
Makes the landing pages look marginally better.
Also pulled in the `html` backgroud from documentation which will
1. avoid showing white space when content is too short for the screen (like javadocs landing page)
2. avoid showing white space above and below on over scrolls
=> Organize javadocs landing pages

Gemfile, Gemfile.lock, _config.yml, _javadocs/1.0.0.markdown, _javadocs/beta-1.markdown, _javadocs/rc-1.markdown, _layouts/javadocs.html, _sass/_style.scss, downloads.html, javadocs/index.html
Introduces `redirect_from` plugin and add to `downloads.html`. This will gracefully handle typos in incoming URLs like `/downloads` or `/download.html` when in fact the visitor wanted `/downloads.html`.
=> Introduce `redirect_from` plugin and add to `downloads.html`

README.md
Tweaked copyright message on README because of NOTICE file link being missing (ALv2 vs BSD-3 differences accounted for)
#252 
=> fixed copyright due to BSD not having notice file

events/past.html
The past events page does not sort them, making it difficult to locate a precise item (e.g. the last event to access the corresponding collaborative agenda on HackMD).
These changes sort the past events in reverse choronological order.
n/a
=> Improve the listing of past events

_community_projects/open-siem-logstash-parsing.md
This will add Cargill's OpenSIEM repo as one of the tiles on the https://opensearch.org/community_projects/ pages.
N/A
Yep
=> OpenSIEM Community Partner Tile for Community Page

README.md
Adds instructions for using future flag in README when testing blogs published in future
Addresses issue #280
=> Adds instructions on using future flag

_community_projects/diggie.md
Modified Diggie download URL because it is currently a version-specific URL. This leads viewers to our release page so they can find the latest version anytime.
=> Modify Diggie download URL

_posts/2021-09-30-opensearch-py-js-go.markdown
Fixes a link and the npm command to match the npm site info for opensearch-js
=> Update 2021-09-30-opensearch-py-js-go.markdown npm info

_posts/2021-11-05-bwc-testing-for-opensearch.markdown
Signed-off-by: Vacha <vachshah@amazon.com>
Updating the backwards compatibility post introduced in PR #419 according to [comments](https://github.com/opensearch-project/project-website/pull/419#pullrequestreview-798298389).
#428 
=> Updates to backwards compatibility post

README.md, _config.yml, _includes/copy_banner.html, _layouts/default.html, _layouts/homepage.html, _plugins/search-indexer.rb, _sass/_custom-search.scss, _sass/_style.scss, assets/css/output.scss, assets/js/search.js, index.markdown, source.markdown, versions/index.html
* Add a plugin that produces indexible content: This content is fed to OpenSearch and made available via https://search-api.opensearch.org/search
* Add a search text input, identical to the one used on documentation
* Converted some `768px` media queries to `46.25rem` which is `740px` (matching [defaults from just-the-docs](https://pmarsceill.github.io/just-the-docs/docs/utilities/responsive-modifiers/) so the website and docsite appear uniform)
* Set `versions` landing page to `omit_from_search: true`
* Moved the title of `source` from config to the page itself as it was used once and helps simplify indexing
=> Add custom search indexing and UI

_artifacts/opensearch-1.2/arm64/opensearch-1.2.3-docker-arm64.markdown, _artifacts/opensearch-1.2/arm64/opensearch-1.2.3-linux-arm64.markdown, _artifacts/opensearch-1.2/arm64/opensearch-1.2.3-min-linux-arm64.markdown, _artifacts/opensearch-1.2/x64/opensearch-1.2.3-docker-x64.markdown, _artifacts/opensearch-1.2/x64/opensearch-1.2.3-linux-x64.markdown, _artifacts/opensearch-1.2/x64/opensearch-1.2.3-min-linux-x64.markdown, _data/alert.yml, _includes/downloads/data-prepper.html, _posts/2021-12-11-update-to-1-2-1.markdown, _posts/2021-12-16-update-1-2-2.markdown, _posts/2021-12-22-update-1-2-3.markdown, _versions/2021-12-22-opensearch-1.2.3.markdown
* adds v1.2.3
* adds version definition
* Update _versions/2021-12-22-opensearch-1.2.3.markdown
Co-authored-by: Vijayan Balasubramanian <vijayan.balasubramanian@gmail.com>
Signed-off-by: Eli Fisher <elifish@amazon.com>
* Updates Data Prepper description
Signed-off-by: Eli Fisher <elifish@amazon.com>
* Adds 1.2.3 blog
Signed-off-by: Eli Fisher <elifish@amazon.com>
* Fixes 1.2.3 blog blurb
Signed-off-by: Eli Fisher <elifish@amazon.com>
* removes FreeBSD as artifacts aren't released yet and shortens update language.
Signed-off-by: Eli Fisher <elifish@amazon.com>
* adds missing and
Signed-off-by: Eli Fisher <elifish@amazon.com>
* adds missing space
Signed-off-by: …
=> Merging main to prod for V1 2 3 release (#605)

_artifacts/data-prepper/data-prepper-1.2.1-linux-x64.markdown, _artifacts/data-prepper/data-prepper-1.2.1-no-jdk-linux-x64.markdown, _includes/downloads/data-prepper.html, _layouts/versions.html, _versions/2021-07-12-opensearch-1.0.0.markdown, _versions/2021-09-01-opensearch-1.0.1.markdown, _versions/2021-10-05-opensearch-1.1.0.markdown, _versions/2021-11-23-opensearch-1.2.0.markdown, _versions/2021-12-11-opensearch-1.2.1.markdown, _versions/2021-12-16-opensearch-1.2.2.markdown, _versions/2021-12-22-opensearch-1.2.3.markdown, _versions/_2021-12-14-opensearch-1.1.1.markdown
This PR adds Data Prepper archive files for Linux.
Additionally, Data Prepper includes a bundle without an embedded JDK. I took the approach of referring users to the archives directory for this artifact. This is similar to how the OpenDistro Data Prepper download page worked.
N/A
=> Added Data Prepper 1.2.1 archives.

_config.yml
* Without a timezone set in the config file, different environments can result in differing dates.
* With a non-UTC timezone set, unquoted date-time combinations can lead to dates being a day off.
* Using UTC, both the above problems are avoided.
Examples:
* `timezone: "America/Los_Angeles"` in config:
* `date: 2021-11-15 01:01:01` results in "Sun, Nov 14, 2021"
* `date: '2021-11-15 01:01:01'` results in "Mon, Nov 15, 2021"
* `date: 2021-11-15` results in "Mon, Nov 15, 2021"
* `date: '2021-11-15'` results in "Mon, Nov 15, 2021"
* `timezone: "Asia/Vladivostok"` in config:
* `date: 2021-11-15 21:01:01` results in "Tue, Nov 16, 2021"
* `date: '2021-11-15 21:01:01'` results in "Mon, Nov 15, 2021"
* `date: 2021-11-15` results in "Mon, Nov 15, 2021"
* …
=> Normalize timezone across builds

_posts/2021-06-03-my-first-steps-in-opensearch-plugins.markdown
We are removing all jcenter references from our code base, it seems appropriate to also update this blog post as well.  See more details on https://github.com/opensearch-project/opensearch-build/issues/1456.
=> Remove jcenter repository reference in blog post

README.md, _plugins/content-modifier.rb, _plugins/link-checker.rb, _plugins/search-indexer.rb
* Add the ContentModifier plugin to mitigate security risks automatically
* Add reverse tabnabbing mitigation to ContentModifier
* Add execution priority to the existing plugins
* Prevent unnecessary execution of hooks when the Serve command is used and provide a way to override this behavior
* Optimize hook registration
=> Add the ContentModifier plugin to mitigate security risks automatically and prioritize plugins

_posts/2022-02-01-data-prepper-1.2.1-performance-testing.md
Signed-off-by: Taylor Gray <tylgry@amazon.com>
* Adds a link to to the Data Prepper 1.2.1 performance blog post, which takes the reader to a document in the Data Prepper repo for the latest performance test results.
=> Add link to blog post for latest Data Prepper performance test results

MAINTAINERS.md
- Moves Kyle to Emeritus
- Adds Miki, Nick, Kris, Peter and Charlotte as maintainers (present in team, but not in markdown)
n/a
=> updates maintainers to reflect actual members

_artifacts/data-prepper/data-prepper-1.5.0-docker-x64.markdown, _artifacts/data-prepper/data-prepper-1.5.0-linux-x64.markdown, _artifacts/data-prepper/data-prepper-1.5.0-no-jdk-linux-x64.markdown, _versions/2021-07-12-opensearch-1.0.0.markdown, _versions/2021-09-01-opensearch-1.0.1.markdown, _versions/2021-10-05-opensearch-1.1.0.markdown, _versions/2021-11-23-opensearch-1.2.0.markdown, _versions/2021-12-11-opensearch-1.2.1.markdown, _versions/2021-12-16-opensearch-1.2.2.markdown, _versions/2021-12-22-opensearch-1.2.3.markdown, _versions/2022-01-18-opensearch-1.2.4.markdown, _versions/2022-03-17-opensearch-1.3.0.markdown, _versions/2022-03-30-opensearch-1.3.1.markdown, _versions/2022-05-05-opensearch-1.3.2.markdown, _versions/2022-05-26-opensearch-2.0.0.markdown, _versions/2022-06-09-opensearch-1.3.3.markdown, _versions/2022-06-16-opensearch-2.0.1.markdown, _versions/_2021-12-14-opensearch-1.1.1.markdown
* Adds Data Prepper 1.5.0 as a new artifact
* Updates all OpenSearch versions to use Data Prepper 1.5.0 as the version.
N/A
=> Data Prepper 1.5.0 Downloads

_posts/2022-02-25-roadmap-proposal.md
Update 2.1.0 and 1.3.4 dates.
The change to 2.1.0 was necessary because some fit and finish items to snapshot management ran late.  I decided to move the release out to accommodate (and avoid the US 4th of July Holiday).  That meant that 2.1.0 would now overlap with 1.3.4, so moving that out as well. 
N/A
=> Date changes to roadmap

_posts/2022-05-16-opentelemetry-metrics-for-data-prepper.md
Signed-off-by: Shivani Shukla <sshkamz@amazon.com>
- While referring to this [Metrics Ingestion with Data Prepper Blog](https://opensearch.org/blog/technical-post/2022/05/opentelemetry-metrics-for-data-prepper/), I observed the `source` in the Configuration was misconfigured as the trace source instead of the metrics source. This PR updates the source from `otel_trace_source` to the correct `otel_metrics_source`. 
- The updated configuration with `otel_metrics_source` was also tested manually. 
=> Fixes misconfigured source from otel_trace to otel_metrics

_faqs/03-30-does-opensearch-support-downgrades.markdown
Signed-off-by: jeffhuss <jeffhuss@amazon.com>
Added an entry under the FAQ to explain that direct version rollbacks are unsupported by OpenSearch and that users should leverage snapshot + restore after doing a fresh install of the target version.
https://github.com/opensearch-project/documentation-website/issues/436
=> Added FAQ entry to address lack of rollback support

_faqs/01-21-what-tools-do-you-recommend-for-log-aggregation.markdown, _faqs/02-04-does-opensearch-include-forks-of-logstash-and-beats.markdown
Fixes two typos in the FAQ called out in https://github.com/opensearch-project/documentation-website/issues/728
Fixed two typos in questions 1.21 and 2.4
This PR doesn't resolve an issue in and of itself - there will need to be another PR against the documentation-website repo.
=> Fixed typos in FAQ questions 1.21 and 2.4

_posts/2022-05-16-opentelemetry-metrics-for-data-prepper.md
There was a typo in the example metrics pipeline configuration (cf. [1]). It was fixed to provide a working configuration. An appropriate index configuration was added as well.
[1] https://stackoverflow.com/questions/73601327/export-opentelemetry-metrics-to-open-search/73631163
Fixed typo in example configuration for DataPrepper OTLP metrics source.
=> Fix OTel Metrics Source DataPrepper Example

_artifacts/data-prepper/data-prepper-2.0.0-docker-x64.markdown, _artifacts/data-prepper/data-prepper-2.0.0-linux-x64.markdown, _artifacts/data-prepper/data-prepper-2.0.0-no-jdk-linux-x64.markdown, _versions/2021-07-12-opensearch-1.0.0.markdown, _versions/2021-09-01-opensearch-1.0.1.markdown, _versions/2021-10-05-opensearch-1.1.0.markdown, _versions/2021-11-23-opensearch-1.2.0.markdown, _versions/2021-12-11-opensearch-1.2.1.markdown, _versions/2021-12-16-opensearch-1.2.2.markdown, _versions/2021-12-22-opensearch-1.2.3.markdown, _versions/2022-01-18-opensearch-1.2.4.markdown, _versions/2022-03-17-opensearch-1.3.0.markdown, _versions/2022-03-30-opensearch-1.3.1.markdown, _versions/2022-05-05-opensearch-1.3.2.markdown, _versions/2022-05-26-opensearch-2.0.0.markdown, _versions/2022-06-09-opensearch-1.3.3.markdown, _versions/2022-06-16-opensearch-2.0.1.markdown, _versions/2022-07-07-opensearch-2.1.0.markdown, _versions/2022-07-14-opensearch-1.3.4.markdown, _versions/2022-08-11-opensearch-2.2.0.markdown, _versions/2022-09-01-opensearch-1.3.5.markdown, _versions/2022-09-01-opensearch-2.2.1.markdown, _versions/2022-09-14-opensearch-2.3.0.markdown, _versions/_2021-12-14-opensearch-1.1.1.markdown
Signed-off-by: Hai Yan <oeyh@amazon.com>
Prepares for Data Prepper 2.0 release:
- Adds Data Prepper 2.0.0 as a new artifact
- Updates all OpenSearch versions to use Data Prepper 2.0.0 as the version.
N/A
=> Data Prepper 2.0.0 Downloads

_posts/2022-10-10-Announcing-Data-Prepper-2.0.0.md
We are releasing Data Prepper 2.0.0 on Oct 10. This is our announcement blog post.
This requires the bio for @oeyh as supplied in #1067.
N/A
=> Created the blog post announcing Data Prepper 2.0

_posts/2022-10-10-Announcing-Data-Prepper-2.0.0.md, about.markdown, index.markdown
This change moves the Founding Documents from the front page to a section on the About page
n/a
=> Move Founding Documents

MAINTAINERS.md
Following https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#addition to update maintainer list with nominees. The maintainers have voted and agreed to this nomination and the nominee confirmed their interest in becoming co-maintainer.
I would like to maintain we add David Tippet as a maintainer on the project-website. He is a Sr Developer Advocate on the OpenSearch project. Full profile here: https://github.com/dtaivpp
He has helped on a number of
PRs:
https://github.com/opensearch-project/project-website/pulls?q=is%3Apr+dtaivpp+
Issues:
https://github.com/opensearch-project/project-website/issues?q=is%3Aissue+dtaivpp+
And has assisted me with input on code, Jekyll questions a number of times.
N/A
- [ x] Commits are …
=> Add @dtaivpp as maintainer

_events/2022-1017-dev-triage-security.markdown
Adds an events page to the site for Monday's trial-run public triage and backlog development meeting
N/A
=> Security Event page

_artifacts/data-prepper/data-prepper-2.0.1-docker-x64.markdown, _artifacts/data-prepper/data-prepper-2.0.1-linux-x64.markdown, _artifacts/data-prepper/data-prepper-2.0.1-no-jdk-linux-x64.markdown, _versions/2021-07-12-opensearch-1.0.0.markdown, _versions/2021-09-01-opensearch-1.0.1.markdown, _versions/2021-10-05-opensearch-1.1.0.markdown, _versions/2021-11-23-opensearch-1.2.0.markdown, _versions/2021-12-11-opensearch-1.2.1.markdown, _versions/2021-12-16-opensearch-1.2.2.markdown, _versions/2021-12-22-opensearch-1.2.3.markdown, _versions/2022-01-18-opensearch-1.2.4.markdown, _versions/2022-03-17-opensearch-1.3.0.markdown, _versions/2022-03-30-opensearch-1.3.1.markdown, _versions/2022-05-05-opensearch-1.3.2.markdown, _versions/2022-05-26-opensearch-2.0.0.markdown, _versions/2022-06-09-opensearch-1.3.3.markdown, _versions/2022-06-16-opensearch-2.0.1.markdown, _versions/2022-07-07-opensearch-2.1.0.markdown, _versions/2022-07-14-opensearch-1.3.4.markdown, _versions/2022-08-11-opensearch-2.2.0.markdown, _versions/2022-09-01-opensearch-1.3.5.markdown, _versions/2022-09-01-opensearch-2.2.1.markdown, _versions/2022-09-14-opensearch-2.3.0.markdown, _versions/_2021-12-14-opensearch-1.1.1.markdown
Releases Data Prepper 2.0.1.
The maintainers plan to release 2.0.1 today. This PR includes the changes for it. Please merge after the release has completed.
N/A
=> Release Data Prepper 2.0.1

_posts/2022-10-24-public-jenkins.markdown
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
The image on the blog post https://opensearch.org/blog/community/2022/10/public-jenkins/ appears to be broken. This change fixes that
=> Fix image on the build system blog post

_posts/2022-10-05-one-million-enitities-in-one-minute.markdown
Signed-off-by: Naarcha-AWS <naarcha@amazon.com>
Fixes error where Gravitron should be Graviton in blog. Also changes wording of a sentence according Sudipto's suggestion.
=> Change Gravitron to Graviton

_artifacts/data-prepper/data-prepper-1.5.2-docker-x64.markdown, _artifacts/data-prepper/data-prepper-1.5.2-linux-x64.markdown, _artifacts/data-prepper/data-prepper-1.5.2-no-jdk-linux-x64.markdown
This PR adds Data Prepper 1.5.2. This release is not linked to any OpenSearch version because 2.0.1 is preferable.
N/A
=> Release Data Prepper 1.5.2

_events/2022-1107-dev-triage-security.markdown, _events/2022-1114-dev-triage-security.markdown, _events/2022-1121-dev-triage-security.markdown, _events/2022-1128-dev-triage-security.markdown, _events/2022-1205-dev-triage-security.markdown, _events/2022-1212-dev-triage-security.markdown, _events/2022-1219-dev-triage-security.markdown
Adds event pages for upcoming Security meetings through Dec 19th
n/a
=> Security triage and backlog meetings

_includes/head.html, _posts/2022-03-09-fine-dining-for-indices.md, _posts/2022-07-20-content-compass.md
Signed-off-by: Nate Boot <nateboot@amazon.com>
Alters `_includes/head.html` to include logic to use `meta_keywords` and `meta_description` as the page's meta keywords and meta description respectively. Blog publishers should be required to include these pieces of front matter going forward, without exception. 
#1129 
=> Allowing for frontmatter-defined meta_description and meta_keyword.

_layouts/homepage.html
Signed-off-by: Michael Zhou <mizho@alumni.upenn.edu>
Displays the latest 1.x line version next to the latest 2.x line version on the website homepage
#971 
=> Display latest 1.x version next to latest 2.x version

releases.md
Rearrange the releases page to reflect that we are now in the year 2023. Puts the 2022 release schedule under a new "Release History" section.
#1264 
=> Rearrange releases page to reflect the year 2023

_layouts/versions.html
Some of the options on the downloads page showed repeated signature verification indicators.
fixes #1128
=> Fix repeating signatures in downloads

MAINTAINERS.md
from @elfisher's nomination email:  
I would like to nominate Fanit Kolchina as a maintainer on the [project-website](https://github.com/opensearch-project/project-website) repo. Fanit’s github profile can be found here: [https://github.com/kolchfa-aws](https://github.com/kolchfa-aws?tab=overview&from=2022-09-01&to=2022-09-30)
Fanit has helped contribute multiple blogs and is a regular reviewer of blogs working with authors to ensure a high quality bar of writing. E.g:
https://github.com/opensearch-project/project-website/pull/1195
https://github.com/opensearch-project/project-website/pull/987
I believe she will be a welcomed maintainer to this group because I believe she will be an even more active participant and will be able to be more …
=> Add Fanit Kolchina as a maintainer

_data/alert.yml
Turning off the top 2.6 alert on the main page
n/a
=> 2.6 alert off

_events/2023-0426-rta-sumit.markdown
I am going to give a lecture at RTA-Summit 2023 in San Francisco in April regarding upgrading from Elasticsearch to OpenSearch.
It would be great to have the details posted on the site in case anyone from the community is going or wants to meet up in SF. 
=> adding event details for RTA-Summit 2023 opensearch talk

MAINTAINERS.md
Following https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#addition to update maintainer list with nominees. The maintainers have voted and agreed to this nomination and the nominee confirmed their interest in becoming co-maintainer.
Detail from nomination:
I would like to maintain we add Nate Boot as a maintainer on the project-website. He is a Developer Advocate on the OpenSearch project. Full profile here: https://github.com/nateynateynate  
He has helped on a number of 
PRs: 
https://github.com/opensearch-project/project-website/pulls?q=is%3Apr+nateynateynate
Issues: 
https://github.com/opensearch-project/project-website/issues?q=is%3Aissue+nateynateynate+
Some of the main highlights he has contributed to the repo already are the Hero Banner carousel, and the …
=> Add nateynateynate as a MAINTAINER

_sass/_style.scss
Changes the color of hyperlinked text so the links are easier to pick out. 
Resolves #1502
=> Lightens the text on hyperlinked text. 

.github/workflows/link-checker.yml
This commit limits the run of the link checker to not run on forks and will only check links 2x a month on the 1st and the 15th.
N/A
=> Reduce schedule of link checker and dont run on forks

_posts/2023-04-19-Announcing-Data-Prepper-2.2.0.md
Creates an announcement of Data Prepper 2.2.0 which is planned for release on Apr 19, 2023.
Resolves #1526
=> Created a blog post announcing Data Prepper 2.2.0

_herobanners/1.md
Currently it takes 4 clicks from the slack banner to get to the actual slack page. From there it takes quite a few more clicks to get into the slack workspace. This directs users directly to the /slack.html page.
N/A
=> Reduce clicks needed to get to Slack

_events/2023-0504-dev-officehours-dashboards.markdown, _events/2023-0518-dev-officehours-dashboards.markdown, _events/2023-0601-dev-officehours-dashboards.markdown, _events/2023-0615-dev-officehours-dashboards.markdown, _events/_0000-0000-dev-officehours-dashboards.markdown
Add event pages (and template) for the initial 4 meetings of the OpenSearch Dashboards Office Hours
Meetup links will need to be updated once meetup events are created. Forum posts are currently in the draft topic.
N/A
=> Add OpenSearch Dashboards office hours events

verify-signatures.markdown
Updates to the verify-signatures page for this year's PGP key update
added a Change Log for better tracking year over year
https://github.com/opensearch-project/project-website/issues/1562
=> Verify signatures page update

_versions/2021-07-12-opensearch-1.0.0.markdown, _versions/2021-09-01-opensearch-1.0.1.markdown, _versions/2021-10-05-opensearch-1.1.0.markdown, _versions/2021-11-23-opensearch-1.2.0.markdown, _versions/2021-12-11-opensearch-1.2.1.markdown, _versions/2021-12-16-opensearch-1.2.2.markdown, _versions/2021-12-22-opensearch-1.2.3.markdown, _versions/2022-01-18-opensearch-1.2.4.markdown, _versions/2022-03-17-opensearch-1.3.0.markdown, _versions/2022-03-30-opensearch-1.3.1.markdown, _versions/2022-05-05-opensearch-1.3.2.markdown, _versions/2022-05-26-opensearch-2.0.0.markdown, _versions/2022-06-09-opensearch-1.3.3.markdown, _versions/2022-06-16-opensearch-2.0.1.markdown, _versions/2022-07-07-opensearch-2.1.0.markdown, _versions/2022-07-14-opensearch-1.3.4.markdown, _versions/2022-08-11-opensearch-2.2.0.markdown, _versions/2022-09-01-opensearch-1.3.5.markdown, _versions/2022-09-01-opensearch-2.2.1.markdown, _versions/2022-09-14-opensearch-2.3.0.markdown, _versions/2022-10-06-opensearch-1.3.6.markdown, _versions/2022-11-15-opensearch-2.4.0.markdown, _versions/2022-12-13-opensearch-1.3.7.markdown, _versions/2022-12-13-opensearch-2.4.1.markdown, _versions/2023-01-24-opensearch-2.5.0.markdown, _versions/2023-02-02-opensearch-1.3.8.markdown, _versions/2023-02-28-opensearch-2.6.0.markdown, _versions/2023-03-16-opensearch-1.3.9.markdown, _versions/2023-05-02-opensearch-2.7.0.markdown, _versions/_2021-12-14-opensearch-1.1.1.markdown
This PR moves Data Prepper above the Logstash on the downloads page for all versions of OpenSearch.
N/A
=> Moves Data Prepper above the Logstash distribution in the downloads page

_artifacts/opensearch-1.3/arm64/opensearch-1.3.10-docker-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.10-freebsd-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.10-linux-arm64-deb.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.10-linux-arm64-rpm.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.10-linux-arm64-yum.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.10-linux-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.10-min-linux-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.10-docker-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.10-linux-arm64-deb.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.10-linux-arm64-rpm.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.10-linux-arm64-yum.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.10-linux-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.10-min-linux-arm64.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.10-docker-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.10-freebsd-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.10-linux-x64-deb.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.10-linux-x64-rpm.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.10-linux-x64-yum.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.10-linux-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.10-min-linux-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.10-windows-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.10-docker-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.10-linux-x64-deb.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.10-linux-x64-rpm.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.10-linux-x64-yum.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.10-linux-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.10-min-linux-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.10-windows-x64.markdown, _artifacts/opensearch-1.3/x86/opensearch-1.3.10-freebsd-x86.markdown, _versions/2023-05-18-opensearch-1.3.10.markdown
Download pages to prep for the 1.3.10 release - currently expected on May 18, 2023
n/a
=> 1.3.10 download pages

_events/2023-0523.markdown
The event on https://opensearch.org/events/2023-0523/ currently says:
](https://github.com/opensearch-project/project-website/assets/148721/aaf4228f-b462-4ab8-90a0-7d0ddc44796b)
Translated to my Time Zone (UTC-10), this is:
> Date: Tue, May 23, 2023
> Time: 13:00 (UTC -10)
But the meetup page says:
So one hour offset: from 12:00 to 13:00 on meetup and 13:00 to 14:00 on the website.
Assuming the time-zone is in fact "PDT" which is "UTC-7" or "UTC-8"
depending on Daylight Saving Time, this should be set to "UTC-7".
=> Fix next Community Meeting Time Zone

benchmarks/index.md, robots.txt
Add a page to display benchmarks
* Simple `IFRAME` to an OSD dashboard
* The page is temporarily excluded from search engines
=> Add a page to display benchmarks

_events/2023-0713-dev-officehours-dashboards.markdown, _events/2023-0723-dev-officehours-dashboards.markdown, _events/2023-0727-dev-officehours-dashboards.markdown, _events/2023-0810-dev-officehours-dashboards.markdown, _events/2023-0824-dev-officehours-dashboards.markdown, _events/2023-0907-dev-officehours-dashboards.markdown, _events/2023-0921-dev-officehours-dashboards.markdown
Add event pages for the next 6 meetings of the OpenSearch Dashboards Office Hours
Meetup links will need to be updated once meetup events are created. Forum posts are currently in the draft topic.
N/A
=> Add OpenSearch Dashboards office hours events Jul - Sep 2023

_events/2023-0718-2-9-release-meetings.markdown, _events/2023-0724-dev-triage-security.markdown, _events/2023-0725-efficient-vector-search-opensearch.markdown, _events/2023-0725.markdown, _events/2023-0726-search-relevance-triage-backlog.markdown, _events/2023-0727-dev-integrations-apache-spark.markdown, _events/2023-0727-dev-officehours-dashboards.markdown, _events/2023-0728-generative-ai-brainstorm.markdown, _events/2023-0731-dev-triage-security.markdown, _events/2023-0807-dev-triage-security.markdown, _events/2023-0808.markdown, _events/2023-0809-search-relevance-triage-backlog.markdown, _events/2023-0810-dev-officehours-dashboards.markdown, _events/2023-0814-dev-triage-security.markdown, _events/2023-0821-dev-triage-security.markdown, _events/2023-0822.markdown, _events/2023-0824-dev-officehours-dashboards.markdown, _events/2023-0828-dev-triage-security.markdown, _events/2023-0904-dev-triage-security.markdown, _events/2023-0907-dev-officehours-dashboards.markdown, _events/2023-0911-dev-triage-security.markdown, _events/2023-0918-dev-triage-security.markdown, _events/2023-0921-dev-officehours-dashboards.markdown, _events/2023-0925-dev-triage-security.markdown
When an event is online, we show the start date and time in the user time-zone.
When a `tz` is present, the date and time of the event in that local time zone is also shown to the user, but this is only intended to on-side events: it is intended to help the user better plan their trip.
| It currently show confusing information (local build): | With this change, less confusion for an online-event: |
|----|----|
| ![current](https://github.com/opensearch-project/project-website/assets/148721/f00320cc-2e28-4567-aa32-c5c78a0f7216) | ![after](https://github.com/opensearch-project/project-website/assets/148721/2b0862dc-3df2-4d21-8273-6b7adc279845) |
=> Remove time-zone information for online events

_events/2023-0807-dev-triage-security.markdown, _events/2023-0808.markdown, _events/2023-0809-search-relevance-triage-backlog.markdown, _events/2023-0814-dev-triage-security.markdown, _events/2023-0821-dev-triage-security.markdown, _events/2023-0822.markdown, _events/2023-0828-dev-triage-security.markdown, _events/2023-0904-dev-triage-security.markdown, _events/2023-0911-dev-triage-security.markdown, _events/2023-0918-dev-triage-security.markdown, _events/2023-0925-dev-triage-security.markdown
PT is currently PDT (UTC-7), and not PST (UTC-8).  It looks like the wrong offset was used, inducing a off-by-one error in the displayed times.
=> Fix the TZ offset of future events

_events/2023-0718-2-9-release-meetings.markdown
This seems to have been changed by mistake in a464fa34b828bf44cab69ca3912ccbcb80312fdd.
While here, use the PDT time-zone abbreviation rather that PT which is PDT or PST depending on the date.
=> Fix event link in the sidebar

_artifacts/opensearch-drivers/opensearch-odbc-1.5.0.0-macos-x64.markdown, _artifacts/opensearch-drivers/opensearch-odbc-1.5.0.0-windows-x32.markdown, _artifacts/opensearch-drivers/opensearch-odbc-1.5.0.0-windows-x64.markdown, _layouts/versions.html, _versions/2023-06-06-opensearch-2.8.0.markdown, verify-signatures.markdown
Update ODBC download links for version 1.5.0.0. Added signature verification how to links for MacOS and Windows Builds.
[Opensearch 2.8.0 · OpenSearch.pdf](https://github.com/opensearch-project/project-website/files/12089159/Opensearch.2.8.0.OpenSearch.pdf)
N/A
=> Update ODBC Driver Download Links

_sass/_pygments.scss
Requests/response code uses syntax highlighting when the specified language is `json`. However, in the current pygments style anything that is an error (does not conform to JSON syntax) is highlighted with a red box. Removing the red box will allow to still keep the JSON syntax highlighting.
=> Remove error highlighting from pygments

_sass/_redesign-conference.scss, _sass/_redesign-platform.scss
Adds additional breakpoints below 428px to accommodate greater content height for session / speaker cards and prevent the page header / title from extending beyond the width of the page.
=> Conference page mobile device breakpoint corrections

_layouts/speaker_session.html
Corrects the speaker image alt text for session page speaker cards (only observable with co-presenters).
Defaults to using the `no-image-available` placeholder image for a speaker card on the session page if the speaker data does not explicitly define one.
=> Session page speaker information patch

releases.md
updated release page to reflect https://github.com/opensearch-project/.github/issues/150
https://github.com/opensearch-project/.github/issues/150
=> updating releases page to reflect release windows

_sass/_web-fonts.scss
Removes unnecessary font weights for Open Sans Condensed.
=> Removes unused font weights for Open Sans Condensed

_artifacts/opensearch-drivers/opensearch-jdbc-1.4.0.1.markdown, _versions/2023-07-24-opensearch-2.9.0.markdown, _versions/2023-08-10-opensearch-1.3.12.markdown
JDBC driver was [released](https://github.com/opensearch-project/sql-jdbc/releases/tag/1.4.0.1) recently. It was published on maven and on artifacts. This PR adds a link to download the latest release.
Add JDBC driver 1.4.0.1 download link.
Closes #1920
=> Add JDBC 1.4.0.1 download link.

_layouts/platform-solution.html
Removes the vector database page callout card header text from the side panel.
=> Removes the vector database callout card header

_speakers/nschwartz.md
Adds the parent company name, GSI Technology, to the speaker bio for Noam Schwartz.
=> Corrects company name for conference speaker

releases.md
Updated 2.10 date to reflect move around Labor Day
https://github.com/opensearch-project/opensearch-build/issues/3954
=> updating 2.10 date for Labor day

CODE_OF_CONDUCT.md
Fixes styling of Code of Conduct page, makes "Enforcement and Reporting Code of Conduct Issues:" a header. Previously was a list item under previous header.
No Issue Made.
=> Make "Enforcement and Reporting Code of Conduct Issues:" a header

_sass/_redesign-conference.scss, events/opensearchcon/sessions/index.html
=> Add session schedule to session page

_sass/_redesign-conference.scss
Scopes new styles for session schedule to prevent global class clash. The specifically observed issue was that the visited link style on the homepage download button had been overridden with new styles for the session schedule table.
=> Scopes new styles for session schedule to prevent global class clash

releases.md
Updating 2.11 release to start Oct 4th.
https://github.com/opensearch-project/opensearch-build/issues/3955
=> updated release date of 2.11 (Making it the last release of 2023).

_layouts/homepage.html
Fix all blog button redirect to wrong url
The correct link is actually `opensearch.org/blog` not `opensearch.org/blogs`.
=> Fix all blog button redirect to wrong url

_posts/2023-09-21-hybrid-search.md
Fixing the table headings for hybrid-search blog.
https://opensearch.org/blog/hybrid-search/#:~:text=The%20following%20table%20provides%20further%20details%20of%20the%20test%20datasets%20used%20for%20benchmarking.
Wrong One
Right one
NA
=> Fixing the table headings for hybrid-search blog.

_posts/2023-10-09-byte-quantized-vectors-in-opensearch.md
3 fixes in this PR:
- add grid lines to tables
- fix math formatting
- make all images the same width
=> Fix table formatting, math, and image width in byte vector blog

_posts/2023-10-09-Announcing-Data-Prepper-2.5.0.md
Incorrectly added my author name as `graytaylor0` instead of `tylgry`, causing my description to not render on the blog post for Data Prepper 2.5.0
=> Fix incorrect author username for Data Prepper 2.5.0 blog

_events/2023-1019-fluent-community-meetup.markdown, _events/2023-1026-fluent-bit-v2-webinar.markdown, _events/2023-1102-fluent-community-meetup.markdown
Added an upcoming webinar and the next two Fluent community meetings.
Adds upcoming Fluent Bit events to the calendar
=> Add Fluent Bit events to calendar

_events/2023-1016-dev-triage-security.markdown, _events/2023-1023-dev-triage-security.markdown, _events/2023-1030-dev-triage-security.markdown, _events/2023-1106-dev-triage-security.markdown, _events/2023-1113-dev-triage-security.markdown, _events/2023-1120-dev-triage-security.markdown
We've lagged behind in putting our dev security triage and backlog meetings on the event calendar. Here's the next six weeks worth. 
N/A
=> Next six weeks worth of security backlog and triage meetings.

_posts/2023-09-25-concurrent_segment_search.markdown
The percentage for `default` case in performance table for instance 8xl should be +ve instead of -ve. There seems to be a typo
N/A
=> Fix the percentage for r5.8xl default case

_events/2023-1019-dev-officehours-dashboards.markdown, _events/2023-1102-dev-officehours-dashboards.markdown, _events/2023-1116-dev-officehours-dashboards.markdown, _events/2023-1130-dev-officehours-dashboards.markdown, _events/2023-1214-dev-officehours-dashboards.markdown
Add event pages for the next 5 meetings of the OpenSearch Dashboards Office Hours
Meetup links will need to be updated once meetup events are created. Forum posts are currently in the draft topic.
N/A
=> Add OpenSearch Dashboards office hours events Oct - Dec 2023

_sass/_opensearch.scss
Make images responsive by default
=> Make images responsive by default

_events/2023-1114-community-meeting.markdown
In my time zone, the website says "Date: 14/11/2023 Time: 12:00:00", on
meetup, I see "Tuesday, November 14, 2023 at 1:00 PM to Tuesday,
November 14, 2023 at 2:00 PM UTC−10".  Looks-like the TZ offset is not
the good one.
=> Fix date of next community meeting

_events/2023-1116-dev-officehours-dashboards.markdown, _events/2023-1130-dev-officehours-dashboards.markdown, _events/2023-1214-dev-officehours-dashboards.markdown
The event was probably using the wrong time-zone information (probably
due to daylight saving that recently changed).  While here, ensure the
join button was functional and fix its label.
The event is passed, but it will hopefuly help if it is taken as a
template to create a new event in the future.
Signed-off-by: Romain Tartière <romain@blogreen.org>
=> Fix OpenSearch Dashboards Developer Office Hours

_events/2023-0927-opensearchcon.markdown, _events/_sample.markdown, events/index.html, events/past.html
The event does not include the location information (city, country, TZ) so the event page lacks a lot of information.
While here, adjust the event logic so that events which started and are not finished at the time of rendering appear both in the future events (because it is what is displayed on the event page and the event is still in progress) and the past events.
Also adjust the event template with actual sample data in comments to make it more obvious for people using it what they need to adjust.
| Before (Currently online) | After |
|--------|-------|
| ![image](https://github.com/opensearch-project/project-website/assets/148721/4832a2cc-1dbf-4da9-b5df-48f46c4f50d2) | ![image](https://github.com/opensearch-project/project-website/assets/148721/534221ef-469e-4488-ad94-548475e881a0) | …
=> Fix OpenSearchCon 2023 info

_layouts/calendar.html, _sass/_events-calendar.scss
Adds events calendar filtering preferences persistence across month changes.
Hides the events filtering and view mode selection on mobile views, but persists the in-person toggle.
Enhances the click-away listener to allow in page links to events, or the prev/next months links to be clickable instead of only hiding the currently displayed event details popup.
=> Events calendar fast follow

_calendars/2024-01.md, _calendars/2024-02.md, _calendars/2024-03.md, _calendars/2024-04.md, _calendars/2024-05.md, _calendars/2024-06.md, _calendars/2024-07.md, _calendars/2024-08.md, _calendars/2024-09.md, _calendars/2024-10.md, _calendars/2024-11.md, _calendars/2024-12.md, _data/top_nav.yml, _includes/header.html, _layouts/calendar.html, _sass/_events-calendar.scss, _sass/_labeled-dropdown.scss, events/index.html, events/past.html
- Adds a status message for calendar and list views without any scheduled events.
- Corrects runtime URL determination based on device width for the Community -> Events top navigation menu item.
- Corrects runtime URL determination for the calendar view Events Page View Mode affordance to switch from both the Upcoming Events list view, and the Past Events list view pages.
=> No events status message, events view and link fixes

releases.md
Updating the release date for 2.12.0 per discussion
https://github.com/opensearch-project/opensearch-build/issues/4290
=> 2.12.0 Release date update

_events/2024-0131-opensearch-core-triage.markdown
Adding event for OpenSearch Core Triage meeting for 1/31
N/A
=> Add OpenSearch Core Triage meeting for 1/31

_events/2024-0207-opensearch-core-triage.markdown, _events/2024-0214-opensearch-core-triage.markdown, _events/2024-0221-opensearch-core-triage.markdown, _events/2024-0228-opensearch-core-triage.markdown, _events/2024-0306-opensearch-core-triage.markdown, _events/2024-0313-opensearch-core-triage.markdown, _events/2024-0320-opensearch-core-triage.markdown, _events/2024-0327-opensearch-core-triage.markdown
Add OpenSearch Core Triage events through the end of March
- Related https://github.com/opensearch-project/project-website/pull/2555
=> Add OpenSearch Core Triage events through the end of March

_events/2024-0214-2-12-release-meetings.markdown
[Release 2.12.0] Add go/no-go placeholder
Part of https://github.com/opensearch-project/opensearch-build/issues/4115
=> [Release 2.12.0] Add go/no-go placeholder

releases.md
Publish 2024 OpenSearch release schedule
- https://github.com/opensearch-project/.github/issues/186
=> Publish 2024 OpenSearch release schedule

_posts/2023-07-06-optimize-opensearch-index-shard-size.markdown
As far as I can tell "Backports to our repo" is just a copy/paste error. Also remove the "the managed service" text as Amazon OpenSearch Service is not the only managed offering of OpenSearch.
=> Remove extra text from end of blog post

_versions/2024-02-20-opensearch-2.12.0.markdown
The recent OpenSearch 2.12.0 release is linking to Data Prepper 2.6.1. This PR corrects that to 2.6.2.
N/A
=> Corrects the Data Prepper version for the recent OpenSearch 2.12.0 release

_posts/2021-12-15-Introducing-Data-Prepper-1.2.0-with-Log-Pipelines.md, _posts/2022-03-22-Introducing-Data-Prepper-1.3.0-with-New-Aggregation-Processor.md, _posts/2022-06-23-S3-Log-Ingestion-Using-Data-Prepper-1.5.0.md, _posts/2022-10-10-Announcing-Data-Prepper-2.0.0.md, _posts/2023-02-07-Announcing-Data-Prepper-2.1.0.md, _posts/2023-04-19-Announcing-Data-Prepper-2.2.0.md, _posts/2023-05-16-Discontinuing-custom-Logstash-distribution.md, _posts/2023-05-25-Announcing-Data-Prepper-2.3.0.md, _posts/2023-06-19-End-to-end-acknowledgements-in-Data-Prepper.md, _posts/2023-08-28-Announcing-Data-Prepper-2.4.0.md, _posts/2023-11-27-Announcing-Data-Prepper-2.6.0.md
A recent PR (#2612) changed the community member names. In it, my alias `dlv` was changed to `dvenable`, but the the blogs were not updated. This PR updates my previous blogs to use the new alias.
N/A
=> Fixes blog posts for dvenable

_posts/2023-12-05-improving-document-retrieval-with-sparse-semantic-encoders.md
In 2.11 we release the neural-sparse search feature, as well as two sparse encoding models. And we have a blog talking about this feature. Recent days we've released the models on HuggingFace model hub, users can play with our sparse_encoding models via HuggingFace and pytorch API. It will be more convinient to conduct search relevance benchmarks, or have a quick try with our models.
To inform users about this, this PR append the model links after the sparse encoding models list.
=> Update HuggingFace link for neural sparse model

.github/workflows/encoding-check.yml, .github/workflows/vale.yml
Add encoding check workflow to ensure all the files having utf-8 encoding and value continue-on-error
Closes https://github.com/opensearch-project/project-website/issues/2699
https://github.com/opensearch-project/documentation-website/pull/6722
=> Add encoding check workflow to ensure all the files having utf-8 encoding and value continue-on-error

.github/vale/styles/OpenSearch/SubstitutionsError.yml, .github/vale/styles/Vocab/OpenSearch/Words/accept.txt
OpenSearch [terms](https://github.com/opensearch-project/documentation-website/blob/main/TERMS.md) are "truststore" and "keystore". Adding those terms and rules to Vale. 
=> Add truststore and keystore rules to Vale

_community_members/chull.md, _opensearchcon_sessions/2024-europe-tune-e-commerce-search-for-success-with-chorus-and-opensearch.md
One more session: Tune E-commerce Search For Success with Chorus & OpenSearch
=> Session: Tune E-commerce Search For Success with Chorus & OpenSearch

_community_members/gkamat.md, _opensearchcon_sessions/2024-europe-unleash-your-clusters-potential-with-opensearch-benchmark.md
One more session for opensearchcon europe
=> Unleash your cluster's potential with opensearch benchmark

_community_members/dblock.md, _opensearchcon_sessions/2024-europe-how-to-become-an-opensearch-project-repo-maintainer.md
=> Welcome to the conference DB! Glad you can come!

benchmarks/index.md
This PR adds opensearch-benchmark's `PMC` workload dashboards to https://opensearch.org/benchmarks page. 
=> Add PMC workload dashboard for benchmarks page

_community_members/macrakis.md
Adds black circle to macrakis profile to indicate speaker track.  Adds macrakis into global speaker listing. 
=> Adding conference track badge to macrakis conference speaker profile.

_posts/2024-05-16-Announcing-Data-Prepper-2.8.0.md
This is the blog post for releasing Data Prepper 2.8.0. We plan to release on May 16.
Resolves #2856.
=> Data Prepper 2.8.0 release blog post. 

.github/vale/styles/OpenSearch/DashSpacing.yml
Exclude list scope from Vale dash spacing rule
=> Exclude list scope from Vale dash spacing rule

_posts/2024-04-30-A-comprehensive-guide-to-setup-and-connect-self-managed-dashboards-with-Amazon-OpenSearch-domain.md
This change should fix the yml formatting issues in the blog
=> Fixed the yaml keyword instead of yml and added bullets in the blog.

benchmarks/index.md
Add Big5 workload dashboard to [performance page. ](https://opensearch.org/benchmarks). 
=> Add Big5 workload dashboard to performance page

_events/2024-0625-2-15-release-meetings.markdown
Correct 2.15.0 meeting time on the go/nogo call
opensearch-project/opensearch-build#4681
=> Correct 2.15.0 meeting time on the go/nogo call

_events/2024-0625-2-15-release-meetings.markdown
Add 2.15.0 second go/nogo meeting on 06/24
https://github.com/opensearch-project/opensearch-build/issues/4681
=> Add 2.15.0 second go/nogo meeting on 06/24

_events/2024-0625-2-15-release-meetings.markdown
Update launch meeting dates and chime id for 2.15.0 release
https://github.com/opensearch-project/opensearch-build/issues/4681
=> Update launch meeting dates and chime id for 2.15.0 release

_posts/2024-06-19-optimizing-opensearch-with-fp16-quantization.md
Fix formatting issue of the table in fp16 blog and move the text in between those 2 tables to avoid squashing of those 2 tables.
=> Fix formatting issue of the table in fp16 blog

events/opensearchcon/2024/north-america/cfp.md, events/opensearchcon/2024/north-america/index.md
Indicates closure of CfP for OSCON 2024 NA and removes form.
=> CfP for OpenSearchCon 2024 North America is now *closed*.

.github/vale/styles/Vocab/OpenSearch/Products/accept.txt
Remove Point in Time from Vale vocabulary so the phrase "point in time" is not flagged.
=> Remove Point in Time from Vale vocabulary

.github/ISSUE_TEMPLATE/bug_template.yml, .github/ISSUE_TEMPLATE/feature_request.yml
we need to have the repo name and also the project name in order for the new issues to be assigned automatically to this project. In the github documentation, they show the numeric project numbers being used. The number "74" which is used in the feature-request template represents the "website update project".
The syntax are different between these two issues so that we can see if either will work.
Note: there are disclaimers saying that the person submitting the new-issue must have write-access to the repo for this auto-assign to the project to work. If neither of these work, likely we will have to scrap it and rely on github-workflows-autoassignissue if we want to implement this feature.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> BUG -- new issue Project-assigning is not working. 

.github/ISSUE_TEMPLATE/partner_add_new_partner.yml
Removing the empty assignes variable fixes the issue. Github is expecting an array, not a string.
=> Updated the template to fix the assignes issue

_sass/_opensearch.scss
This PR adds highlighting to the items in inline code font. Also, it removes the inner border from the code blocks and makes all font the same size. See an example image:
=> Add highlighting to inline code font

_posts/2024-06-11-A-deep-dive-into-faster-semantic-sparse-retrieval-in-OS-2.12.md
In blog `2024-06-11-A-deep-dive-into-faster-semantic-sparse-retrieval-in-OS-2.12.md` there is a wrong figure url in section `Accelerating sparse search with Lucene upgrades`. We used a duplicate link in 2 subsections. This PR fix the wrong link.
=> [Fix] fix wrong figure url in blog

_layouts/versions.html
Fixes Arch Linux install command. 
Replaces #3126 to avoid DCO.
=> Arch Linux install command.

events/opensearchcon/2024/north-america/index.md
Adds another prominent button to the landing page for OpenSearchCon North America 2024 to the registration page. 
CFP is closed - omitting the button. 
#2886 
=> One more Register Now button for OpenSearchCon NA

_events/2024-0806-2-16-release-meetings.markdown
[Release 2.16.0] Update the go/no-go voting call information
=> [Release 2.16.0] Update the go/no-go voting call information

_events/2024-0806-2-16-release-meetings.markdown
[Release 2.16.0] Update the release event with the release date and go/no-go call information
=> [Release 2.16.0] Update the release event with the release date and go/no-go call information

_events/2024-0806-2-16-release-meetings.markdown
[2.16.0 Release] Retro meeting update
https://github.com/opensearch-project/opensearch-build/issues/4771 and https://github.com/opensearch-project/opensearch-build/issues/4847
=> [2.16.0 Release] Retro meeting update

_events/2024-0806-2-16-release-meetings.markdown
[2.16.0 Release] Update the calendar date for 2.16.0 retro meeting
Part of https://github.com/opensearch-project/opensearch-build/issues/4771 and https://github.com/opensearch-project/opensearch-build/issues/4847
=> [2.16.0 Release] Update the calendar date for 2.16.0 retro meeting

.github/vale/styles/Vocab/OpenSearch/Words/accept.txt
Make Vale accept performance metrics notation like p90.
=> Add performance metrics to Vale

_data/top_nav.yml, release-metrics/index.md
For the UI mocks (the behavior) please check https://github.com/opensearch-project/opensearch-metrics/issues/69#issuecomment-2327088889.
Part of https://github.com/opensearch-project/opensearch-metrics/issues/69 and https://github.com/opensearch-project/opensearch-metrics/issues/51
=> Central view of the release metrics in the website.

_data/top_nav.yml, events/opensearchcon/2024/north-america/index.md, events/opensearchcon/2024/north-america/schedule.md, release-metrics/index.md, releases.md
Navbar update to archive opensearchcons, 
Overall opensearchcon 2024 NA schedule. 
=> OSCON schedule and navbar update. 

release-dashboard/index.md
Bug fix to update the right modal windows for the dashboards
Part of https://github.com/opensearch-project/opensearch-metrics/issues/69 and https://github.com/opensearch-project/opensearch-metrics/issues/51
=> Bug fix to update the right modal windows for the dashboards

_opensearchcon_sessions/2024/north-america/2024-north-america-how-attribute-based-access-control(abac)-can-solve-different-customer-usecases-and-be-the-future-of-fgac.md, release-dashboard/index.md
Bug fix to update the right modal windows for the dashboards. PR https://github.com/opensearch-project/project-website/pull/3273 that was merged to main branch.
Part of https://github.com/opensearch-project/opensearch-metrics/issues/69 and https://github.com/opensearch-project/opensearch-metrics/issues/51
=> [Prod] Bug fix to update the right modal windows for the dashboards

_layouts/post.html, _posts/_sample.markdown, _sass/_opensearch.scss
Adds the ability to add other information (usually, credits to more authors, reviewers, or developers of the feature) on the bottom of the right column in blog posts.
=> Add support for additional author info in blogs

_plugins/search-indexer.rb
Update blog label category for search. 
We keep all blogs in the `_post` folder and `News` may sound confusing when user looks into the search results breadcrumb. Rename it to `Blogs`.
Part of https://github.com/opensearch-project/project-website-search/issues/66
=> Update blog label category for search

_plugins/search-indexer.rb, release-dashboard/index.md
Update blog label category for search.
We keep all blogs in the `_post` folder and `News` may sound confusing when user looks into the search results breadcrumb. Rename it to `Blogs`.
=> [Backport] Backport PR from main branch: Update blog label category

_data/header_navmenu_datafile.json
Usergroups were added to the community section of the navbar.
Added usergroups to the navbar under the community section. 
The link points to the OpenSearch meetup page for now. 
#3187 
=> UserGroups added to navbar

_data/header_navmenu_datafile.json, _sass/_navbar.scss
z index issue in the navbar dropdowns. The bottom right triangle image was being overlayed ontop of the text and other images in the dropdown.
By pushing the triangle image to the back layer, and bringing the text forward, the link behavior works again. 
[[ISSUE]](https://github.com/opensearch-project/project-website/pull/3366)
=> Navbar zindex fix

_data/header_navmenu_datafile.json
Add blog url as part of subtext of roadmap
Specifically arrange this way so it wont be blocked by the picture on the right.
=> Add blog url as part of subtext of roadmap

_sass/_navbar.scss
The hover state was missing, I missed this because the "visited state" was set as the same as hover.
If someone has not previously clicked this link, it had no hover styling applied.
Fix was to apply a hover state to this button. 
=> btn hover state was missing for text

_sass/_opensearch.scss
For blog images, this PR adds:
- A rounded border with a shadow
- Padding 
=> Add border styling and padding to blog images

_posts/2024-10-15-Announcing-Data-Prepper-2.10.0.md
This PR adds the release blog post for Data Prepper 2.10. This post was written by @dlvenable and @sb2k16 who will create a separate PR with his profile.
We can start the review while we wait on us getting the profile for @sb2k16 and our Thank You text updated.
Tasks for our team before merging:
Resolves #3371
=> Data Prepper 2.10.0 release blog

_includes/bootstrap-includes.html
the bundle.min.js includes popper, which bootstrap uses to render certain elements through javascript. Specifically dropdown elements.
Removed the unpkg script that was loading the bootstrap javascript externally. 
Switched the include statement to the correct bootstrap bundle.min.js. 
#3385 
=> Removed popper and switched the javascript include.

_posts/2024-11-13-boosting-k-nn-exact-search.md
Add boosting k-NN exact search blog
=> Add boosting k-NN exact search blog

releases.md
Added release information for 1.3.20
Part of https://github.com/opensearch-project/opensearch-build/issues/4990
=> Added release information for 1.3.20

_posts/2024-11-22-faiss-byte-vector.md
Add Faiss byte vector support blog
Closes #3420 
=> Add Faiss byte vector support blog

_posts/2024-11-22-faiss-byte-vector.md
=> Meta and date change.

_artifacts/opensearch-1.3/arm64/opensearch-1.3.20-docker-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.20-freebsd-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.20-linux-arm64-deb.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.20-linux-arm64-rpm.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.20-linux-arm64-yum.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.20-linux-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-1.3.20-min-linux-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.20-docker-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.20-linux-arm64-deb.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.20-linux-arm64-rpm.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.20-linux-arm64-yum.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.20-linux-arm64.markdown, _artifacts/opensearch-1.3/arm64/opensearch-dashboards-1.3.20-min-linux-arm64.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.20-docker-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.20-freebsd-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.20-linux-x64-deb.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.20-linux-x64-rpm.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.20-linux-x64-yum.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.20-linux-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.20-min-linux-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-1.3.20-windows-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.20-docker-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.20-linux-x64-deb.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.20-linux-x64-rpm.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.20-linux-x64-yum.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.20-linux-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.20-min-linux-x64.markdown, _artifacts/opensearch-1.3/x64/opensearch-dashboards-1.3.20-windows-x64.markdown, _artifacts/opensearch-1.3/x86/opensearch-1.3.20-freebsd-x86.markdown, _versions/2024-12-10-opensearch-1.3.20.markdown
Artifacts and version markdowns for the release of 1.3.20 today (12.10.2024)
=> Release volley for 1.3.20-ga

releases.md
Per the recommendation vote of the TSC and after getting feedback on [this issue][1], we are increasing the release cadence to every eight weeks.
This only changes the documented cadence. The full 2025 release schedule will be published separately.
[1]: https://github.com/opensearch-project/.github/issues/234
Resolves https://github.com/opensearch-project/.github/issues/234
=> Update release cadence to eight weeks

_versions/2024-12-10-opensearch-1.3.20.markdown
Data prepper 2.10.2 on OS 1.3.20 download page. 
=> Data prepper 2.10.2 for Opensearch 1.3.20

release-dashboard/index.md
Onboard 3.0.0 Release
Part of https://github.com/opensearch-project/opensearch-build/issues/3747
=> Onboard 3.0.0 Release

_includes/navbar.html
commented out, instead of deleting. So that when we get the calendar fixed we can put this back.
Image shows that the link has been updated to just point to "/events/"
n/a
=> NAVBAR - Remove the script that changes all calendar links

_includes/redesign_buttons.html
On the [OpenSearchCon web page](https://opensearch.org/events/opensearchcon/2024/europe/index.html), there is a button in the left-hand column labeled "Upcoming OpenSearch Events", linking to `/events/calendars/2024-01.html`, which is a broken link.
I modified the link to go to https://opensearch.org/events/ instead which is the upcoming events page.
(no issue)
=> Fix broken link in "Upcoming OpenSearchEvents" button

_includes/footer.html, _includes/redesign_buttons.html
Updated invitation link for the Slack page
Removal of Facebook link - no longer in use by the project
https://github.com/opensearch-project/project-website/issues/3564
https://github.com/opensearch-project/project-website/issues/3526 (partially resolved) 
=> Slack url update - FB link removal

_posts/2025-01-28-OpenSearch-Now-Supports-DeepSeek-Chat-Models.md
Add some tutorials into this [blog post](https://opensearch.org/blog/OpenSearch-Now-Supports-DeepSeek-Chat-Models/).
=> Add tutorials in 'OpenSearch now supports DeepSeek chat models' Blog

_posts/2025-01-30-one-click-deepseek-integration.md
=> Updated step3 for DeepSeek using FF blogpost

_posts/2025-01-28-OpenSearch-Now-Supports-DeepSeek-Chat-Models.md
Add link to a DeepSeek demo notebook in this [blog post](https://opensearch.org/blog/OpenSearch-Now-Supports-DeepSeek-Chat-Models/).
=> Update 'OpenSearch now supports DeepSeek chat models' Blog 

release-dashboard/index.md
Change order of release versions to bump 3.0, as 2.19 is closed
Part of https://github.com/opensearch-project/opensearch-build/issues/5152
=> Change order of release versions to bump 3.0

_platforms/machineLearning.md, _redesign_use_cases/machineLearning-category.markdown
Created a new landing page for the AI / ML use case. 
N/A
=> [NEW] ML / AI Capabilities landing page 

_posts/2025-01-28-OpenSearch-Now-Supports-DeepSeek-Chat-Models.md
Apply new changes based on suggestions to this [blog post](https://opensearch.org/blog/OpenSearch-Now-Supports-DeepSeek-Chat-Models/).
=> [Blog fix] OpenSearch now supports DeepSeek chat models

_posts/2025-02-11-explore-OpenSearch-2-19.md
Update deprecation notice on 2.19 blog for 3.0
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9459
=> Update deprecation notice on 2.19 blog for 3.0

_community_members/bowenlan.md, _posts/2025-02-04-introduce-bitmap-filtering-feature.md
Notice that Froh and I don't show up as author in the blog
https://opensearch.org/blog/introduce-bitmap-filtering-feature/
This PR try to fix the problem
=> Fix the author for bitmap filtering blog

_posts/2025-03-06-Tracking-the-Evolution-of-OpenSearch-Performance.md
This is intended as a short amplification post for the TrailOfBits performance blog post.
=> Adding a summary blog post announcing publication of the TrailOfBits performance blog post

_versions/2025-03-18-opensearch-3.0.0-alpha1.markdown
Keeps 3.0.0-alpha1 from showing as 'latestl' by removing version_sort metadata. 
=> Removing version_sort metadata to keep 2.19.1 as "latest"

_posts/2025-03-18-GPU-Accelerated-Vector-Search-OpenSearch-New-Frontier.md, _versions/2025-03-18-opensearch-3.0.0-alpha1.markdown
Keeps 2.19.1 as 'latest' version by removing version_sort metadata on 3.0.0-alpha1. 
=> [prod] Keeps 2.19.1 as 'latest' version by removing version_sort metadata on 3.0.0-alpha1.

releases.md
Update 3.0.0 schedule as 3.0.0-beta1 will be delayed by 2 weeks
https://github.com/opensearch-project/opensearch-build/issues/3747
https://github.com/opensearch-project/.github/issues/300
=> Update 3.0.0 schedule as 3.0.0-beta1 will be delayed by 2 weeks

releases.md
Add release manager for 2.19.2 release
Part of https://github.com/opensearch-project/opensearch-build/issues/5419
=> Add release manager for 2.19.2 release

benchmarks/index.md
This PR adds Neural Search Benchmark dashboards to nightly benchmark so that the dashboards can be viewed in public. Related dashboards to be added: 
* [Neural Search Sparse Search Dashboard](https://benchmarks.opensearch.org/app/dashboards#/view/01b25d30-5216-11f0-b39d-2363e77eb224?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2w,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'Neural%20Search%20Sparse%20Search%20Dashboard',viewMode:view))
* [Neural Search Semantic Search Dashboard](https://benchmarks.opensearch.org/app/dashboards#/view/ee8742a0-52b7-11f0-b39d-2363e77eb224?_g=(filters:!(),query:(language:kuery,query:''),refreshInterval:(pause:!t,value:0),time:(from …
=> Add Neural Search Benchmark Dashboard to nightly benchmark

_posts/2025-07-14-OpenSearch-Approximation-Framework.md
Fixes some typos in Approximation Framework blogpost ("terminattion" --> "termination", "Additioanl" --> "Additional").
[#3903 ]
=> Fixing Typos in Approximation Framework blogpost
